.changeset/sweet-lobsters-shout.md
README.md
package.json
src/core/getFrameMetadata.ts
src/core/index.ts
src/index.ts

feat: renamed `generateFrameNextMetadata` to `getFrameMetadata`

---

.changeset/wild-poems-tell.md
README.md
package.json
src/core/getFrameAccountAddress.ts
src/index.ts
yarn.lock

feat: added initial version of `getFrameAccountAddress`, which helps getting the Account Address from the Farcaster ID using the Frame.

---

package.json
src/core/getFrameAccountAddress.ts
yarn.lock

Adding `ethers` for now, but I need to talk with those libraries and see if they can migrate to `viem`.

fix: build

---

README.md
jest.config.js
package.json
src/core/getFrameAccountAddress.test.ts
src/core/getFrameAccountAddress.ts
yarn.lock

1. Add unit tests
2. Fixed some logic + wrote unit tests

fixes: add some additional logic checks and unit tests.

---

.github/workflows/kit.yml

Time to get some CI fun!
cc @robpolak @cnasc @alvaroraminelli 

chore: added CI steps to check Format and Tests

---

package.json
src/core/getFrameAccountAddress.test.ts
src/core/getFrameAccountAddress.ts
src/core/getFrameMetadata.test.ts
src/core/getFrameValidatedMessage.test.ts
src/core/getFrameValidatedMessage.ts
src/core/mock.ts
src/index.ts
yarn.lock

fix: some tests polish for getFrameValidatedMessage

---

README.md

docs: added missing types

---

.changeset/brave-chefs-pay.md
src/core/getFrameMetadata.test.ts
src/core/getFrameMetadata.ts

Latest [Frame APIs](https://warpcast.com/v/0x24295a0a)

feat: update `getFrameMetadata` to the latest Frame APIs

---

CHANGELOG.md
README.md

docs: added missing `getFrameMetadata`

---

.changeset/metal-bugs-tease.md
README.md
src/core/farcasterTypes.ts
src/core/getFrameAccountAddress.ts
src/core/getFrameHtmlResponse.test.ts
src/core/getFrameHtmlResponse.ts
src/index.ts
src/utils/neynar/user/neynarUserFunctions.ts

feat: polished `getFrameHtmlResponse`

---

CHANGELOG.md

docs: format

---

README.md

docs: added docs for `getFrameHtmlResponse`

---

README.md

docs: polish readme links

---

.changeset/smart-actors-walk.md
src/core/getFrameMessage.ts
src/version.ts

fix: `getFrameMessage`

---

CHANGELOG.md
README.md

docs: polish

---

tsconfig.json

fix: tsc build

---

.changeset/lazy-shirts-warn.md
README.md

docs: textInput

---

.changeset/nice-bottles-arrive.md
CHANGELOG.md
src/core/farcaster.integ.ts
src/core/types.ts
src/version.ts

feat: added `textInput` to `FrameData`

---

.github/workflows/build.yml
.github/workflows/test.yml
src/version.ts

chore: ci cleanup

---

.changeset/honest-tigers-thank.md
src/components/FrameMetadata.test.tsx
src/components/FrameMetadata.tsx
src/core/types.ts
src/version.ts

feat: polished `wrapper` prop for `<FrameMetadata />` component

---

.changeset/honest-tigers-thank.md
src/components/FrameMetadata.test.tsx
src/components/FrameMetadata.tsx
src/core/getFrameHtmlResponse.test.ts
src/core/getFrameHtmlResponse.ts
src/core/getFrameMetadata.test.ts
src/core/getFrameMetadata.ts
src/core/types.ts

feat: added new `mint` and `link` Frame spec

---

.changeset/clever-maps-marry.md
README.md
src/components/FrameMetadata.test.tsx
src/components/FrameMetadata.tsx
src/core/getFrameHtmlResponse.test.ts
src/core/getFrameHtmlResponse.ts
src/core/getFrameMetadata.test.ts
src/core/getFrameMetadata.ts
src/core/types.ts
src/version.ts

Related to https://github.com/coinbase/onchainkit/issues/102

feat: made all `FrameMetadataType` parameters use consistent lowerCamelCase

---

.changeset/popular-phones-shake.md
README.md
src/core/types.ts
src/index.ts
src/version.ts

feat: exported `FrameButtonMetadata`, `FrameInputMetadata` and `FrameImageMetadata` types

---

docs/farcaster-kit.md
src/farcaster/getFarcasterUserAddress.test.ts
src/farcaster/getFarcasterUserAddress.ts

Fixing a typo in custody address

fix: Update to custody address

---

README.md
docs/.vitepress/config.mts

docs: added GA

---

src/core/getFrameHtmlResponse.test.ts

chore: added extra test

---

README.md
site/docs/pages/framekit/introduction.mdx
site/docs/pages/identitykit/introduction.mdx
site/docs/pages/index.mdx
src/core/getFrameMetadata.ts

docs: polish the new site

---

README.md

docs: readme polish

---

README.md
src/components/FrameMetadata.tsx
src/core/getFrameHtmlResponse.ts
src/core/getFrameMetadata.ts
src/core/types.ts

feat: enable `target` for `post` in Frames

---

.changeset/chatty-bananas-breathe.md
CHANGELOG.md
README.md
site/docs/pages/farcasterkit/introduction.mdx
site/docs/pages/farcasterkit/types.mdx
site/docs/pages/framekit/frame-metadata.mdx
site/docs/pages/framekit/get-frame-html-response.mdx
site/docs/pages/framekit/get-frame-metadata.mdx
site/docs/pages/framekit/introduction.mdx
site/docs/pages/framekit/types.mdx
site/docs/pages/getting-started.mdx
site/docs/pages/identitykit/avatar.mdx
site/docs/pages/identitykit/introduction.mdx
site/docs/pages/identitykit/name.mdx
site/docs/pages/identitykit/types.mdx
site/docs/pages/index.mdx
site/sidebar.ts
src/components/FrameMetadata.tsx
src/core/types.ts
src/index.ts
src/version.ts

chore: prep release

---

README.md
site/docs/pages/index.mdx
site/docs/styles.css

docs: polish dep

---

src/core/getFrameHtmlResponse.test.ts

fix: added more tests

---

site/vocs.config.tsx

fix: og image

---

site/vocs.config.tsx

docs: frames

---

.changeset/mean-gorillas-reflect.md
package.json
site/docs/pages/getting-started.mdx
site/docs/pages/index.mdx
site/docs/pages/xmtpkit/get-xmtp-frame-message.mdx
site/docs/pages/xmtpkit/introduction.mdx
site/docs/pages/xmtpkit/is-xmtp-frame-request.mdx
site/docs/pages/xmtpkit/types.mdx
src/version.ts
src/xmtp/getXmtpFrameMessage.ts
src/xmtp/isXmtpFrameRequest.ts

fix: modules imports

---

site/docs/pages/index.mdx
site/vocs.config.tsx

fix: colors

---

src/frame/getMockFrameRequest.ts
src/frame/types.ts
src/utils/neynar/frame/neynarFrameModels.ts
src/utils/neynar/frame/types.ts

Supporting new fields returned by Neynar API, including verified `sol_addresses`.
Constructed type by consulting response from https://docs.neynar.com/reference/user-bulk-by-address and confirmed the shape was correct

feat: support verified_addresses from neynar

---

.changeset/three-doors-know.md
CHANGELOG.md
src/frame/components/FrameMetadata.test.tsx
src/frame/components/FrameMetadata.tsx
src/frame/getFrameHtmlResponse.test.ts
src/frame/getFrameMetadata.test.ts
src/version.ts

feat: added Cross Site Scripting tests for frame:state

---

framegear/components/Frame/Frame.tsx

Part of #146.
Picked some distinct icons for the different button actions.

tweak: button icons (framegear)

---

.changeset/wise-chairs-leave.md
site/docs/pages/frame/types.mdx
src/frame/getFrameMessage.test.ts
src/frame/index.ts
src/frame/types.ts
src/version.ts

feat: added `transactionId` in `FrameData`

---

.changeset/loud-keys-build.md
src/frame/types.ts
src/version.ts

fix: converted the `value` for `FrameTransactionEthSendParams` to string

---

.changeset/dirty-crabs-pretend.md
site/docs/pages/frame/types.mdx
src/frame/types.ts
src/version.ts

fix: for FrameTransactionEthSendParams.data replaced Address with Hex

---

framegear/components/ValidationResults/ValidationResults.tsx

fix: format

---

.changeset/angry-fishes-greet.md
src/frame/getFrameHtmlResponse.test.ts
src/frame/getFrameHtmlResponse.ts
src/frame/getFrameMetadata.test.ts
src/frame/getFrameMetadata.ts
src/version.ts

Resolves #242 
Pass `button.target` through even if `button.action` is not set.
Unit tests

fix: `button.target` is not dependent on `button.action`

---

CHANGELOG.md

chore: format

---

package.json
src/wallet/create.ts
src/wallet/index.ts

chore: playground

---

.github/workflows/canary.yml

fix: canary

---

.github/workflows/test.yml
jest.config.js

chore: add test coverage on workflow

---

jest.config.js
src/frame/mock.test.ts
src/index.ts

chore: added deprecated comments on original imports

---

CHANGELOG.md
site/package.json
site/yarn.lock

chore: udpated pkg

---

framegear/package.json
framegear/yarn.lock
package.json
site/package.json
site/yarn.lock
yarn.lock

chore: bump @xmtp/frames-validator to 0.6

---

.changeset/soft-apricots-cross.md
src/version.ts

feat: upgraded `@xmtp/frames-validator` package to v0.6.0

---

framegear/components/Frame/Frame.tsx
framegear/utils/frameResultToFrameMetadata.test.ts
framegear/utils/frameResultToFrameMetadata.ts
framegear/utils/validation.test.ts
framegear/utils/validation.ts

- updated validation schema to match current spec
- added a handler to alert user when button action is not supported
- cleaned up a console error relating to the "Following" checkbox
- more correct handling of post_url (not 100%, but I think the cases where it would fail are cases we don't currently support)

fix: various minor framegear fixes

---

.changeset/tame-mayflies-itch.md
CHANGELOG.md
site/docs/pages/frame/types.mdx
src/frame/getFrameMessage.test.ts
src/frame/getMockFrameRequest.ts
src/frame/types.ts
src/utils/neynar/frame/convertToNeynarResponseModel.ts
src/utils/neynar/frame/types.ts
src/version.ts

This PR covers @SamuelLHuber type fix, mentioned in https://warpcast.com/samuellhuber/0xf547db59

feat: added missing address and transaction field for FrameValidationData type

---

site/docs/public/manifest.json

fix: latest manifest favicon

---

README.md
site/docs/pages/index.mdx
site/vocs.config.tsx

fix: favicon version

---

site/docs/pages/index.mdx
site/docs/styles.css
site/vocs.config.tsx

Manual
||Light|Dark|
|---|---|---|
|Home page|<img width="1791" alt="Screenshot 2024-04-20 at 3 24 20 AM" src="https://github.com/coinbase/onchainkit/assets/9765685/17a853af-ac96-40de-a3fd-18017d494965">|<img width="1792" alt="Screenshot 2024-04-20 at 3 34 00 AM" src="https://github.com/coinbase/onchainkit/assets/9765685/8f882a7c-97d0-4467-879a-7971739573c3">|
|Docs page|<img width="1792" alt="Screenshot 2024-04-20 at 3 24 31 AM" src="https://github.com/coinbase/onchainkit/assets/9765685/0bf976e2-5f8e-4a94-a3dc-d079ffe91ba4">|<img width="1792" alt="Screenshot 2024-04-20 at 3 34 11 AM" src="https://github.com/coinbase/onchainkit/assets/9765685/3a8ff7aa-eac6-4769-a124-463c7783b9ba">|

feat: kickstart landing page revamp

---

site/docs/styles.css

1. restore search bar in /getting-started
2. re-enable color transition (but only for landing page)
Manual

fix: restore search bar in /getting-started

---

site/docs/pages/index.mdx

feat(footer): adds new footer to homepage

---

site/docs/pages/index.mdx

docs: homepage

---

site/docs/pages/index.mdx
site/vocs.config.tsx

docs: better colors

---

site/docs/pages/index.mdx
site/docs/styles.css

feat: blur circles on homepage

---

.changeset/odd-ties-sing.md
site/docs/pages/identity/avatar.mdx
site/docs/pages/identity/badge.mdx
site/package.json
site/yarn.lock
src/identity/components/Avatar.test.tsx
src/identity/components/Avatar.tsx
src/identity/components/Badge.test.tsx
src/identity/components/Badge.tsx
src/identity/components/WithAvatarBadge.test.tsx
src/identity/components/WithAvatarBadge.tsx
src/identity/components/WithNameBadge.test.tsx
src/identity/components/WithNameBadge.tsx
src/version.ts

feat: polished Badge component props

---

.changeset/lucky-bobcats-leave.md
site/docs/pages/identity/badge.mdx
site/docs/pages/identity/introduction.mdx
site/docs/pages/identity/types.mdx
site/package.json
site/yarn.lock
src/identity/components/Badge.tsx
src/identity/index.ts
src/identity/types.ts
src/version.ts

feat: exported `BadgeReact` type

---

site/docs/components/FarcasterCastCard.tsx
site/docs/components/index.d.ts
site/docs/pages/index.mdx
site/package.json
site/yarn.lock

Manual
|||
|---|---|
|Light mode|<img width="1792" alt="Screenshot 2024-04-26 at 2 01 25 AM" src="https://github.com/coinbase/onchainkit/assets/9765685/c447ca69-5708-487c-a0f0-f51fd3dc6de3">|
|Dark mode|<img width="1792" alt="Screenshot 2024-04-26 at 2 01 34 AM" src="https://github.com/coinbase/onchainkit/assets/9765685/aec79565-7254-4c2b-8c7c-bf8522faf695">|
|Mobile|<img width="417" alt="Screenshot 2024-04-26 at 2 23 08 AM" src="https://github.com/coinbase/onchainkit/assets/9765685/4979a9f1-6bf8-41e6-8e83-a5ee2e818439">|

feat: add farcaster casts as embeds on landing page

---

site/docs/pages/identity/badge.mdx
site/package.json
site/yarn.lock

More polishing for the Badge page.

docs: completed Badge page

---

site/docs/pages/identity/badge.mdx
site/docs/pages/identity/get-eas-attestations.mdx

docs: used the Verified Account EAS

---

site/docs/pages/identity/introduction.mdx

typo fix
one character change 😄 
see above

fix: typo in docs

---

.changeset/lovely-meals-appear.md
site/docs/pages/identity/get-name.mdx
site/docs/pages/identity/name.mdx
site/docs/pages/identity/types.mdx
site/docs/pages/index.mdx
src/identity/components/Name.test.tsx
src/identity/components/Name.tsx
src/identity/core/getName.test.tsx
src/identity/core/getName.ts
src/identity/hooks/useName.test.tsx
src/identity/hooks/useName.ts
src/identity/types.ts
src/version.ts

feat: allow Name to showcase just Address

---

site/docs/pages/xmtp/get-xmtp-frame-message.mdx
site/docs/pages/xmtp/introduction.mdx

Updated the introduction to XMTP Kit with the metadata needed for it to work

docs: XMTP Kit update

---

site/docs/pages/identity/name.mdx
site/package.json
site/yarn.lock

docs: update pkg

---

framegear/components/FrameInput/FrameInput.tsx
framegear/components/ValidationResults/ValidationResults.tsx
framegear/utils/fetchFrame.ts

This has been changed as per request by @briandoyle81CB referencing issue #319 
Change can be better understood from following video
https://github.com/coinbase/onchainkit/assets/108223901/dc78b7e0-c690-46de-b0f7-402a9ed1bc51

feat: Made Framegear URL field autogrow

---

CHANGELOG.md
site/docs/pages/identity/introduction.mdx
site/package.json
site/yarn.lock
src/version.ts

docs: polished Identity intro

---

.changeset/fluffy-pigs-sit.md
CHANGELOG.md
site/docs/pages/identity/get-eas-attestations.mdx
site/docs/pages/identity/introduction.mdx
site/docs/pages/identity/types.mdx
site/sidebar.ts
src/identity/getAttestations.test.ts
src/identity/getAttestations.ts
src/identity/hooks/useAttestations.test.ts
src/identity/hooks/useAttestations.ts
src/identity/index.ts
src/identity/types.ts
src/queries/attestations.test.ts
src/queries/attestations.ts
src/version.ts

feat: getAttestations

---

package.json
yarn.lock

feat: added wagmi as peer dep

---

.changeset/heavy-tools-wash.md
package.json
site/package.json
site/yarn.lock

fix: removed lib

---

package.json

fix: added back `lib`

---

.changeset/tricky-pants-allow.md

fix: release

---

.changeset/odd-suns-live.md
package.json
src/version.ts

fix: revert

---

.changeset/empty-roses-boil.md
package.json

fix: keep polishing pkg

---

.changeset/quick-kangaroos-serve.md
package.json
site/package.json
site/yarn.lock

fix: packemon

---

site/package.json
site/sidebar.ts
site/yarn.lock

docs: back to work

---

site/docs/pages/wallet/AccountConnect.tsx
site/docs/pages/wallet/connect-account.mdx
site/docs/pages/wallet/introduction.mdx
site/package.json
site/yarn.lock

docs: polish Wallet intro

---

site/package.json
site/yarn.lock

docs: latest version

---

site/docs/pages/App.tsx
site/docs/pages/wallet/introduction.mdx

docs: updated preferecenes

---

.changeset/shy-toes-agree.md
src/OnchainKitConfig.test.ts
src/OnchainKitConfig.ts
src/OnchainKitProvider.tsx
src/index.ts
src/types.ts
src/useOnchainKit.test.tsx
src/useOnchainKit.tsx
src/version.ts

This PR makes it easier to have a shared config between all utilities.
Oh and we do a few deprecation in what we export.

feat: init OnchainKitConfig

---

src/queries/request.test.ts
src/queries/request.ts
src/queries/swap.test.ts
src/queries/swap.ts
src/trade/types.ts

- add types for Swap API
- add `swapAPIRequest` and JSONRPC helper functions
- add tests

feat: scaffold Swap API request and types 

---

site/docs/components/tokens.ts
site/docs/pages/token/tokenchip.mdx
site/docs/pages/token/types.mdx
src/token/components/TokenChip.test.tsx
src/token/components/TokenChip.tsx
src/token/types.ts

- add `TokenChip` component
locally

feat: TokenChip component

---

site/package.json
site/sidebar.ts
site/yarn.lock

docs: init TokenChip

---

site/package.json
site/yarn.lock

docs: pkg update

---

site/docs/pages/farcaster/introduction.mdx
site/docs/pages/farcaster/types.mdx
site/docs/pages/frame/introduction.mdx
site/docs/pages/frame/types.mdx
site/docs/pages/identity/introduction.mdx
site/docs/pages/identity/types.mdx
site/docs/pages/swap/introduction.mdx
site/docs/pages/swap/types.mdx
site/docs/pages/token/introduction.mdx
site/docs/pages/token/token-chip.mdx
site/docs/pages/wallet/introduction.mdx
site/docs/pages/wallet/types.mdx
site/docs/pages/xmtp/types.mdx

chore: doc site fix

---

CHANGELOG.md
site/docs/pages/token/token-chip.mdx
site/docs/pages/token/token-row.mdx
site/package.json
site/yarn.lock
src/token/index.ts
src/version.ts

docs: token polish

---

.changeset/brown-peaches-burn.md
site/docs/pages/token/token-selector.mdx
src/token/components/TokenSelector.test.tsx
src/token/components/TokenSelector.tsx

- update TokenSelector docs
- add useFilteredTokens for TokenSelector
Keeping useFilteredTokens internal to TokenSelector for now
Locally

chore: TokenSelector updates

---

CHANGELOG.md
site/docs/pages/token/token-selector.mdx
site/package.json
site/yarn.lock

docs: updated TokenKit

---

.changeset/fifty-adults-rest.md
src/queries/request.test.ts
src/queries/request.ts
src/version.ts

feat: added `onchainkit_version` header to API requests

---

.changeset/twenty-jeans-exercise.md
site/docs/pages/token/get-tokens.mdx
site/docs/pages/token/types.mdx
src/token/types.ts

- update getTokens docs to include address search capability

docs: update getTokens to include address search capability

---

src/version.ts

chore: release

---

CHANGELOG.md
site/docs/pages/token/token-search.mdx
site/package.json
site/yarn.lock

docs: updated

---

.changeset/three-camels-flow.md
site/docs/components/TokenSelector.tsx
site/docs/pages/token/introduction.mdx

- add new doc for TokenKit introduction
locally

docs: TokenKit introduction

---

site/docs/pages/index.mdx
site/docs/styles.css

docs: polished mobile version

---

.changeset/tender-buttons-dress.md
.gitignore
package.json
site/docs/pages/App.tsx
src/index.css
src/token/components/TokenChip.tsx
tailwind.config.js
yarn.lock

- add minimal tailwindcss integration to test it out
- trying out vanilla tailwind classNames and generated classNames
locally

feat: tailwind integration

---

.changeset/wicked-masks-sip.md
.gitignore
CHANGELOG.md
package.json
site/docs/pages/token/token-image.mdx
site/docs/pages/token/token-selector.mdx
site/package.json
site/yarn.lock
src/version.ts

fix: moved `styles.css` at top level

---

.changeset/curly-geese-exercise.md
CHANGELOG.md
package.json
site/package.json
site/yarn.lock
src/version.ts

fix: styles.css location

---

.changeset/heavy-dogs-compete.md
.gitignore
CHANGELOG.md
package.json
site/package.json
site/yarn.lock
src/version.ts

fix: style.css location

---

site/docs/pages/App.tsx
site/docs/pages/token/token-chip.mdx
site/package.json
site/yarn.lock

docs: with tailwind

---

.changeset/sour-moons-rule.md
CHANGELOG.md
README.md
site/docs/pages/index.mdx
site/docs/pages/wallet/is-wallet-a-smart-wallet.mdx
site/docs/pages/wallet/types.mdx
src/version.ts
src/wallet/index.ts
src/wallet/isWalletASmartWallet.test.ts
src/wallet/isWalletASmartWallet.ts
src/wallet/types.ts

chore: polished release

---

CHANGELOG.md
src/version.ts

chore: version

---

site/package.json
site/yarn.lock
src/version.ts

docs: latest pkg

---

README.md
site/docs/pages/getting-started.mdx

- add styles.css import instructions to docs

docs: add styles.css import to docs

---

CHANGELOG.md
site/package.json
site/yarn.lock

chore: latest site

---

site/.env.d.ts

Add ability to declare types for environment variables. Less error-prone, easier refactoring.
It's also self-contained which means your LSP should apply it only to the directory the file is created at i.e. it's only applied to the `site` directory here so you don't have conflicts in other packages where other declarations could be defined.
https://github.com/coinbase/onchainkit/assets/155655425/70973e26-d51e-48af-b7bd-008edfacb039

chore: add ability to declare types for environment variables

---

.changeset/dirty-rice-grow.md
.changeset/olive-keys-repair.md
site/docs/pages/identity/badge.mdx
src/identity/components/Avatar.css
src/identity/components/Avatar.tsx
src/identity/components/Badge.css
src/identity/components/Badge.test.tsx
src/identity/components/Badge.tsx
src/identity/components/WithAvatarBadge.tsx
src/identity/components/WithNameBadge.css
src/identity/components/WithNameBadge.test.tsx
src/identity/components/WithNameBadge.tsx
src/identity/types.ts
src/index.css
src/token/components/TokenImage.css
src/token/components/TokenImage.tsx
src/token/types.ts
src/version.ts
src/wallet/components/ConnectAccount.css
src/wallet/components/ConnectAccount.tsx

chore: completed migration to Tailwind for internal CSS classes

---

biome.json
package.json
yarn.lock

This is a reopen of https://github.com/coinbase/onchainkit/pull/469 with only changes specified in this comment https://github.com/coinbase/onchainkit/pull/469#issuecomment-2156192838

feat: add `biome`

---

biome.json
jest.setup.ts
package.json
src/OnchainKitConfig.test.ts
src/OnchainKitConfig.ts
src/OnchainKitProvider.test.tsx
src/OnchainKitProvider.tsx
src/definitions/base.ts
src/definitions/baseSepolia.ts
src/definitions/optimism.ts
src/farcaster/getFarcasterUserAddress.ts
src/getRPCUrl.test.ts
src/isBase.ts
src/queries/attestations.test.ts
src/queries/attestations.ts
src/swap/core/formatDecimals.ts
src/swap/core/getParamsForToken.ts
src/swap/types.ts
src/types.ts
src/wallet/isValidAAEntrypoint.ts
src/xmtp/getXmtpFrameMessage.test.ts

chore: lint biome

---

.changeset/eight-doors-juggle.md
src/OnchainKitProvider.test.tsx
src/OnchainKitProvider.tsx
src/queries/request.test.ts
src/queries/request.ts
src/version.ts

fix: have API_KEY set correctly by `OnchainKitProvider`

---

site/package.json
site/yarn.lock

docs: latest

---

.changeset/warm-ties-wonder.md
site/docs/pages/swap/swap.mdx
site/docs/pages/swap/types.mdx
site/package.json
site/yarn.lock
src/swap/components/Swap.tsx
src/swap/components/SwapAmountInput.test.tsx
src/swap/components/SwapButton.tsx
src/swap/types.ts

fix: Swap type

---

src/swap/components/SwapAmountInput.test.tsx
src/swap/components/SwapAmountInput.tsx

chore: Add test coverage

---

src/swap/utils.test.ts
src/swap/utils.ts

chore: remove rounding of amount

---

.changeset/short-schools-train.md
CHANGELOG.md
src/version.ts

chore: build release

---

site/docs/components/SwapAmountInputContainer.tsx
site/docs/components/TokenSelector.tsx
site/docs/components/TokenSelectorContainer.tsx
site/docs/pages/App.tsx
site/vocs.config.tsx
src/identity/components/WithAvatarBadge.tsx
src/swap/components/Swap.tsx
src/swap/components/SwapAmountInput.tsx
src/swap/components/SwapButton.tsx
src/token/components/TextInput.tsx
src/token/components/TokenChip.tsx
src/token/components/TokenRow.tsx
src/token/components/TokenSelectButton.tsx
src/wallet/components/ConnectAccount.tsx

chore: lint

---

CHANGELOG.md
package.json

chore: polish

---

src/internal/text/TextHeadline.tsx
src/internal/text/TextLabel1.tsx
src/internal/text/TextLabel2.tsx
src/internal/text/index.ts
src/swap/components/Swap.tsx
src/swap/components/SwapAmountInput.tsx
src/swap/components/SwapButton.tsx
src/token/components/TokenChip.tsx

- update Swap component style
In follow up PRs:
- Need to integrate `DM Sans` font
- Refactor text component color scheme
- Add switch token button

feat: update swap style

---

.changeset/proud-buttons-flash.md
src/identity/components/Avatar.tsx
src/identity/components/Badge.tsx

fix identity components biome lint errors
locally

fix: identity components lint errors

---

site/docs/pages/swap/types.mdx
src/swap/components/SwapAmountInput.test.tsx
src/swap/components/SwapAmountInput.tsx
src/swap/types.ts
src/token/components/TokenSelectDropdown.tsx

- add back after merging
```
<App>
<Swap>
<SwapAmountInput
label="Sell"
token={{
name: 'Ethereum',
address: '0x833589fcd6edb6e08f4c7c32d4f71b54bda02913',
symbol: 'ETH',
decimals: 18,
image: 'https://wallet-api-production.s3.amazonaws.com/uploads/tokens/eth_288.png',
chainId: 8453,
}}
swappableTokens={[
{
name: 'Ethereum',
address: '',
symbol: 'ETH',
decimals: 18,
image: 'https://wallet-api-production.s3.amazonaws.com/uploads/tokens/eth_288.png',
chainId: 8453,
},
{
name: 'USDC',
address: '0x833589fcd6edb6e08f4c7c32d4f71b54bda02913',
symbol: 'USDC',
decimals: 6,
image:
'https://d3r81g40ycuhqg.cloudfront.net/wallet/wais/44/2b/442b80bd16af0c0d9b22e03a16753823fe826e5bfd457292b55fa0ba8c1ba213-ZWUzYjJmZGUtMDYxNy00NDcyLTg0NjQtMWI4OGEwYjBiODE2', …
```

feat: Add swappable tokens to SwapAmountInput

---

.changeset/tiny-mugs-roll.md
src/swap/components/SwapAmountInput.tsx

fix Swap component where the user sets two token pairs
locally

fix: Swap for token pair mode

---

package.json
src/internal/text/TextHeadline.tsx
src/internal/text/TextLabel1.tsx
src/swap/components/Swap.tsx
src/swap/components/SwapAmountInput.test.tsx
src/swap/components/SwapAmountInput.tsx
src/swap/components/SwapToggleButton.tsx
src/swap/index.ts
src/swap/types.ts
src/token/components/TokenSelectButton.tsx

- add SwapToggleButton
- update styles
- Working on `DM Sans` font next
locally

feat: SwapToggleButton

---

.changeset/tidy-cherries-repair.md
biome.json
src/token/components/TokenSelectButton.test.tsx
src/token/components/TokenSelectButton.tsx
src/token/components/TokenSelectDropdown.tsx

- fix TokenSelectButton not detecting click event when svg element is clicked
locally

fix: TokenSelectButton hit detection

---

.changeset/cool-spies-sneeze.md
site/vocs.config.tsx

update vocs site config update
Locally

docs: vocs site config update

---

.changeset/tidy-eggs-give.md
site/docs/components/App.tsx
site/docs/components/SwapComponents.tsx
site/docs/pages/swap/swap.mdx
src/internal/text/TextMessage.tsx
src/internal/text/index.ts
src/swap/components/Swap.tsx
src/swap/components/SwapAmountInput.tsx
src/swap/components/SwapMessage.test.tsx
src/swap/components/SwapMessage.tsx
src/swap/index.ts
src/swap/types.ts
src/version.ts

feat: init SwapMessage component

---

.changeset/tidy-eggs-give.md
site/docs/components/SwapComponents.tsx
site/docs/pages/swap/swap.mdx
site/docs/pages/swap/types.mdx
src/swap/core/buildSwapTransaction.test.ts
src/swap/core/getSwapTransaction.test.ts
src/swap/core/getSwapTransaction.ts
src/swap/index.ts
src/swap/types.ts

feat: simplified `Transaction` type in `Swap` experience

---

site/docs/components/SwapComponents.tsx
site/docs/pages/swap/swap.mdx
site/package.json
site/yarn.lock

docs: updated Swap

---

.changeset/pretty-camels-allow.md
site/docs/pages/swap/build-swap-transaction.mdx
site/docs/pages/swap/get-swap-quote.mdx
site/docs/pages/swap/types.mdx
site/sidebar.ts
src/swap/index.ts
src/swap/types.ts

- fix hyperlinks in `getSwapQuote`
- add docs for `buildSwapTransaction`
- add docs for missing types
locally

feat: docs for `buildSwapTransaction` + cleanup

---

.changeset/fast-snails-carry.md
.changeset/pretty-camels-allow.md
.changeset/serious-flies-tie.md
.changeset/strong-walls-film.md
CHANGELOG.md
package.json

chore: release v0.20.15

---

.changeset/eighty-fireants-swim.md
site/docs/components/SwapComponents.tsx
site/docs/pages/swap/swap.mdx
src/swap/components/SwapAmountInput.tsx

- disable `SwapButton` in docs component
- remove `onSubmit`
- fix bug with maximum input

feat: disable `SwapButton` in docs and remove `onSubmit`

---

.changeset/swift-phones-obey.md
src/swap/components/SwapButton.tsx
src/swap/core/getTokenBalances.ts
src/utils/getRoundedAmount.test.ts
src/utils/getRoundedAmount.ts

- add default value for `disabled` prop
- handle 0n value for token balance
- handle edge case (display `0` instead of `0.` for rounded amount)

chore: fix minor issues

---

.changeset/few-beers-cry.md
site/docs/pages/identity/identity.mdx
site/docs/pages/identity/types.mdx
site/package.json
site/sidebar.ts
site/yarn.lock
src/identity/components/Identity.test.tsx
src/identity/components/Identity.tsx
src/identity/components/Name.test.tsx
src/identity/components/Name.tsx
src/identity/types.ts
src/version.ts

feat: added Name to Identity

---

.changeset/calm-spiders-brush.md
site/docs/pages/identity/identity.mdx
site/package.json
site/yarn.lock
src/identity/components/Avatar.tsx
src/identity/components/Identity.test.tsx
src/identity/components/Identity.tsx
src/identity/components/Name.tsx

fix: Identity matching Name component

---

CHANGELOG.md
site/docs/pages/identity/identity.mdx
site/package.json
site/yarn.lock
src/version.ts

chore: latest docs

---

.changeset/new-moons-act.md
site/docs/pages/identity/types.mdx
src/identity/components/Identity.tsx
src/identity/components/WithNameBadge.test.tsx
src/identity/components/WithNameBadge.tsx
src/identity/hooks/useAttestations.test.ts
src/identity/hooks/useAttestations.ts
src/identity/types.ts
src/version.ts

feat: added badge feature to Identity

---

site/docs/pages/temp-demo.mdx
site/middleware.ts

Enable geo blocking across the entire onchainkit website.
https://www.loom.com/share/22b4c51b5b7343ba8b24a14f621e81dd?sid=00f38f38-9929-4857-9136-cebb80d70c9e

feat: Enable Geo blocking across entire website

---

.changeset/thirty-vans-visit.md
package.json

-  update lib to esm for exported files
This PR are needed to unblock the theming for tailwind users

feat: update lib to esm for exported files

---

.changeset/curvy-ties-repeat.md
jest.config.js
site/docs/pages/guides/tailwind.mdx
site/package.json
site/tailwind.config.js
site/yarn.lock

- update tailwind integration guide
To test `tailwind.css` or `styles.css`, you need to run `yarn dev --clean` to run the doc site.
Otherwise, it may use a previous css cache which may give you the wrong result.
locally

fix: update tailwind integration

---

.changeset/tender-poets-exercise.md
site/docs/pages/index.mdx

Fix UI regression in index.mdx that was introduced through this [PR](https://github.com/coinbase/onchainkit/pull/659). 

fix: ui regression on index.mdx

---

site/package.json
site/yarn.lock

User exact ock version on doc site

fix: site ock version

---

README.md
site/docs/pages/identity/address.mdx
site/docs/pages/identity/avatar.mdx
site/docs/pages/identity/badge.mdx
site/docs/pages/identity/identity.mdx
site/docs/pages/identity/introduction.mdx
site/docs/pages/identity/name.mdx
site/docs/pages/identity/types.mdx
site/docs/pages/index.mdx
site/package.json
site/yarn.lock

docs: release 0.22.0 📖

---

.changeset/mean-apples-walk.md
site/docs/pages/swap/swap.mdx
site/docs/pages/swap/types.mdx

chore: Update docs with SwapButton info and remove disabled flag on swap component

---

.changeset/silent-forks-chew.md
src/internal/form/TextInput.tsx

feat: add `use client` directives to internal components

---

.changeset/four-meals-exercise.md
src/identity/components/Address.tsx
src/identity/components/Avatar.tsx
src/identity/components/DisplayBadge.tsx
src/identity/components/Identity.tsx
src/identity/components/Name.tsx
src/identity/context.ts
src/identity/hooks/useAttestations.ts
src/identity/hooks/useAvatar.ts
src/identity/hooks/useName.ts

feat: add `use client` directives to identity components

---

.changeset/fair-yaks-promise.md
src/wallet/components/ConnectAccount.tsx
src/wallet/components/Wallet.tsx
src/wallet/components/WalletDropdown.tsx

feat: add `use client` directives to wallet components

---

.changeset/three-carpets-sin.md
src/token/components/TokenChip.tsx
src/token/components/TokenRow.tsx
src/token/components/TokenSearch.tsx
src/token/components/TokenSelectButton.tsx
src/token/components/TokenSelectDropdown.tsx

feat: add `use client` directives to token components

---

.changeset/khaki-turtles-cross.md
src/internal/loading/Spinner.test.tsx
src/internal/loading/Spinner.tsx
src/swap/components/Swap.tsx

- add test for `Spinner` component
- add comments to amount change handlers
locally

chore: Add tests and comments

---

.changeset/sour-llamas-provide.md
src/swap/components/Swap.tsx
src/swap/components/SwapButton.tsx
src/swap/components/SwapMessage.test.tsx
src/swap/core/getSwapMessage.test.ts
src/swap/core/getSwapMessage.ts

- adjust messages
- add test coverage
- reset error states
locally

chore: Swap message updates

---

.changeset/brown-dragons-wash.md
src/identity/components/Avatar.tsx
src/identity/components/Badge.test.tsx
src/identity/components/Badge.tsx
src/identity/components/DisplayBadge.tsx
src/identity/components/Identity.tsx
src/identity/components/Name.test.tsx
src/identity/components/Name.tsx
src/identity/core/getName.test.tsx
src/identity/core/getName.ts
src/identity/types.ts
src/styles/theme.ts
tailwind.config.js

- add `fill` theme
- update `Name` component default font color
- add `className` prop to `Identity`
- add `className` prop to `Badge` and remove styling props
- add `className` prop to `Avatar`
- fix using `address` prop on `Avatar` and `Name` component along with `Identity`
- remove `showAddress` from `getName`
Updating docs after cutting a new release
locally

feat: identity polish

---

site/docs/pages/identity/avatar.mdx

docs: add defaultComponent and loadingComponent to avatar page

---

site/docs/pages/identity/address.mdx
site/docs/pages/identity/badge.mdx
site/docs/pages/identity/get-name.mdx
site/docs/pages/identity/name.mdx
site/docs/styles.css
site/package.json
site/yarn.lock

docs: update docs for 0.22.1 release 📖

---

site/docs/pages/guides/tailwind.mdx

docs: update tailwind instructions

---

.changeset/red-hornets-shout.md
src/identity/components/Address.tsx
src/identity/components/Avatar.tsx
src/identity/components/DisplayBadge.tsx
src/identity/components/Identity.tsx
src/identity/components/Name.tsx
src/identity/context.ts
src/identity/hooks/useAttestations.ts
src/identity/hooks/useAvatar.ts
src/identity/hooks/useName.ts
src/internal/form/TextInput.tsx
src/swap/components/Swap.tsx
src/swap/components/SwapAmountInput.tsx
src/swap/components/SwapButton.tsx
src/swap/components/SwapMessage.tsx
src/swap/components/SwapToggleButton.tsx
src/token/components/TokenChip.tsx
src/token/components/TokenRow.tsx
src/token/components/TokenSearch.tsx
src/token/components/TokenSelectButton.tsx
src/token/components/TokenSelectDropdown.tsx
src/wallet/components/ConnectAccount.tsx
src/wallet/components/Wallet.tsx
src/wallet/components/WalletDropdown.tsx

ock bundles are in correctly compiled with `use client` #684
we will unblock folks and allow a PR that handles this properly

fix: revert "use client"

---

src/token/components/TokenSearch.tsx
src/token/components/TokenSelectModal.test.tsx
src/token/components/TokenSelectModal.tsx
src/token/index.test.ts
src/token/index.ts
src/token/types.ts

https://github.com/coinbase/onchainkit/assets/132851666/5c5c3e54-76c9-484f-a87c-116d68f37b7a
In follow up PRs:
locally

feat: TokenSelectModal MVP

---

site/package.json
site/yarn.lock

docs: update doc site to v0.22.3 📖 

---

.changeset/kind-toys-leave.md
package.json
yarn.lock

fix: move tanstack to peer dependency

---

README.md
site/docs/pages/getting-started.mdx
site/docs/pages/index.mdx
site/docs/pages/xmtp/introduction.mdx
site/package.json
site/yarn.lock

docs: v0.22.5 📖

---

package.json
yarn.lock

Reverts coinbase/onchainkit#705

fix: Revert "fix: move tanstack to peer dependency"

---

package.json

Reverts coinbase/onchainkit#701

fix: Revert "fix: move viem and wagmi to peer dependencies"

---

CHANGELOG.md
site/package.json
site/yarn.lock

docs: updated site

---

.changeset/happy-feet-do.md
site/docs/pages/identity/types.mdx
src/identity/types.ts

- Update all the Token React types with className.

docs: Update Token Type docs with new className parameter

---

.changeset/cyan-pots-jump.md
site/docs/pages/swap/swap.mdx
site/docs/pages/swap/types.mdx
site/package.json
site/yarn.lock
src/swap/index.ts

Update Swap docs to include className override changes.
Add example code and visual in the documentation page for overriding each component.  
Bump `site/package.json` onchainkit version to `@0.23.2`

docs: Update Swap docs to include className override changes and examples.

---

src/identity/components/Address.test.tsx
src/identity/components/Address.tsx
src/identity/components/Avatar.test.tsx
src/identity/components/Badge.test.tsx
src/identity/components/EthBalance.test.tsx
src/identity/components/EthBalance.tsx
src/identity/components/Identity.test.tsx
src/identity/components/IdentityLayout.tsx
src/identity/components/Name.test.tsx
src/identity/index.ts
src/identity/types.ts
src/internal/testing/index.ts
src/internal/testing/mock.ts
src/internal/testing/silenceError.ts
src/internal/utils/findComponent.test.tsx
src/internal/utils/findComponent.ts
src/utils/getRoundedAmount.test.ts
src/utils/getRoundedAmount.ts

- Add `EthBalance` component
- `getRoundedAmount` renders correctly when amount is greater than 0 but less than the fractionDigit
- Add `mock` and `silenceError` testing helper functions
- Add `findComponent` helper function
locally

feat: EthBalance component

---

.changeset/nasty-knives-rush.md
src/identity/components/EthBalance.tsx
src/identity/components/Identity.tsx
src/identity/components/IdentityLayout.test.tsx
src/identity/components/IdentityLayout.tsx
src/identity/index.ts
src/identity/types.ts

- clean up
- remove `IdentityLayout` from exports
- fix `EthBalance` rendering
- add `copyAddressOnClick` to `Identity` component
locally

feat: wallet address copy

---

site/docs/components/App.tsx
site/docs/components/WalletDemo.tsx
site/docs/pages/identity/identity.mdx
site/package.json
site/yarn.lock

docs: wallet demo for QA

---

.changeset/odd-suits-hammer.md
src/wallet/components/ConnectWallet.tsx
src/wallet/components/WalletDropdown.tsx
src/wallet/types.ts

- add className to ConnectWallet and WalletDropdown
locally

feat: add className to ConnectWallet and WalletDropdown

---

.changeset/wise-goats-brake.md
src/token/components/TokenImage.tsx
src/token/components/TokenRow.tsx
src/token/components/TokenSelectDropdown.tsx

- lock TokenImage size
- Adjust `TokenRow` and `TokenSelectDropdown` to be styled with `SwapAmountInput` better
locally

chore: token components touch ups

---

.changeset/nine-yaks-yawn.md
package.json
src/swap/types.ts
src/transaction/components/Transaction.tsx
src/transaction/components/TransactionProvider.tsx
src/transaction/index.ts
src/transaction/types.ts

feat: init Transaction module

---

site/docs/components/landing/NavigationList.tsx
site/docs/pages/index.mdx
site/docs/styles.css
site/sidebar.ts

- add links to landing sections headers
- add links to sidebar headers
- adjust gradiant
- refactor code

chore: landing page polishing

---

site/docs/pages/index.mdx
site/package.json
site/yarn.lock

- disable swaps on landing page

feat: disable `SwapButton` on landing

---

package.json
yarn.lock

chore: remove duplicate dependencies

---

.changeset/big-worms-sparkle.md
.changeset/cool-nails-wash.md
.changeset/eight-buses-enjoy.md
.changeset/flat-readers-reflect.md
.changeset/forty-carpets-double.md
.changeset/moody-deers-occur.md
.changeset/nasty-singers-train.md
.changeset/wet-cougars-pay.md
package.json
yarn.lock

chore: updated Viem and Wagmi

---

.changeset/silver-geckos-think.md
biome.json
site/package.json
site/yarn.lock
src/transaction/components/TransactionGasFeeSponsor.tsx
src/transaction/index.ts
src/transaction/types.ts
src/version.ts

chore: export Transaction components

---

site/docs/pages/getting-started.mdx

- tell devs in the docs how to set smartWalletOnly for the `ConnectWallet` component

docs: update docs to set wagmiConfig to `smartWalletOnly`

---

.gitignore
package.json
site/docs/pages/transaction/transaction.mdx

fix: Transaction demo

---

site/docs/components/App.tsx
src/transaction/components/TransactionGasFee.tsx

feat: adjust writeContracts functionality

---

.changeset/six-poets-pull.md
src/transaction/components/TransactionGasFee.test.tsx

Fix transaction gas fee test which was failing on main - now passing.

chore: fix transaction gas fee test

---

.changeset/six-poets-pull.md
site/docs/pages/index.mdx

Update View Figma to link to https://www.figma.com/community/file/1370194397345450683/onchainkit. 
Update OnchainKit bottom text to match the landing page header text - needed line spacing and font bold updates. 

chore: Landing page fixes

---

site/vocs.config.tsx

docs: bye bye light theme

---

site/docs/pages/index.mdx
site/docs/pages/transaction/transaction.mdx
site/vocs.config.tsx

docs: update transaction

---

site/docs/pages/transaction/transaction.mdx
site/docs/pages/transaction/types.mdx
site/sidebar.ts
src/transaction/components/TransactionProvider.tsx
src/transaction/types.ts

- update transaction docs
- add transaction types to docs
- remove unused code

Update transaction docs and cleanup code

---

.changeset/brave-lobsters-begin.md
.changeset/curly-carrots-draw.md
CHANGELOG.md
src/identity/utils/getName.test.tsx
src/identity/utils/getName.ts
src/version.ts

fix: fetch ens

---

site/docs/pages/transaction/transaction.mdx

- update docs with transaction components

chore: update transaction docs

---

.changeset/tasty-apples-double.md
src/wallet/components/WalletDropdownDisconnect.test.tsx
src/wallet/components/WalletDropdownDisconnect.tsx

**fix**: Fix `WalletDropdownDisconnect` to correclty disconnect all connectors

[fix]: Correctly disconnect the wallet(s)

---

.changeset/long-dragons-camp.md
src/identity/constants.ts

Fix: Update resolver for Base Mainnet

---

.changeset/eight-nails-repeat.md
site/docs/pages/transaction/types.mdx
src/transaction/index.ts
src/transaction/types.ts
src/version.ts

fix: WalletCapabilities type

---

site/docs/components/TransactionWrapper.tsx
site/docs/pages/transaction/transaction.mdx
site/docs/pages/transaction/types.mdx
src/internal/svg/checkmarkSvg.tsx
src/transaction/components/Transaction.test.tsx
src/transaction/components/Transaction.tsx
src/transaction/components/TransactionButton.test.tsx
src/transaction/components/TransactionButton.tsx
src/transaction/components/TransactionProvider.tsx
src/transaction/components/TransactionSponsor.test.tsx
src/transaction/components/TransactionSponsor.tsx
src/transaction/components/TransactionToast.test.tsx
src/transaction/components/TransactionToast.tsx
src/transaction/hooks/useCallsStatus.test.ts
src/transaction/types.ts

- hide sponsor component if user hasn't provided paymaster url
- fix issue where request denied error is absorbed
- add onsuccess handler
- add disable functionality to button

chore: Additional Transaction component QA

---

src/transaction/components/TransactionSponsor.tsx

- hide sponsor component if txn in progress

Hide sponsor if txn in progress

---

.changeset/twelve-rings-return.md
site/docs/pages/transaction/transaction.mdx

Not all Transaction components had the necessary Sepolia ChainID. 
Cleanup. 

docs: Enforce Base Sepolia on Transaction.mdx 

---

site/docs/pages/transaction/types.mdx
src/transaction/components/TransactionButton.test.tsx
src/transaction/components/TransactionButton.tsx
src/transaction/components/TransactionProvider.test.tsx
src/transaction/components/TransactionProvider.tsx
src/transaction/components/TransactionSponsor.test.tsx
src/transaction/components/TransactionSponsor.tsx
src/transaction/components/TransactionToast.tsx
src/transaction/hooks/useGetTransactionStatus.test.tsx
src/transaction/hooks/useGetTransactionStatus.tsx
src/transaction/hooks/useWriteContract.test.ts
src/transaction/hooks/useWriteContract.ts
src/transaction/types.ts

- add `delayMs` prop to transaction toast
- update button text on error
- remove sponsored by name
- update to use `writeContractAsync` instead of `writeContract`

continued Transaction component QA

---

site/docs/pages/transaction/transaction.mdx

- txn sponsor no longer takes text as prop

Remove sponsor name text from docs

---

site/docs/pages/transaction/transaction.mdx

Remove tooltip in Transactions page after adding Base Sepolia switcher. 

docs: remove tooltip

---

site/docs/pages/guides/reporting-bug.mdx
site/docs/pages/transaction/transaction.mdx
site/sidebar.ts
site/vocs.config.tsx

Update "report a bug" to landing page

docs: Update "report a bug" to landing page + docs

---

site/docs/components/App.tsx
site/docs/pages/wallet/wallet.mdx

https://linear.app/coinbase/issue/BOE-101/add-change-text-feature-to-docs

chore: Add change text feature to Wallet docs

---

src/wallet/components/ConnectWallet.test.tsx
src/wallet/components/ConnectWallet.tsx

Fix Wallet component when it's active

fix: wallet dark mode

---

site/docs/styles.css

Fix landing page background
locally

fix: landing page background

---

site/docs/components/TokenSelector.tsx
site/docs/pages/index.mdx
site/docs/styles.css

fix: landing page token selector styling
locally

fix: landing page token selector styling

---

site/docs/pages/getting-started.mdx
site/docs/pages/transaction/transaction.mdx

Fix formatting on "Transaction page" + adding missing component to "Getting started"

Docs: Fix formatting + missing components

---

README.md
site/docs/pages/index.mdx
site/vocs.config.tsx

docs: template

---

site/docs/pages/guides/tailwind.mdx
site/tailwind.config.js

landing page text color
locally

fix: landing page text color

---

.changeset/many-ravens-cry.md
src/transaction/components/TransactionToast.test.tsx

<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

chore: Add testing to Transaction Toast.

---

vitest.config.ts

chore: coverage

---

src/swap/components/SwapAmountInput.tsx
src/swap/components/SwapProvider.tsx
src/swap/hooks/useSwapBalances.tsx
src/swap/types.ts
vitest.config.ts

chore: useValue cleanup

---

src/transaction/constants.ts
src/transaction/hooks/useCallsStatus.ts
src/transaction/hooks/useWriteContract.ts
src/transaction/hooks/useWriteContracts.ts
src/transaction/types.ts
src/transaction/utils/isSpinnerDisplayed.ts

chore: types

---

playground/nextjs-app-router/next.config.mjs
playground/nextjs-app-router/package.json
src/swap/components/SwapButton.stories.tsx
src/swap/components/SwapToggleButton.stories.tsx
src/swap/utils/fromReadableAmount.ts
src/swap/utils/toReadableAmount.ts

- fix the `next build` step in playground so we can successfully create dev deployments off branches

fix: playground build

---

src/internal/svg/fundWallet.tsx

fix: update fundWallet viewbox

---

vercel/vercel.json

feat: vercel rewrites

---

vercel/vercel.json

chore: vercel routes

---

src/network/neynar/getCustodyAddressForFidNeynar.test.ts
src/network/neynar/getVerifiedAddressesForFidNeynar.test.ts
vercel/vercel.json
vitest.config.ts

chore: more tests

---

playground/nextjs-app-router/components/demo/Swap.tsx

fix: disable swap on playground

---

README.md
biome.json
site/docs/components/App.tsx
site/docs/components/TokenSelector.tsx
site/docs/components/TransactionWrapper.tsx
site/docs/components/landing/NavigationList.tsx
site/docs/components/svg/walletDropdownLinkCustomBaseIconSvg.tsx
site/sidebar.ts
site/vocs.config.tsx
vercel/vercel.json

chore: biome with site

---

vercel/vercel.json

fix: routes

---

site/docs/components/landing/NavigationList.tsx
site/docs/pages/frame/frame-metadata.mdx
site/docs/pages/identity/identity.mdx
site/docs/pages/index.mdx
site/docs/pages/swap/swap.mdx
site/docs/pages/transaction/transaction.mdx
site/docs/pages/wallet/wallet.mdx
site/docs/styles.css
src/identity/components/IdentityLayout.test.tsx
src/identity/components/IdentityLayout.tsx
src/identity/hooks/usePopover.ts
src/swap/components/SwapAmountInput.tsx
src/swap/components/SwapProvider.tsx
src/token/components/TokenSelectDropdown.tsx
src/token/components/TokenSelectModal.tsx
vitest.config.ts

chore: fix docs and added tests

---

playground/nextjs-app-router/components/demo/Wallet.tsx

The Wallet component would be removed from the DOM and not return when the user disconnected their wallet.
Removed conditional rendering

fix: Playground Wallet rendering 

---

src/swap/components/Swap.tsx
src/swap/components/SwapAmountInput.test.tsx
src/swap/components/SwapProvider.test.tsx
src/swap/components/SwapProvider.tsx
src/swap/components/SwapToggleButton.test.tsx
src/swap/hooks/useFromTo.test.ts
src/swap/hooks/useSwapBalances.test.tsx
src/swap/mocks.ts
src/swap/types.ts
src/swap/utils/buildSwapTransaction.test.ts
src/swap/utils/buildSwapTransaction.ts
src/swap/utils/getAPIParamsForToken.test.ts
src/swap/utils/getAPIParamsForToken.ts
src/swap/utils/getSwapMessage.test.ts
src/swap/utils/getSwapQuote.test.ts
src/swap/utils/getSwapQuote.ts
src/swap/utils/getTokenBalanceErrorState.test.ts
src/swap/utils/getTokenBalances.test.ts
src/transaction/components/TransactionProvider.tsx
src/wallet/hooks/useGetETHBalance.test.ts
src/wallet/hooks/useGetETHBalance.ts
src/wallet/hooks/useGetTokenBalance.test.ts
src/wallet/hooks/useGetTokenBalance.ts
vitest.config.ts

feat: init setLifeCycleStatus in Swap experience

---

package.json

- Adding pay module to begin build out of crypto payment functionality
- Empty module, more to come
- CI

feat: Add pay module

---

src/wallet/components/ConnectButton.tsx
src/wallet/components/ConnectWallet.test.tsx
src/wallet/components/ConnectWallet.tsx
src/wallet/types.ts
vitest.config.ts

chore: test

---

CHANGELOG.md
src/swap/components/SwapButton.tsx
src/swap/components/SwapProvider.test.tsx
src/swap/components/SwapProvider.tsx
src/swap/types.ts
src/swap/utils/processSwapTransaction.test.ts
src/swap/utils/processSwapTransaction.ts
vitest.config.ts

chore: move away from onStart and using only onStatus for advance lifeCycleStatus

---

site/docs/pages/identity/identity.mdx

chore: fix typo in Identity code snippet

---

src/swap/components/SwapAmountInput.test.tsx

chore: Add SwapAmountInput unit test

---

site/docs/pages/swap/swap.mdx

- noticed when i copied the code some of it was unnecessary and some was broken

chore: fix Swap docs

---

site/docs/pages/swap/types.mdx

docs: types

---

src/transaction/components/TransactionProvider.test.tsx

Added tests for success and failure on legacy write contract, removed a test that didn't seem to be doing anything

chore: add transaction provider tests

---

.changeset/green-elephants-matter.md
src/swap/components/SwapProvider.test.tsx
src/swap/components/SwapProvider.tsx
vitest.config.ts

fix: error message

---

README.md
site/docs/pages/index.mdx
site/docs/styles.css
site/sidebar.ts
src/internal/utils/formatTokenAmount.test.ts
src/swap/components/SwapProvider.tsx
vitest.config.ts

docs: code coverage

---

.changeset/cyan-jokes-bathe.md
src/network/constants.ts
src/network/request.test.ts
src/network/request.ts

- add `onchainkit-version` header to API requests

feat: add `onchainkit-version` header to API requests

---

playground/nextjs-app-router/components/demo/Identity.tsx
site/docs/pages/guides/contribution.mdx
site/docs/pages/guides/reporting-bug.mdx
site/docs/pages/guides/tailwind.mdx
site/docs/pages/guides/use-basename-in-onchain-app.mdx
site/docs/pages/identity/get-address.mdx
site/docs/pages/identity/get-name.mdx
site/docs/pages/identity/name.mdx
site/docs/pages/identity/types.mdx
site/docs/pages/identity/use-address.mdx
site/docs/pages/identity/use-avatar.mdx
site/docs/pages/identity/use-name.mdx
site/sidebar.ts
src/identity/types.ts

docs: use basename

---

src/swap/components/SwapProvider.test.tsx
src/swap/components/SwapProvider.tsx

chore: Reset lifecycle state after Swap success

---

site/docs/pages/guides/lifecycle-status.mdx

docs: Fix lifecycle spelling

---

site/docs/pages/swap/swap.mdx

- The goal of this PR is to make the Swap component instantly usable after copy/pasting from docs with no errors
- Added missing imports for Avatar and Swap Message
- Added images for tokens to fix type errors in IDE
- Placed the tokens into the swappableTokens const so that the component is usable after copy/pasting
- Open to suggestions about which img urls to use for tokens
- Visually on localhost
- Copy pasted the code and ran it without errors

Swap doc improvements

---

site/docs/public/robots.txt

docs: added robots.txt

---

vercel/vercel.json

chore: redirect

---

vercel/vercel.json

chore: redirect part II

---

vercel/vercel.json

chore: redirect part III

---

site/docs/components/TransactionWrapper.tsx
site/docs/pages/guides/lifecycle-status.mdx
site/docs/pages/transaction/transaction.mdx
site/docs/pages/transaction/types.mdx
site/package.json
site/yarn.lock

docs: transaction

---

src/swap/components/SwapProvider.test.tsx
src/swap/components/SwapProvider.tsx
src/swap/components/SwapSettingsSlippageInput.test.tsx
src/swap/components/SwapSettingsSlippageInput.tsx
src/swap/types.ts
src/swap/utils/processSwapTransaction.test.ts
src/swap/utils/processSwapTransaction.ts

feat: added type LifecycleStatusDataShared

---

src/identity/index.ts

chore: export getAddress

---

.changeset/fluffy-apes-float.md
src/transaction/components/TransactionButton.tsx

fix: Transaction style

---

src/transaction/components/Transaction.test.tsx
src/transaction/components/Transaction.tsx
src/transaction/components/TransactionProvider.tsx
src/transaction/types.ts

feat: default chainId option with Transaction

---

site/docs/pages/index.mdx

feat: add twoslash to homepage

---

site/docs/components/WalletComponents.tsx
site/docs/pages/transaction/transaction.mdx
site/docs/pages/wallet/wallet.mdx

docs: wallet story time

---

playground/nextjs-app-router/components/AppProvider.tsx
playground/nextjs-app-router/components/Demo.tsx
playground/nextjs-app-router/components/OnchainProviders.tsx
playground/nextjs-app-router/components/demo/Swap.tsx
playground/nextjs-app-router/components/form/swap-config.tsx
playground/nextjs-app-router/package.json
src/swap/components/SwapSettingsSlippageInput.tsx

- add swap config to playground
- fix bug with `Auto` resetting to default

chore: add swap config to playground

---

site/docs/pages/swap/swap.mdx
site/docs/pages/swap/types.mdx

docs: isSponsored for `Swap`

---

site/docs/pages/swap/swap.mdx
site/docs/pages/swap/types.mdx

chore: add `SwapToast` to docs

---

.changeset/shy-forks-explode.md

chore: add onramp changeset

---

site/docs/pages/getting-started.mdx

- Update our getting started page to be more beginner friendly. 
- Clean up unclear instructions, missing links, and missing variables 

docs: updating our getting started page

---

playground/nextjs-app-router/components/Demo.tsx
playground/nextjs-app-router/components/demo/Swap.tsx

update playground to have a collapsable menu on mobile

fix: update playground for mobile

---

site/docs/pages/getting-started.mdx

feat: docs quickstart

---

playground/nextjs-app-router/components/OnchainProviders.tsx
playground/nextjs-app-router/lib/constants.ts

chore: Add OnchainKit CDP ProjectID to Playground

---

site/docs/pages/getting-started.mdx

fix `wagmi.ts` in `Getting Started`

---

playground/nextjs-app-router/components/Demo.tsx
playground/nextjs-app-router/components/demo/Identity.tsx

- Update the Identity component to be dynamically rendered based on `useAccount` Wagmi hook
- Minor updates to hover link animation

playground: fixes of the identity component

---

playground/nextjs-app-router/components/Demo.tsx
playground/nextjs-app-router/components/demo/Identity.tsx

chore: fix ci

---

src/swap/constants.ts
src/swap/utils/getSwapMessage.ts

fix: swap error message

---

playground/nextjs-app-router/components/AppProvider.tsx
playground/nextjs-app-router/components/Demo.tsx
playground/nextjs-app-router/components/demo/TransactionDefault.tsx
playground/nextjs-app-router/components/form/active-component.tsx
playground/nextjs-app-router/components/form/transaction-options.tsx
src/transaction/components/TransactionButton.tsx
src/transaction/components/TransactionDefault.test.tsx
src/transaction/components/TransactionDefault.tsx
src/transaction/index.ts
src/transaction/types.ts

feat: add TransactionDefault component

---

site/docs/pages/swap/swap.mdx
site/docs/pages/swap/types.mdx
site/docs/pages/transaction/transaction.mdx
site/docs/pages/transaction/types.mdx
site/docs/pages/wallet/wallet.mdx

feat: Add docs for default components

---

site/docs/components/landing/Tweets.tsx
site/docs/styles.css

docs: Update Tweet on Landing Page

---

site/docs/pages/fund/fund-button.mdx

fix: fund docs typo

---

src/fund/utils/getOnrampBuyUrl.test.ts
src/fund/utils/getOnrampBuyUrl.ts

Added the sdkVersion param to the onramp URL.
Unit tests.

fix: add sdkVersion param to onramp url

---

src/pay/components/PayButton.tsx

fix: remove `onTouchStart` in `PayButton`

---

site/docs/pages/fund/fund-button.mdx

docs: fix typo on fund docs

---

src/wallet/components/WalletDefault.tsx

- WalletDefault imports sub components from index instead of individual files creating circular dependency

chore: fix circular dependency with WalletDefault

---

src/internal/components/QuantitySelector.test.tsx
src/internal/components/QuantitySelector.tsx
src/internal/components/TextInput.tsx

Add QuantitySelector component 

feat: add quantity selector

---

playground/nextjs-app-router/app/globals.css
playground/nextjs-app-router/components/AppProvider.tsx
playground/nextjs-app-router/components/form/component-theme.tsx
src/styles/tailwind-base.css
src/types.ts
src/useTheme.test.ts
src/useTheme.ts

Updated the `Minimal` theme name to `Hacker`. 

chore: Update theme name Minimal to Hacker

---

site/docs/pages/pay/pay.mdx
site/package.json
site/yarn.lock

docs: `Pay` advanced usage

---

.github/workflows/test.yml

fix: `yarn test` CI/CD

---

src/pay/components/PayProvider.test.tsx

chore: fix flaky test

---

site/docs/pages/getting-started.mdx

chore: suffix `latest` to cli command

---

site/docs/pages/getting-started.mdx
site/docs/pages/guides/lifecycle-status.mdx
site/sidebar.ts

- Make navigation cleaner
- Updated "getting started" guides to call out `<Provider />` wrapping

docs: fixes

---

src/version.ts

fix: version

---

.changeset/mighty-kings-knock.md

chore: update changeset

---

.changeset/olive-boats-guess.md

chore: Add custom theming changeset

---

site/docs/pages/getting-started.mdx

- Make edits to "Getting Started"

docs: update "getting-started"

---

playground/nextjs-app-router/components/AppProvider.tsx
playground/nextjs-app-router/components/demo/Transaction.tsx
playground/nextjs-app-router/components/form/transaction-options.tsx
src/transaction/components/TransactionProvider.test.tsx
src/transaction/components/TransactionProvider.tsx
src/transaction/types.ts

adds the callsback support to transactions component

fix: transaction callbacks

---

site/docs/pages/transaction/transaction.mdx
site/docs/pages/wallet/wallet.mdx

Fixing some typos in the `Transaction` and `Wallet` docs

docs: fix typos in docs

---

site/docs/pages/checkout/checkout.mdx

docs: `Checkout`polish

---

src/internal/svg/infoSvg.tsx
src/internal/utils/multiplyFloats.test.ts
src/internal/utils/multiplyFloats.ts
src/nft/components/mint/NFTAssetCost.test.tsx
src/nft/components/mint/NFTAssetCost.tsx
src/nft/components/mint/NFTCreator.test.tsx
src/nft/components/mint/NFTCreator.tsx
src/nft/components/mint/NFTMintButton.test.tsx
src/nft/components/mint/NFTMintButton.tsx
src/nft/components/mint/NFTMinters.test.tsx
src/nft/components/mint/NFTMinters.tsx
src/nft/components/mint/NFTQuantitySelector.test.tsx
src/nft/components/mint/NFTQuantitySelector.tsx
src/nft/components/mint/NFTTotalCost.test.tsx
src/nft/components/mint/NFTTotalCost.tsx
src/nft/components/mint/index.ts

feat: add mint components

---

.changeset/yellow-parrots-sing.md
playground/nextjs-app-router/components/AppProvider.tsx
playground/nextjs-app-router/components/OnchainProviders.tsx
src/OnchainKitConfig.ts
src/OnchainKitProvider.test.tsx
src/OnchainKitProvider.tsx
src/checkout/components/CheckoutProvider.tsx
src/index.ts
src/types.ts

- add `name` and `logo` to `config.appearance` in `OnchainKitProvider`
- introduce `AppConfig` type
- pull these values in the `Checkout` component for wallet connection
tested in playground

feat: add `name` and `logo` to OnchainKitProvider

---

site/docs/components/landing/FundDemo.tsx

- Fund was disabled if wallet isn't connected.
- Add wallet connection to fund if wallet is not connected
https://github.com/user-attachments/assets/f27a6bef-3825-49da-8ffc-42af8614b774

add wallet connection to fund if wallet is not connected

---

create-onchain/src/cli.ts
create-onchain/templates/next/app/page.tsx

- Added "client api key" to CLI installation process to minimize confusion

chore: add "client api key" to cli installation

---

site/docs/pages/transaction/transaction.mdx
site/docs/pages/transaction/types.mdx

update transaction docs for promises

docs: update transaction docs

---

site/docs/components/App.tsx
site/docs/components/landing/CheckoutDemo.tsx
site/docs/components/landing/ComponentPreview.tsx
site/docs/components/landing/FundDemo.tsx
site/docs/components/landing/IdentityDemo.tsx
site/docs/components/landing/SwapDemo.tsx
site/docs/components/landing/TransactionDemo.tsx
site/docs/components/landing/WalletDemo.tsx
site/docs/components/landing/getHighlightedCode.tsx
site/docs/contexts/Theme.tsx
site/docs/layout.tsx

* Added syntax highlighting to component code snippets
Before (Light):
After (Light):
Before (Dark):
After (Dark):
* locally

feat: landing page code highlighting

---

src/nft/components/mint/NFTMintButton.test.tsx
src/nft/components/mint/NFTMintButton.tsx
src/nft/types.ts

feat: pass through transaction overrides

---

playground/nextjs-app-router/app/mint/MintComponent.tsx

fix: mint id

---

playground/nextjs-app-router/components/Demo.tsx
site/docs/components/landing/ComponentPreview.tsx
site/docs/components/landing/getHighlightedCode.tsx
site/docs/pages/swap/swap.mdx
site/docs/styles.css

* changed spacing on sidebar links so they don't overlap
* before: 
* after: 
* fixed twoslash pop-up hover background
* before: 
* after: 
* fixed code snippet newline issue on homepage
* before: 
* after: 
locally

fix: display issues

---

create-onchain/templates/next/app/page.tsx

chore: fix lightmode formatting

---

playground/nextjs-app-router/components/demo/NFTMintCard.tsx
src/nft/components/mint/NFTAssetCost.test.tsx
src/nft/components/mint/NFTAssetCost.tsx
src/nft/components/mint/NFTCollectionTitle.tsx
src/nft/components/mint/NFTCreator.tsx
src/nft/components/mint/NFTMintButton.tsx
src/nft/components/mint/NFTMinters.tsx
src/nft/components/mint/NFTQuantitySelector.tsx
src/nft/components/mint/NFTTotalCost.test.tsx
src/nft/components/mint/NFTTotalCost.tsx
src/nft/components/view/NFTAudio.tsx
src/nft/components/view/NFTImage.tsx
src/nft/components/view/NFTLastSoldPrice.tsx
src/nft/components/view/NFTMedia.tsx
src/nft/components/view/NFTMintDate.tsx
src/nft/components/view/NFTNetwork.tsx
src/nft/components/view/NFTOwner.tsx
src/nft/components/view/NFTTitle.tsx

fix: nft style tweaks

---

create-onchain/templates/next/app/page.tsx

updated to use [tailwind dark mode](https://tailwindcss.com/docs/dark-mode)
| dark | light |
| ------- | -------- |
| ![image](https://github.com/user-attachments/assets/37837977-4301-4ad8-9563-02880392037e) | ![image](https://github.com/user-attachments/assets/e1bed0ef-b5a0-4aec-9249-6c6a97fcf183) |

fix: light/dark mode

---

src/internal/components/QuantitySelector.tsx
src/internal/utils/multiplyFloats.test.ts
src/internal/utils/multiplyFloats.ts
src/nft/components/mint/NFTAssetCost.test.tsx
src/nft/components/mint/NFTAssetCost.tsx
src/nft/components/view/NFTAudio.tsx

* Add a hover state to the Quantity Selector input
* small tweak on play button
* remove foreground muted on $
* updated multiplyFloats

fix: small style tweaks

---

src/nft/components/NFTMintCard.tsx
src/nft/components/NFTProvider.tsx
src/nft/components/mint/NFTMintButton.test.tsx
src/nft/components/mint/NFTMintButton.tsx
src/nft/types.ts

fix: nft is sponsored

---

playground/nextjs-app-router/components/Demo.tsx
playground/nextjs-app-router/components/demo/Identity.tsx
playground/nextjs-app-router/components/demo/IdentityCard.tsx
src/identity/components/IdentityLayout.tsx

chore: Update sizing and clean up Identity and IdentityCard playground

---

playground/nextjs-app-router/lib/nft/buildMintTransaction.ts
playground/nextjs-app-router/onchainkit/package.json
src/nft/components/mint/NFTMintButton.test.tsx
src/nft/components/mint/NFTMintButton.tsx
src/transaction/types.ts

Safari blocks popups when an api call is triggered before it is shown

fix: rewrite mint button using useEffect

---

playground/nextjs-app-router/lib/nft/buildMintTransaction.ts
src/nft/components/mint/NFTMintButton.tsx

| -------- | -------- |
| ![image](https://github.com/user-attachments/assets/447ba448-27a9-46c0-acfe-c97e30ffd98d) | ![image](https://github.com/user-attachments/assets/ae9348d5-7e95-40dd-8764-c1ff24f51168) |

fix: mint button api errors

---

.changeset/kind-stingrays-cross.md
src/nft/components/view/NFTImage.tsx
src/nft/components/view/NFTMedia.tsx
src/nft/components/view/NFTVideo.tsx

| ------ | ------ |
|  ![image](https://github.com/user-attachments/assets/ff7e9216-36b6-4244-81c2-7add898cf495) | ![image](https://github.com/user-attachments/assets/2389c6f9-b3c0-41fd-b827-c7a0538a2881) |
| ![image](https://github.com/user-attachments/assets/644bbb9c-1d86-4d9d-8534-d1c6d6b52fa5) | ![image](https://github.com/user-attachments/assets/7e96f6c9-17a0-46ec-9cdf-d166a6af7e4c) |

fix: default media to square

---

src/transaction/components/TransactionButton.test.tsx
src/transaction/components/TransactionButton.tsx

chore: update Transaction link for smart wallets

---

site/docs/pages/identity/identity-card.mdx

docs: Add schemaID parameter to IdentityCard examples

---

site/docs/pages/getting-started.mdx

- Make "getting started" more succinct

docs: small edits

---

src/nft/index.ts
src/nft/types.ts

* exporting useNFTData and BuildMintTransaction types
* small type comment updates

fix: update types, export apis

---

src/nft/components/NFTCard.test.tsx
src/nft/components/NFTCard.tsx

Update the NFTCard component to go to zora onclick instead of opensea

fix: update opensea to zora

---

.changeset/rich-elephants-give.md
playground/nextjs-app-router/components/AppProvider.tsx
playground/nextjs-app-router/components/Demo.tsx
playground/nextjs-app-router/components/DemoOptions.tsx
playground/nextjs-app-router/components/demo/NFTCardDefault.tsx
playground/nextjs-app-router/components/demo/NFTMintCardDefault.tsx
playground/nextjs-app-router/components/form/active-component.tsx
playground/nextjs-app-router/components/form/nft-options.tsx
src/nft/components/NFTCardDefault.test.tsx
src/nft/components/NFTCardDefault.tsx
src/nft/components/NFTMintCardDefault.test.tsx
src/nft/components/NFTMintCardDefault.tsx
src/nft/index.ts
src/nft/types.ts
src/transaction/components/TransactionDefault.test.tsx

Add NFTCardDefault and NFTMintCardDefault components, allowing you to use our pre-defined child components.

feat: add NFT defaults

---

site/docs/components/landing/FundDemo.tsx
site/docs/pages/fund/fund-button.mdx

docs: fix typo in fund code examples

---

create-onchain/package.json
create-onchain/src/cli.ts

`.env` file is not breaking lines correctly after #1561. This fixes the regression.

fix: fix misconfigured `.env` file in create-onchain CLI

---

site/docs/pages/api/build-mint-transaction.mdx
site/docs/pages/api/build-swap-transaction.mdx
site/docs/pages/api/get-mint-details.mdx
site/docs/pages/api/get-swap-quote.mdx
site/docs/pages/api/get-token-details.mdx
site/docs/pages/api/get-tokens.mdx
site/docs/pages/guides/build-onchain-apps.mdx
site/docs/pages/installation/astro.mdx
site/docs/pages/installation/nextjs.mdx
site/docs/pages/installation/remix.mdx
site/docs/pages/installation/vite.mdx

docs: update client API key url

---

create-onchain/package.json

chore: update cli version

---

site/docs/pages/config/onchainkit-provider.mdx

docs: fix typo in provider docs

---

src/transaction/components/TransactionProvider.test.tsx

* updated a test in TransactionProvider
* previously, test was flakey
* made test more explicit, and added an additional mock to make sure we test the intended case
via test suite

fix: flakey tx test

---

site/README.md
site/docs/components/App.tsx
site/docs/components/landing/CheckoutDemo.tsx
site/docs/components/landing/ComponentPreview.tsx
site/docs/components/landing/FundDemo.tsx
site/docs/components/landing/IdentityDemo.tsx
site/docs/components/landing/NftMintCardDemo.tsx
site/docs/components/landing/SwapDemo.tsx
site/docs/components/landing/TransactionDemo.tsx
site/docs/components/landing/WalletDemo.tsx

* updated landing page code snippets to be runnable demo functions
* added NFTMintCard to previews
* locally

feat: homepage updates

---

src/transaction/components/TransactionDefault.tsx

chore: add contracts back to txn default

---

site/.gitignore
site/docs/components/AppWithWalletModal.tsx
site/docs/pages/wallet/wallet.mdx

fix: fix docs site build

---

create-onchain/package.json

chore: update version for `create-onchain`

---

site/docs/pages/installation/nextjs.mdx

* changed installation instruction for nextjs to use Nextjs v14 instead of `@latest`
locally

fix: next installation steps

---

playground/nextjs-app-router/onchainkit/package.json
playground/nextjs-app-router/tsconfig.json

fix: update tsconfig.json to fix auto-imports in dev:watch mode

---

src/checkout/components/CheckoutButton.test.tsx
src/checkout/components/CheckoutButton.tsx

- changed `Pay with Crypto` to `Pay`

chore: modify `Checkout` button copy

---

site/docs/pages/guides/using-ai-powered-ides.mdx
site/sidebar.ts

[docs] updating docs to include ai-powered ide guides

---

package.json
playground/nextjs-app-router/onchainkit/package.json
src/styles/tailwind-base.css
tailwind.config.js
yarn.lock

* Add tailwindcss-animate and remove tailwind config animations
* Created apply classes to allow the Toast component to work unchanged, since this is only internal we could refactor

feat: tailwindcss-animate

---

src/fund/utils/subscribeToWindowMessage.test.ts
src/fund/utils/subscribeToWindowMessage.ts

fix: onramp listener function bug

---

site/docs/pages/identity/avatar.mdx

Hey !
I fixed several spelling issues.Glad I could help .
Br, Guayaba221.

 docs: fix spelling issues

---

src/fund/types.ts

This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected `avaialable` to `available`
Please review the changes and let me know if any additional changes are needed.

fix: typos in documentation files

---

site/docs/pages/guides/lifecycle-status.mdx
site/docs/pages/guides/use-basename-in-onchain-app.mdx
site/docs/pages/installation/astro.mdx
src/core/OnchainKitConfig.ts

docs: fix typos

---

CHANGELOG.md
site/docs/pages/token/token-image.mdx

Changed "With" to "When" in the token props description:
- Old: `With 'token' props has no image`
- New: `When 'token' props has no image`
Updated Twitter links format and syntax:
- Old: `https://twitter.com/zizamia` and `https://twitter.com/onchainkit`
- New: `https://x.com/zizamia` and `https://x.com/onchainkit`

docs: improve grammar in TokenImage docs

---

vitest.config.ts

fix: alias

---

site/docs/pages/wallet/wallet.mdx

- Removed unnecessary <h3> heading in docs

chore: baby fix

---

CHANGELOG.md

fixed:
experinece - experience
updatd - updated 
correclty - correctly 
addeded - added 
enableded - enabled 
I hope my corrections will help you. Thank you for your work.

fix: fix typos and spelling errors

---

.storybook/main.ts

fix: storybook

---

package.json
playground/nextjs-app-router/components/Demo.tsx
playground/nextjs-app-router/components/DemoOptions.tsx
playground/nextjs-app-router/components/demo/Buy.tsx
playground/nextjs-app-router/components/form/active-component.tsx
playground/nextjs-app-router/lib/constants.ts
playground/nextjs-app-router/types/onchainkit.ts
src/buy/components/BuyTokenItem.tsx

chore: add `Buy` to playground

---

src/buy/components/BuyMessage.test.tsx
src/buy/components/BuyMessage.tsx

chore: update BuyMessage to show "user rejected" error

---

package.json
yarn.lock

fix: add support for React 19

---

src/buy/components/BuyAmountInput.tsx
src/buy/components/BuyDropdown.tsx
src/buy/components/BuyMessage.tsx
src/buy/components/BuyOnrampItem.tsx
src/buy/components/BuyProvider.tsx
src/buy/components/BuyTokenItem.tsx
src/buy/hooks/useOnrampEventListeners.test.ts
src/buy/hooks/useOnrampEventListeners.ts

- handle multiple onramp events
- fix theming 

chore: handle multiple onramp event emissions 

---

site/docs/components/landing/BuyDemo.tsx
site/docs/pages/buy/buy.mdx

chore: disable buy on docs

---

.changeset/happy-bobcats-drum.md
src/ui/react/nft/mint/NFTMintButton.tsx

No visual changes, updated NFTMintButton component to remove wrapper divs and pass through classNames to appropriate components

fix: mint button styling updates

---

CHANGELOG.md
site/package.json
site/yarn.lock

chore: docs

---

src/fund/hooks/useFundCardSetupOnrampEventListeners.test.tsx

Fund Card PR introduced a flaky test. This PR fixes it.

Fix flaky test

---

.gitignore

chore: remove vscode settings from gitignore

---

.vscode/settings.json

chore: remove settings

---

CHANGELOG.md
site/package.json
site/yarn.lock

chore: release v0.36.7 docs and changelog

---

src/core-react/OnchainKitProvider.tsx
src/core-react/internal/utils/findComponent.ts

Hi! This PR fixes typos in comments
- "overriden" to "overridden".
- "deafult" to "default".

fix: fix typos

---

playground/nextjs-app-router/components/demo/FundCard.tsx
playground/nextjs-app-router/onchainkit/package.json
src/fund/components/FundCardAmountInputTypeSwitch.test.tsx
src/fund/components/FundCardAmountInputTypeSwitch.tsx
src/fund/components/FundCardCurrencyLabel.tsx
src/fund/components/FundCardPaymentMethodDropdown.tsx
src/fund/components/FundCardPaymentMethodSelectRow.test.tsx
src/fund/components/FundCardPaymentMethodSelectRow.tsx
src/fund/components/FundCardPaymentMethodSelectorToggle.tsx

Bugbash fast follows: 
- Remove exchange rate line
- Update some colors 
- Updated font
- Removed shadow on payment method dropdown
|Light mode | Dark Mode |
|------------|------------|
|<img width="511" alt="Screenshot 2025-01-21 at 3 30 57 PM" src="https://github.com/user-attachments/assets/5e7ed29f-c15d-4da7-98c0-e3c04c05d61f" />|<img width="521" alt="Screenshot 2025-01-21 at 3 31 11 PM" src="https://github.com/user-attachments/assets/940bd42a-bacf-4160-a474-0cfbe9142790" />|
|Light mode | Dark Mode |
|------------|------------|
|<img width="513" alt="Screenshot 2025-01-21 at 3 31 02 PM" src="https://github.com/user-attachments/assets/4aa455e4-4d98-4d12-b26e-56acd0ed4423" />|<img width="533" alt="Screenshot 2025-01-21 at 3 31 19 PM" …

Bugbash fixes/updates

---

.changeset/perfect-knives-draw.md
src/version.ts

chore: release v0.36.8

---

.storybook/main.ts
packemon.config.ts
tsconfig.json
vitest.config.ts

chore: remove unused aliases

---

src/api/index.ts
src/nft/index.ts
src/nft/types.ts
src/transaction/types.ts

aliases aren't resolved in type declarations

fix: remove aliases from types

---

.changeset/friendly-cougars-fly.md
.changeset/many-glasses-visit.md
.changeset/smart-yaks-greet.md
src/version.ts

chore: release v0.36.9

---

site/docs/pages/wallet/wallet-island.mdx

* added an info callout regarding network support for token balances in WalletIsland

chore: document wallet island network support

---

site/docs/pages/api/get-portfolio-token-balances.mdx
site/docs/pages/api/get-portfolios.mdx
site/docs/pages/api/types.mdx

* added documentation for `getPortfolioTokenBalances`

chore: add docs for getPortfolioTokenBalances

---

src/nft/index.ts

export nft context to allow consumers to create their own replacements for the internal nft components

refactor: export nft context

---

src/nft/utils/buildMintTransactionData.test.ts

What changed? Why?
In buildMintTransactionData.test.ts, the word "Transation" was corrected to "Transaction" to fix a typographical error.
Notes to reviewers:
Please ensure that the corrected spelling aligns with the intended meaning and does not break any existing functionality.
How has it been tested?
The changes have been tested through the existing test cases for both files to ensure no functional changes were introduced.

fix: fix spelling errors in buildMintTransactionData.test.ts

---

playground/nextjs-app-router/onchainkit/package.json
src/wallet/components/WalletAdvanced.tsx
src/wallet/components/WalletAdvancedAddressDetails.test.tsx
src/wallet/components/WalletAdvancedAddressDetails.tsx
src/wallet/components/WalletAdvancedContent.test.tsx
src/wallet/components/WalletAdvancedContent.tsx
src/wallet/components/WalletAdvancedQrReceive.test.tsx
src/wallet/components/WalletAdvancedQrReceive.tsx
src/wallet/components/WalletAdvancedSwap.test.tsx
src/wallet/components/WalletAdvancedSwap.tsx
src/wallet/components/WalletAdvancedTokenHoldings.test.tsx
src/wallet/components/WalletAdvancedTokenHoldings.tsx
src/wallet/components/WalletAdvancedTransactionActions.test.tsx
src/wallet/components/WalletAdvancedTransactionActions.tsx
src/wallet/components/WalletAdvancedWalletActions.test.tsx
src/wallet/components/WalletAdvancedWalletActions.tsx
src/wallet/types.ts

* added classnames overrides throughout WalletAdvanced components
examples:
```
<WalletAdvanced classNames={{
container: '!bg-purple-500',
qr: {
container: 'bg-blue-500',
header: 'text-red-500',
copyButton: 'text-green-500',
},
swap: {
container: '!bg-yellow-500',
settings: 'rounded-full bg-purple-500',
settingsSlippageTitle: '!text-pink-500',
settingsSlippageDescription: '!text-orange-500',
settingsSlippageInput: '!text-red-500',
toAmountInput: '!text-red-500',
fromAmountInput: '!text-green-500',
toggleButton: '!bg-red-500',
swapButton: '!text-red-500',
message: '!text-red-500',
toast: '!text-red-500',
},
}}>
```
Top-Level:
QrReceive:
Swap:
```
<WalletAdvancedWalletActions
classNames={{
container: '!bg-red-500',
baseScanIcon: '!bg-blue-500',
qrIcon: …
```

feat: Add WalletAdvanced classnames overrides

---

site/docs/pages/fund/fetch-onramp-config.mdx
site/docs/pages/fund/fetch-onramp-options.mdx
site/docs/pages/fund/fetch-onramp-transaction-status.mdx
site/docs/pages/fund/get-onramp-buy-url.mdx
site/docs/pages/fund/setup-onramp-event-listeners.mdx
site/docs/pages/fund/types.mdx
site/sidebar.ts
src/fund/utils/fetchOnrampTransactionStatus.test.ts
src/fund/utils/fetchOnrampTransactionStatus.ts

- Added documentation for the onramp utils

chore: Documentation for the onramp utils

---

.changeset/chilled-donkeys-rest.md
.changeset/healthy-cups-admire.md
.changeset/plenty-bananas-invite.md
.changeset/tiny-geckos-visit.md
.changeset/tough-points-love.md
src/version.ts

- **feat**: Export NFT context. By @alessey #1917
- **feat**: WalletAdvanced mobile design. by @brendan-defi #1827
- **fix**: Await sequential transaction calls. by @dschlabach #1918
- **feat**: Add exchange rate refresh with throttling for FundCard. By @rustam-cb #1900
- **feat**: Dynamic text size in AmountInput component. by @rustam-cb #1909
- **feat**: Add style overrides to WalletAdvanced. by @brendan-defi #1912
- **feat**: Add DropdownMenu UI Primitive. By @cpcramer #1901
- **feat**: Implemented `DropdownMenu` primitive into `TokenSelectDropdown`. By @cpcramer #1903

chore: release v0.36.10

---

.changeset/cold-coins-call.md
site/docs/pages/guides/telemetry.mdx
site/sidebar.ts

Add Telemetry guide which includes:
- Why we are collecting telemetry
- What data will be collected 
- How we will be collecting the data
- How to opt-out and disable telemetry collection  

docs: Add Telemetry guide

---

.changeset/cold-coins-call.md
.changeset/dull-steaks-jog.md
.changeset/selfish-cougars-travel.md
src/version.ts

chore: release v0.36.11

---

src/token/components/TokenBalance.tsx

We have a possible circular dependency in `TokenBalance`. This fixes that import

fix: fix circular dependency in `TokenBalance`

---

src/appchain/bridge/abi.ts
src/appchain/bridge/hooks/useDeposit.test.ts
src/appchain/bridge/hooks/useDeposit.ts
src/appchain/bridge/hooks/useWithdraw.test.ts
src/appchain/bridge/hooks/useWithdraw.ts
src/appchain/bridge/types.ts

title
unit tests, and locally on playground

fix: support handling custom erc-20 gas tokens in deposit and withdraw hooks

---

playground/nextjs-app-router/app/mint/MintComponent.tsx

chore: update earnings token

---

src/appchain/bridge/constants.ts

deployed a new `DeployContract` instance

trivial: update testnet DeployContract address

---

.changeset/tall-moose-type.md
src/version.ts

chore: release 0.37.0

---

LICENSE.md

Updated the copyright year from 2023 to 2025 in the LICENSE file.

chore: update LICENSE

---

src/earn/components/Earn.test.tsx
src/earn/components/Earn.tsx
src/internal/components/tabs/Tabs.tsx

chore: add theme to earn

---

src/core/analytics/types.ts
src/fund/components/FundButton.test.tsx
src/fund/components/FundButton.tsx
src/fund/components/FundCardAmountInput.test.tsx
src/fund/components/FundCardAmountInput.tsx
src/fund/components/FundCardProvider.test.tsx
src/fund/components/FundCardProvider.tsx

fix: Fund component telemetry 

---

src/fund/components/FundCardAmountInput.test.tsx

fix: Hanging Fund unit tests

---

site/docs/components/landing/ComponentPreview.tsx
site/docs/components/landing/EarnDemo.tsx

Adding an `<Earn />` component demo to the homepage.

docs: add `<Earn />` demo to docs homepage

---

site/vercel.json
vercel/vercel.json

fix: fix other broken playground redirects

---

site/vercel.json
vercel/vercel.json

fix: restore playground rewrites

---

site/vercel.json
vercel/vercel.json

* add redirects for pay (checkout), buildSwapTransaction (api), getToken (api)
* redirect all frame/farcaster/xmtp content to homepage

fix: add / update redirects

---

src/core/analytics/types.ts
src/nft/components/NFTLifecycleProvider.test.tsx
src/nft/components/NFTLifecycleProvider.tsx
src/nft/components/mint/NFTMintButton.test.tsx
src/nft/components/mint/NFTMintButton.tsx
src/nft/components/mint/NFTQuantitySelector.test.tsx
src/nft/components/mint/NFTQuantitySelector.tsx

Reverts coinbase/onchainkit#1966
this is causing infinite state loops

Revert "feat: Add Mint Telemetry"

---

src/appchain/bridge/components/AppchainBridge.tsx
src/appchain/bridge/components/AppchainBridgeProvider.tsx
src/appchain/bridge/types.ts
src/appchain/index.ts

for developers to implement token price API. expose this prop on `AppchainBridge` for ease of use.
unit tests

feat: expose `handleFetchPrice` on top-level `AppchainBridge` component

---

.changeset/calm-items-double.md
src/appchain/bridge/components/AppchainBridge.test.tsx
src/appchain/bridge/components/AppchainBridge.tsx
src/appchain/bridge/components/AppchainBridgeProvider.test.tsx
src/appchain/bridge/components/AppchainBridgeProvider.tsx
src/appchain/bridge/components/AppchainBridgeSuccess.test.tsx
src/appchain/bridge/components/AppchainBridgeSuccess.tsx
src/appchain/bridge/components/AppchainBridgeWithdraw.test.tsx
src/appchain/bridge/components/AppchainBridgeWithdraw.tsx
src/appchain/bridge/hooks/useDepositButton.test.tsx
src/appchain/bridge/hooks/useDepositButton.tsx
src/appchain/bridge/hooks/useWithdraw.ts
src/appchain/bridge/types.ts

- add `AppchainBridgeSuccess`
- replace old success states with this component
unit tests, see video on slack

feat: `AppchainBridgeSuccess`

---

src/core/analytics/types.ts
src/transaction/components/TransactionProvider.test.tsx
src/transaction/components/TransactionProvider.tsx

feat: Add Transaction Telemetry 

---

src/core/analytics/constants.ts
src/core/analytics/types.ts
src/swap/components/SwapAmountInput.test.tsx
src/swap/components/SwapAmountInput.tsx
src/swap/components/SwapProvider.test.tsx
src/swap/components/SwapProvider.tsx
src/swap/components/SwapSettingsSlippageInput.test.tsx
src/swap/components/SwapSettingsSlippageInput.tsx

feat: Add Swap Telemetry

---

playground/nextjs-app-router/onchainkit/package.json
src/internal/components/tabs/Tab.tsx
src/internal/components/tabs/TabsList.test.tsx
src/internal/components/tabs/TabsList.tsx

Adding keyboard shortcuts to navigate between tabs as is recommended in [accessibility guidelines](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tab_role).

feat: improve accessibility in Tabs

---

src/appchain/bridge/components/AppchainBridge.tsx

remove problematic `relative flex` container
chrome devtools

fix: apply `w-full` on `AppchainBridge` default children

---

src/appchain/index.ts

feat: add additional `AppchainBridge` exports

---

README.md
site/docs/pages/guides/troubleshooting.mdx

chore: update Discord invite link

---

src/api/getPriceQuote.test.ts
src/api/getPriceQuote.ts
src/api/types.ts

* removed unnecessary nullish values from types
* added error to error.message

fix: getPriceQuote error message and types

---

src/checkout/components/CheckoutButton.test.tsx
src/checkout/components/CheckoutButton.tsx
src/checkout/components/CheckoutProvider.test.tsx
src/checkout/components/CheckoutProvider.tsx
src/core/analytics/types.ts

We were not emitting Checkout Success events as expected. This update fixes that by moving the analytics call to the CheckoutButton. 

fix: Checkout component success event

---

src/minikit/hooks/useAddFrame.test.tsx
src/minikit/hooks/useAddFrame.ts
src/minikit/hooks/useAuthenticate.test.tsx
src/minikit/hooks/useAuthenticate.ts
src/minikit/hooks/useClose.test.tsx
src/minikit/hooks/useClose.ts
src/minikit/hooks/useMiniKit.test.tsx
src/minikit/hooks/useMiniKit.ts
src/minikit/hooks/useNotification.test.tsx
src/minikit/hooks/useNotification.ts
src/minikit/hooks/useOpenUrl.test.tsx
src/minikit/hooks/useOpenUrl.ts
src/minikit/hooks/usePrimaryButton.test.tsx
src/minikit/hooks/usePrimaryButton.ts
src/minikit/hooks/useViewProfile.test.tsx
src/minikit/hooks/useViewProfile.ts
src/minikit/index.ts

Adding simple wrapper hooks over the frames sdk.  When possible, adding different behaviors when working in a non-frame environment.

feat: add minikit hooks

---

.changeset/purple-rivers-remember.md
CHANGELOG.md
package.json

Export MiniKit provider and hooks

feat: export minikit

---

create-onchain/package.json

chore: bump `create-onchain` version

---

.changeset/tall-shirts-live.md
src/appchain/bridge/hooks/useDeposit.ts
src/appchain/bridge/hooks/useWithdraw.ts
src/core/analytics/constants.ts
src/core/analytics/types.ts

- add analytics events for deposits + withdrawals
unit tests

feat: `AppchainBridge` deposit and withdrawal analytics

---

.github/actions/setup/action.yml

chore: update workflow

---

src/minikit/hooks/useAuthenticate.test.tsx
src/minikit/hooks/useAuthenticate.ts
src/minikit/index.ts

* Update useAuthenticate to include validation for nonce and fid
* Export parseSignInMessage

fix: useAuthenticate

---

eslint.config.mjs
packages/onchainkit/src/api/buildMintTransaction.ts
packages/onchainkit/src/api/buildPayTransaction.ts
packages/onchainkit/src/api/buildSwapTransaction.ts
packages/onchainkit/src/api/getMintDetails.ts
packages/onchainkit/src/api/getSwapQuote.ts
packages/onchainkit/src/api/getTokenDetails.ts
packages/onchainkit/src/identity/hooks/useAddress.test.tsx
packages/onchainkit/src/identity/hooks/useAttestations.test.ts
packages/onchainkit/src/identity/hooks/useAvatar.test.tsx
packages/onchainkit/src/identity/hooks/useAvatars.test.tsx
packages/onchainkit/src/identity/hooks/useName.test.tsx
packages/onchainkit/src/identity/hooks/useNames.test.tsx
packages/onchainkit/src/identity/hooks/useSocials.test.tsx
packages/onchainkit/src/identity/utils/getAvatar.ts
packages/onchainkit/src/identity/utils/getName.ts
packages/onchainkit/src/internal/components/QrCode/gradientConstants.test.ts
packages/onchainkit/src/internal/hooks/useLifecycleStatus.ts
packages/onchainkit/src/token/components/TokenSearch.stories.tsx

Enabling the eslint rule `no-unused-vars` and fixing or ignoring the flagged errors.
Unit tests.

chore: Enable eslint no-unused-vars

---

packages/onchainkit/src/wallet/components/ConnectWallet.tsx

Added all dependencies to a useCallback that was causing lint issues
Manually

fix: Add all dependencies to useCallback

---

packages/playground/components/Demo.tsx

Hi! I fixed navigation to actual `playground` source code location

fix: update dead link in `Demo.tsx`

---

.github/workflows/miniapp-manifest-build.yml
.github/workflows/miniapp-manifest-lint.yml
.github/workflows/miniapp-manifest-test.yml
packages/miniapp-manifest-generator/.gitignore
packages/miniapp-manifest-generator/package.json
packages/miniapp-manifest-generator/src/components/Page.test.tsx
packages/miniapp-manifest-generator/src/components/Page.tsx
packages/miniapp-manifest-generator/src/components/Step.test.tsx
packages/miniapp-manifest-generator/src/components/Step.tsx
packages/miniapp-manifest-generator/src/components/Success.test.tsx
packages/miniapp-manifest-generator/src/components/Success.tsx
packages/miniapp-manifest-generator/src/components/Timer.test.tsx
packages/miniapp-manifest-generator/src/components/Timer.tsx
packages/miniapp-manifest-generator/src/components/steps/Connect.test.tsx
packages/miniapp-manifest-generator/src/components/steps/Connect.tsx
packages/miniapp-manifest-generator/src/components/steps/Domain.test.tsx
packages/miniapp-manifest-generator/src/components/steps/Domain.tsx
packages/miniapp-manifest-generator/src/components/steps/Sign.test.tsx
packages/miniapp-manifest-generator/src/components/steps/Sign.tsx
packages/miniapp-manifest-generator/src/hooks/useFid.test.tsx
packages/miniapp-manifest-generator/src/hooks/useFid.ts
packages/miniapp-manifest-generator/src/hooks/useSignManifest.test.tsx
packages/miniapp-manifest-generator/src/hooks/useSignManifest.ts
packages/miniapp-manifest-generator/src/utilities/toBase64.test.ts
packages/miniapp-manifest-generator/src/utilities/toBase64.ts
packages/miniapp-manifest-generator/src/utilities/validateUrl.test.ts
packages/miniapp-manifest-generator/src/utilities/validateUrl.ts
packages/miniapp-manifest-generator/vitest.config.ts
packages/miniapp-manifest-generator/vitest.setup.ts
pnpm-lock.yaml

* Refactored miniapp-manifest-generator
* Added tests
* Added workflows

refactor: add tests to manifest

---

packages/create-onchain/package.json
packages/miniapp-manifest-generator/package.json
packages/miniapp-manifest-generator/scripts/copyBuild.js
packages/miniapp-manifest-generator/scripts/copyBuild.test.ts

Updating to a more decoupled copy script

refactor: update manifest build copy

---

packages/create-onchain/package.json
packages/create-onchain/src/cli.ts

Add --template=minikit/onchainkit options to the CLI to support more future templates

fix: add --template cli option

---

README.md
packages/miniapp-manifest-generator/README.md
packages/onchainkit/README.md

fix: update manifest readme

---

packages/create-onchain/templates/minikit-basic/README.md
packages/create-onchain/templates/minikit-basic/app/page.tsx
packages/create-onchain/templates/minikit-snake/README.md
packages/create-onchain/templates/minikit-snake/app/page.tsx

* small template style fixes to prevent layout shift when connecting wallets
* update readme onchainkit links to docs

fix: small template tweaks

---

packages/create-onchain/README.md

feat: add cli readme

---

packages/create-onchain/templates/minikit-snake/app/components/snake.tsx
packages/create-onchain/templates/minikit-snake/app/page.tsx

* Add wallet component to page.tsx so when user deletes the snake game they still have scaffolding with a connect and add frame button.
* Updated deprecated ConnectWalletText
| ----- | ------ |
| ![image](https://github.com/user-attachments/assets/64ddbcbd-16b3-42ec-8917-223f435c2335) | ![image](https://github.com/user-attachments/assets/8185741d-ab6d-49ad-952c-f25eabed50b0) |
| ![image](https://github.com/user-attachments/assets/bff849db-588b-41d8-9aab-59410438b24d) | ![image](https://github.com/user-attachments/assets/eeeb7ddd-9642-4da5-8228-461f59b76249) |

fix: add wallet to page

---

packages/create-onchain/src/analytics.test.ts
packages/create-onchain/src/analytics.ts
packages/create-onchain/src/cli.test.ts
packages/create-onchain/src/cli.ts
packages/create-onchain/src/minikit.test.ts
packages/create-onchain/src/minikit.ts
packages/create-onchain/src/onchainkit.test.ts
packages/create-onchain/src/onchainkit.ts
packages/create-onchain/src/utils.test.ts
packages/create-onchain/src/utils.ts

feat: add cli analytics

---

packages/create-onchain/templates/minikit-snake/app/page.tsx

fix: lint in snake

---

.github/workflows/cli-basic.yml
.github/workflows/cli-snake.yml

* Add build CI tasks for the minikit templates
* Update the current CI build task to opt out of analytics

fix: add ci builds for each template

---

.github/workflows/cli-snake.yml

fix: snake ci task

---

packages/onchainkit/src/appchain/bridge/hooks/useWithdrawButton.test.tsx
packages/onchainkit/src/appchain/bridge/hooks/useWithdrawButton.tsx

- fix regression in withdrawal UI
locally in playground

fix: withdraw UI

---

.changeset/quick-papayas-remain.md
packages/onchainkit/src/version.ts

Bump patch version for release

---

.changeset/hungry-poets-clap.md
packages/onchainkit/src/nft/components/view/NFTAudio.tsx
packages/onchainkit/src/nft/components/view/NFTImage.tsx
packages/onchainkit/src/nft/components/view/NFTMedia.tsx
packages/onchainkit/src/nft/components/view/NFTVideo.test.tsx
packages/onchainkit/src/nft/components/view/NFTVideo.tsx

* fixed square aspect ratio which was not working on some videos
* fixed the non-square aspect ratio on images
* fixed the audio play button default style
* prevented clicks from propagating on nft videos in case they do not auto load on slow connections and users need to press play
| ----- | ----- |
| ![image](https://github.com/user-attachments/assets/f9b64071-dcf9-4750-8272-de0cd400f841) | ![image](https://github.com/user-attachments/assets/351264cc-1327-434b-9006-14b653f5cfd0) |

fix: nft fixes

---

packages/onchainkit/src/buy/index.ts
packages/onchainkit/src/checkout/index.ts
packages/onchainkit/src/earn/index.ts
packages/onchainkit/src/nft/index.ts
packages/onchainkit/src/swap/index.ts
packages/onchainkit/src/transaction/index.ts
packages/onchainkit/src/wallet/index.ts

chore: add context exports

---

packages/onchainkit/src/earn/index.ts
packages/onchainkit/src/wallet/index.ts

- prevent breaking change
- remove when we remove deprecated items to consolidate breaking changes

chore: add provider exports back

---

packages/onchainkit/package.json
packages/onchainkit/vite.config.ts

Skips cleaning out dir in dev mode
Manually

fix: Don't clean out out dir when building in dev mode

---

packages/onchainkit/src/wallet/components/WalletModal.tsx

fix wallet modal

---

packages/create-onchain/templates/minikit-basic/package.json
packages/create-onchain/templates/minikit-snake/package.json
packages/create-onchain/templates/next/package.json

chore: bump cli templates deps

---

packages/onchainkit/src/minikit/hooks/useMiniKit.test.tsx
packages/onchainkit/src/minikit/hooks/useMiniKit.ts

fix: ready options

---

packages/onchainkit/src/minikit/hooks/useAuthenticate.test.tsx
packages/onchainkit/src/minikit/hooks/useAuthenticate.ts

fix: authenticate against user fid

---

packages/create-onchain/package.json

chore: update `create-onchain` version

---

.changeset/config.json
.github/workflows/release.yml

chore: update release workflows

---

.changeset/metal-trains-stand.md
.github/workflows/release.yml
package.json

fix: fix build command in workflow

---

.changeset/little-meals-lay.md
.changeset/plain-planes-tickle.md
.changeset/pretty-clowns-pay.md
.changeset/rude-friends-bathe.md

- Adds changesets to kick off release

chore: Release changesets

---

packages/onchainkit/.vscode/extensions.json
packages/onchainkit/.vscode/settings.json

Added some default settings/recommended extensions for vscode/cursor contributors
- Tested on fresh workflow for ock

Chore: workflow improvement for vscode/cursor users

---

.changeset/chatty-pants-trade.md
packages/onchainkit/src/DefaultOnchainKitProviders.tsx
packages/onchainkit/src/minikit/MiniKitProvider.tsx

- Fixes MiniKit frames connector
- Manually

fix: MiniKit frames connector

---

.github/workflows/release.yml

- Updates changesets to sign commits

chore: Use signed commits for Changesets action

---

packages/miniapp-manifest-generator/src/components/steps/Sign.test.tsx
packages/miniapp-manifest-generator/src/components/steps/Sign.tsx

fix; typo in function

---

packages/onchainkit/package.json
packages/onchainkit/src/earn/components/VaultDetails.tsx
packages/onchainkit/src/earn/components/YieldDetails.tsx
packages/onchainkit/src/internal/components/Popover.test.tsx
packages/onchainkit/src/internal/components/Popover.tsx
packages/onchainkit/src/swap/components/SwapSettings.test.tsx
packages/onchainkit/src/swap/components/SwapSettings.tsx
pnpm-lock.yaml

Use `radix-ui` for Popover, maintain similar API as before
tested components that use it + vitests

[feat] Update popover

---

packages/onchainkit/src/nft/components/NFTCard.tsx
packages/onchainkit/src/nft/components/NFTLifecycleProvider.tsx
packages/onchainkit/src/nft/components/NFTMintCard.tsx
packages/onchainkit/src/nft/components/NFTProvider.tsx
packages/onchainkit/src/nft/components/mint/NFTAssetCost.tsx
packages/onchainkit/src/nft/components/mint/NFTCollectionTitle.tsx
packages/onchainkit/src/nft/components/mint/NFTCreator.tsx
packages/onchainkit/src/nft/components/mint/NFTMintButton.tsx
packages/onchainkit/src/nft/components/mint/NFTMinters.tsx
packages/onchainkit/src/nft/components/mint/NFTQuantitySelector.tsx
packages/onchainkit/src/nft/components/mint/NFTTotalCost.tsx
packages/onchainkit/src/nft/components/view/NFTAudio.tsx
packages/onchainkit/src/nft/components/view/NFTImage.tsx
packages/onchainkit/src/nft/components/view/NFTLastSoldPrice.tsx
packages/onchainkit/src/nft/components/view/NFTMedia.tsx
packages/onchainkit/src/nft/components/view/NFTMintDate.tsx
packages/onchainkit/src/nft/components/view/NFTNetwork.tsx
packages/onchainkit/src/nft/components/view/NFTOwner.tsx
packages/onchainkit/src/nft/components/view/NFTTitle.tsx
packages/onchainkit/src/nft/components/view/NFTVideo.tsx
packages/onchainkit/src/nft/index.ts
packages/onchainkit/src/nft/types.ts

chore: rename nft types

---

packages/onchainkit/src/checkout/components/Checkout.tsx
packages/onchainkit/src/checkout/components/CheckoutButton.tsx
packages/onchainkit/src/checkout/components/CheckoutProvider.tsx
packages/onchainkit/src/checkout/components/CheckoutStatus.tsx
packages/onchainkit/src/checkout/index.ts
packages/onchainkit/src/checkout/types.ts

chore: rename checkout types 

---

.changeset/tall-planets-ring.md

- Adds changeset to kick off create-onchain release

chore: create-onchain changeset

---

.changeset/wild-turtles-admire.md

- Adds changeset for useIsInMiniApp change

chore: Adds changeset for useIsInMiniApp change

---

.pnpmrc
examples/minikit-example/package.json
package.json
packages/create-onchain/templates/minikit-basic/package.json
packages/create-onchain/templates/minikit-snake/package.json
packages/create-onchain/templates/next/package.json
packages/miniapp-manifest-generator/package.json
packages/onchainkit/package.json
packages/onchainkit/src/DefaultOnchainKitProviders.test.tsx
packages/onchainkit/src/DefaultOnchainKitProviders.tsx
packages/onchainkit/src/checkout/components/CheckoutProvider.tsx
packages/onchainkit/src/internal/svg/baseAccountSvg.tsx
packages/onchainkit/src/wallet/components/WalletModal.test.tsx
packages/onchainkit/src/wallet/components/WalletModal.tsx
packages/playground/package.json
pnpm-lock.yaml

- Adds Base Account to list of connectors

feat: Add Base Account connector support

---

packages/miniapp-manifest-generator/src/utilities/validateUrl.ts

Updated validate file for manifest to increase char limit from 6 to 12

extended validation to max 8 chars

---

.changeset/tall-socks-read.md

- Adds changeset for manifest validator fix

chore: Manifest validator changeset

---

.changeset/better-friends-hug.md
.changeset/moody-taxes-play.md
examples/minikit-example/app/actions/SwapToken.tsx
examples/minikit-example/app/page.tsx
examples/minikit-example/package.json
packages/create-onchain/templates/minikit-basic/package.json
packages/create-onchain/templates/minikit-snake/package.json
packages/onchainkit/package.json
packages/onchainkit/src/minikit/MiniKitProvider.test.tsx
packages/onchainkit/src/minikit/MiniKitProvider.tsx
packages/onchainkit/src/minikit/components/AutoConnect.test.tsx
packages/onchainkit/src/minikit/hooks/useMiniKit.test.tsx
packages/onchainkit/src/minikit/hooks/useSwapToken.test.tsx
packages/onchainkit/src/minikit/hooks/useSwapToken.ts
packages/onchainkit/src/minikit/index.ts
packages/playground/package.json
pnpm-lock.yaml

- Added `useSwapToken` minikit util
- Unit tests

feat: Add useSwapToken util

---

.gitignore
CLAUDE.md
examples/minikit-example/app/actions/BatchedTransaction.tsx
examples/minikit-example/app/page.tsx

- Added example of batched transactions to MiniKit example app to help debug

feat: Add batched transaction example to MiniKit Example App

---

packages/create-onchain/scripts/copy-templates.js

Fixes issue where .gitignore wasn't included in a new project

fix: Include .gitignore in alpha projects

---

packages/onchainkit/docs/components/appchain/bridge.mdx
packages/onchainkit/docs/components/checkout/checkout.mdx
packages/onchainkit/docs/components/earn/earn.mdx
packages/onchainkit/docs/components/fund/fund-button.mdx
packages/onchainkit/docs/components/identity/badge.mdx
packages/onchainkit/docs/components/identity/identity-card.mdx
packages/onchainkit/docs/components/mint/nft-card.mdx
packages/onchainkit/docs/components/mint/nft-mint-card.mdx
packages/onchainkit/docs/components/signature/signature.mdx
packages/onchainkit/docs/components/token/token-chip.mdx
packages/onchainkit/docs/components/token/token-image.mdx
packages/onchainkit/docs/components/token/token-row.mdx
packages/onchainkit/docs/components/token/token-search.mdx
packages/onchainkit/docs/components/transaction/transaction.mdx
packages/onchainkit/docs/components/wallet/wallet-dropdown-link.mdx
packages/onchainkit/docs/components/wallet/wallet.mdx
packages/onchainkit/docs/configuration/themes.mdx
packages/onchainkit/docs/getting-started/manual-installation.mdx
packages/onchainkit/docs/utilities/identity/get-attestations.mdx
packages/onchainkit/docs/utilities/wallet/is-wallet-a-coinbase-smart-wallet.mdx

chore: Remove @noErrors directrive from docs

---

.changeset/config.json

- Fix onchainkit and create-onchain versions together

fix: Fix onchainkit and create-onchain versions

---

.changeset/plenty-wombats-drum.md

- Changeset for create-onchain release

chore: Add changeset to create-onchain

---

packages/onchainkit/src/buy/components/Buy.test.tsx
packages/onchainkit/src/buy/components/Buy.tsx
packages/onchainkit/src/buy/components/BuyDropdown.test.tsx
packages/onchainkit/src/buy/components/BuyDropdown.tsx
packages/onchainkit/src/buy/components/BuyProvider.tsx
packages/onchainkit/src/buy/types.ts
packages/onchainkit/src/buy/utils/getBuyFundingUrl.test.ts
packages/onchainkit/src/buy/utils/getBuyFundingUrl.ts
packages/onchainkit/src/fund/components/FundButton.test.tsx
packages/onchainkit/src/fund/components/FundButton.tsx
packages/onchainkit/src/fund/components/FundCard.test.tsx
packages/onchainkit/src/fund/components/FundCard.tsx
packages/onchainkit/src/fund/components/FundCardProvider.tsx
packages/onchainkit/src/fund/components/FundCardSubmitButton.test.tsx
packages/onchainkit/src/fund/components/FundCardSubmitButton.tsx
packages/onchainkit/src/fund/hooks/useFundCardFundingUrl.test.ts
packages/onchainkit/src/fund/hooks/useFundCardFundingUrl.ts
packages/onchainkit/src/fund/hooks/useGetFundingUrl.test.ts
packages/onchainkit/src/fund/hooks/useGetFundingUrl.ts
packages/onchainkit/src/fund/types.ts
packages/onchainkit/src/fund/utils/getOnrampBuyUrl.test.ts
packages/onchainkit/src/fund/utils/getOnrampBuyUrl.ts
packages/playground/components/demo/FundCard.tsx

- Added sessionToken parameter to FundCard
- Removed unneeded params from the FundCard
Unit tests

chore(ONRAMP-843): FundCard accept sessionToken param

---

.changeset/stale-teeth-fly.md
packages/onchainkit/src/fund/index.ts

- Fixes missing types for GetOnrampUrl methods

fix: Update GetOnrampUrl type
