README.md

docs: document `getFrameAccountAddress`

---

README.md

adds a link to neynar.com where devs can sign up to get the API key
NA
NA

docs: add link to get API key

---

src/core/getFrameAccountAddress.ts
src/core/parseFrameMessage.ts
src/index.ts

While working with frames, it's beneficial to be able to get the whole validated message. Since we parse and validate the message as part of `getFrameAccountAddress`, I pulled the relevant code out into a new function.
yolo'd this, would love to hear any strategies for testing
edit: did manually test in a frame by copying code over and it appears to work

feat: factor out parseFrameMessage

---

package.json
src/core/farcaster.integ.ts
src/core/farcasterTypes.ts
src/core/getFrameAccountAddress.test.ts
src/core/getFrameAccountAddress.ts
src/core/getFrameMessage.ts
src/core/getFrameValidatedMessage.test.ts
src/core/getFrameValidatedMessage.ts
src/index.ts
src/utils/neynar/neynar.integ.ts

1. Be more explicit on our Farcaster request / response types.
2.  Decided against importing the Farcaster types from @farcaster/hub-nodejs as the object types were more complex and could confuse consumers.  Extract + simplify the interface.
1.   Added a farcaster message verification integration test.
```
yarn test
PASS  src/utils/neynar/user/neynarUserFunctions.test.ts
PASS  src/core/getFrameValidatedMessage.test.ts
PASS  src/core/getFrameMetadata.test.ts
PASS  src/core/getFrameAccountAddress.test.ts
Test Suites: 4 passed, 4 total
Tests:       8 passed, 8 total
Snapshots:   0 total
Time:        1.876 s, estimated 2 s
Ran all test suites.
```
```
❯ yarn test:integration         
PASS …
```

fix: Refactor Farcaster typing to be explicit

---

src/core/getFrameAccountAddress.test.ts
src/core/getFrameAccountAddress.ts
src/core/mock.ts

Have `getFrameAccountAddress` reading from the `message` instead of the `body`.
The idea is that the `body` should be read only from `getFrameMessage`, and then the `message` is re-used in different places.

fix: have `getFrameAccountAddress` reading from the `message`

---

src/core/farcasterTypes.ts
src/core/getFrameHtmlResponse.test.ts
src/core/getFrameHtmlResponse.ts
src/core/getFrameMetadata.test.ts
src/core/getFrameMetadata.ts

Add support for Text Input metadata for Farcaster Frames
**Screenshots**
Preemptively derived from spec defined in the [public proposal](https://warpcast.notion.site/Frames-Text-Input-Public-27c9f0d61903486d89b6d932dd0d6a22).
Manually

Add Text Input metadata support

---

.changeset/mighty-tomatoes-decide.md
README.md
src/components/FrameMetadata.tsx
src/core/getFrameHtmlResponse.ts
src/core/getFrameMetadata.ts
src/core/types.ts
src/index.ts
src/version.ts

feat: exported `FrameMetadataType`

---

.changeset/itchy-glasses-add.md
README.md
src/components/Name.test.tsx
src/components/Name.tsx
src/hooks/useName.test.ts
src/hooks/useName.ts
src/index.ts

Rename from `OnchainName` to `Name` to make cleaner usage of component in consumer's project.

fix: rename onchainname component to name

---

src/components/FrameMetadata.test.tsx
src/components/FrameMetadata.tsx
src/core/getFrameMetadata.ts
src/core/types.ts

Adds optional `wrapperComponent` prop to `FrameMetadata` component that defaults to `React.Fragment` when not passed (original behavior).  Also exported `FrameMetadataResponse` which can be useful when using `getFrameMetadata` in a TS project.
Example use-case for project using `react-helmet-async` (which expects only valid head tags to be rendered directly inside `Helmet`):
```js
import { FrameMetadata } from '@coinbase/onchainkit';
import { Helmet } from 'react-helmet-async';
const PageComponent = () => (
<FrameMetadata
image="https://zizzamia.xyz/park-1.png"
buttons={[{ label: 'Click Me', action: 'post_redirect' }]}
wrapperComponent={Helmet}
/>
);
```

feat: Add wrapper component to FrameMetadata

---

CHANGELOG.md
README.md

docs: polish

---

README.md
docs/frame-kit.md
src/components/FrameMetadata.test.tsx
src/components/FrameMetadata.tsx
src/core/getFrameHtmlResponse.test.ts
src/core/getFrameHtmlResponse.ts
src/core/getFrameMetadata.test.ts
src/core/getFrameMetadata.ts
src/core/types.ts

Add support for optional metadata tag `fc:frame:image:aspect_ratio`
See: https://docs.farcaster.xyz/reference/frames/spec
**Screenshot**
Aspect Ratio: "1:1"
Backwards compatible. Image metadata can be defined as a string (defaults to aspectRatio of `1.91:1`) or an object with a `src` URL string and `aspectRatio` of `1.91:1` or `1:1`.
Manually

Add support for image aspect ratio metadata

---

README.md

Minor type-o in readme for 1:1 aspect ratio
⏹
Manually

Fixes 1.1 => 1:1 aspect ratio examples in readme

---

package.json
src/core/getEASAttestations.test.ts
src/core/getEASAttestations.ts
src/core/types.ts
src/definitions/base.ts
src/definitions/baseSepolia.ts
src/definitions/optimism.ts
src/index.ts
src/network/easGraphQL.ts
src/queries/easAttestations.test.ts
src/queries/easAttestations.ts
src/utils/easAttestation.ts
yarn.lock

The new `getEASAttestations` function fetches Ethereum Attestation Service (EAS) attestations for a given address and chain. Optionally filtered by schemas associated with the attestation.
Example:
```javascript
import { getEASAttestations } from '@coinbase/onchainkit'
import { base } from "viem/chains";
const attestations = await getEASAttestations("0x1234567890abcdef1234567890abcdef12345678", base)
// returns [
//   {
//       "attester": "0x357458739F90461b99789350868CD7CF330Dd7EE",
//       "expirationTime": 0,
//       "id": "0x93016a60f13e7cfe0257116aedfce7088c2c0020787a325ea9f6b4ba11d07598",
//       "recipient": "0x44a7D120beA87455071cebB841eF91E6Ae21bC1a",
//       "revocationTime": 0,
//       "schemaId": "0x1801901fabd0e6189356b4fb52bb0ab855276d84f7ec140839fbd1f6801ca065",
// …
```

feat: new function `getEASAttestations` to fetch attestation from Ethereum Attestation Service (EAS) - part 2

---

.github/workflows/test.yml

Didn't realize global tests would run on this directory, adding installing `framegear` deps to the workflow

fix: install framegear deps during CI

---

framegear/app/page.tsx
framegear/components/Frame/Frame.tsx
framegear/components/FrameInput/FrameInput.tsx
framegear/components/Header/Header.tsx
framegear/components/ValidationResults/ValidationResults.tsx
framegear/tailwind.config.ts
framegear/utils/constants.ts

- removed `pages` definition from tailwind config; we don't use pages in this project
- removed magic strings and string constants in CSS, replacing with tailwind theme extensions. No need for `clsx` at this time because we don't have any conditional styles.
- did _not_ remove `framegear/.gitignore` because the root-level `.gitignore` doesn't cover all of what it does and rather than updating at the root level I think it makes sense to keep any config specific to this module local.
No functional/visual changes, just cleanup

fix: css followups

---

.changeset/chatty-bananas-breathe.md
src/version.ts

chore: version docs

---

framegear/components/Frame/Frame.tsx
framegear/components/Header/Header.tsx
framegear/package.json
framegear/tailwind.config.ts
framegear/yarn.lock

- forgot to implement `input` before, now it's there
- added Radix Icons as used in onchainkit, and replacing a literal SVG with the icon react component
- this will be helpful when we start dealing with frame actions, as different types of buttons should have different icons associated

chore: smol tweaks to framegear

---

.changeset/cuddly-frogs-flow.md
src/core/getFrameMessage.test.ts
src/core/getFrameMessage.ts
src/core/getMockFrameRequest.ts
src/core/types.ts
src/index.ts

Taken from #148, this PR introduces the concept of mock frame messages, which facilitates testing locally running frames in future releases of `framegear`. This is MVP-quality, keeping track of enhancements for fast followup in #146.
This PR has to be merged and released before we can add the second part.
Unit tests, manual end-to-end testing with locally-installed package and modified `framegear`.

feat: `getFrameMessage` can now handle mock frame messages.

---

site/docs/pages/xmtpkit/introduction.mdx

Added a longer introduction to XMTP in the XMTPKit docs.
Just docs

Docs update for XMTP Frames

---

site/docs/pages/xmtpkit/introduction.mdx

I'm a `vocs` n00b and accidentally put some text inside the code group. 🤦 . This should make the text visible to users.

Move text out of code-group

---

CHANGELOG.md
README.md
site/docs/pages/index.mdx
site/vocs.config.tsx

feat: colors

---

framegear/components/Frame/Frame.tsx
framegear/components/ValidationResults/ValidationResults.tsx
framegear/utils/validation.ts

Part of #146. Changes in this PR:
- always show required tags, even when not present
- show error message when relevant in verification
- add placeholder message when no frame has been loaded
- update schema for more consistent error messages (wording around "required" vs "defined")
Small improvements while I was in there:
- we didn't gracefully handle wrong aspect-ratio image, now using `object-cover` to clip the edges to fit. This is consistent with Warpcast behavior.
- Handled long frame button text with ellipsis
| no results | invalid results | valid results |
| ----- | ----- | ----- | 
| <img width="1584" alt="image" src="https://github.com/coinbase/onchainkit/assets/9300702/00e048ee-c0bb-4833-b233-14fdc758ec0e"> | <img width="1584" alt="image" …

feat: always show required tag status

---

src/queries/easAttestations.ts

Fix for `Error in getEASAttestation: Unknown type "EASAttestationWhereInput"`
The gql types are [AttestationWhereInput](https://studio.apollographql.com/sandbox/schema/reference/inputs/AttestationWhereInput) and [AttestationScalarFieldEnum](https://studio.apollographql.com/sandbox/schema/reference/enums/AttestationScalarFieldEnum?query=returnType%3AAttestationScalarFieldEnum) without the `EAS` prefix.

Fix EAS graphql types

---

site/docs/pages/frame/get-frame-message.mdx
site/docs/pages/frame/types.mdx

docs: polish getFrameMessage types

---

framegear/app/api/postFrame/route.ts

- added `'Content-Type': 'application/json'` to post frame request headers.
- sending this request without the content-type  can cause server parsing issues. happened for me with express `4.17.21`
- tested locally using express server. don't think this should cause issues with other servers, but you might want to do further testing.

add content type to framegear post frame request

---

framegear/components/Frame/Frame.tsx
framegear/package.json
framegear/yarn.lock

Pinning onchainkit within `framegear`, I think having the caret is what made it so that different people saw different results (e.g., regarding `viem` import) (even though the caret shouldn't have any impact pre-1.0 for non-patch versions 🤷‍♂️)
Additionally, #185 pointed out that that was a bug in the aspect ratio classnames. I always forget this, but tailwind needs to see the full dynamic classnamein order to generate it, so `aspect-[1/1]` wasn't doing anything because that literal string never showed up. 

chore: pin onchainkit, update aspect ratio classname

---

framegear/components/Header/Header.tsx

per feedback from @huntertdiamond, the header now takes up less space. In particular, removed the banner because the information it provides other than the link to the spec is not very useful.

fix: economize vertical space in framegear header

---

framegear/app/api/postFrame/route.ts
framegear/app/page.tsx
framegear/components/Frame/Frame.tsx
framegear/components/RedirectModal/RedirectModal.tsx
framegear/components/RedirectModal/index.ts
framegear/components/RedirectModalContext/RedirectModalContext.tsx
framegear/utils/postFrame.ts

- Add support for `post_redirect`, `link` actions.
- Add external link icon for `post_redirect`, `link` buttons.
**Screenshot**
N/A
Manually

[Framegear] Add support for `post_redirect`, `link` + icons

---

framegear/components/Frame/Frame.tsx

Part of #146 
Passing input text value in the frame action.
Also cleaned up some lint/type errors while I was in there.

feat: pass input text through post action

---

framegear/components/RedirectModal/RedirectModal.tsx

Modal text defaulted to white, was unreadable

fix: link modal text color

---

.changeset/honest-hounds-tie.md
site/docs/pages/frame/types.mdx
src/frame/getFrameHtmlResponse.test.ts
src/frame/getFrameMetadata.test.ts
src/frame/types.ts
src/version.ts

Added `tx` as a Frame action option, enabling support for Frame Transactions. 
Spec: https://warpcast.notion.site/Frame-Transactions-Public-Draft-v2-9d9f9f4f527249519a41bd8d16165f73

feat: add `tx` as a Frame action option

---

.changeset/spotty-melons-bathe.md
site/docs/pages/frame/introduction.mdx
site/docs/pages/frame/types.mdx
site/docs/pages/getting-started.mdx
site/docs/pages/identity/introduction.mdx
site/docs/pages/index.mdx
src/frame/index.ts
src/frame/types.ts
src/version.ts

Cooking some initial types for Frame transactions.
We are following the latest spec https://warpcast.notion.site/Frame-Transactions-Public-Draft-v2-9d9f9f4f527249519a41bd8d16165f73
We aim to enhance those types further as we gain insights from the latest spec version.

feat: added initial version of Frame Transaction types

---

src/utils/neynar/frame/types.ts

updated NeynarFrameValidationInternalModel type, for type safe handling of state and input in a validated message

fix: update neynar frame validation type

---

.changeset/gold-impalas-retire.md
site/docs/pages/identity/introduction.mdx
site/docs/pages/identity/use-avatar.mdx
site/docs/pages/identity/use-name.mdx
site/sidebar.ts
src/version.ts

fix: format

---

framegear/components/ValidationResults/ValidationResults.tsx

Added `break-all` to frame `ValidationEntry` value container to allow longer values to freely wrap without breaking the layout.
Before
After
Visually.

word-break break-all for validator entry values

---

framegear/components/Frame/Frame.tsx
framegear/utils/store.ts

Added:
- an atom to track mock frame options
- a checkbox to toggle the `following` option
- passed this value through in `postFrame`
Will add others as the need becomes apparent.

feat: framegear supports mock following option

---

.changeset/nine-wasps-work.md
framegear/utils/frameResultToFrameMetadata.ts
framegear/utils/postFrame.ts
framegear/utils/store.ts
jest.config.js
src/frame/components/FrameMetadata.test.tsx
src/frame/components/FrameMetadata.tsx
src/frame/getFrameMetadata.test.ts
src/frame/getFrameMetadata.ts
src/frame/index.ts
src/frame/types.ts
src/version.ts

feat: added `post_url` optional metadata for `tx` Frame

---

framegear/package.json
framegear/yarn.lock

Updating to latest patch version of `onchainkit`

chore: `framegear` uses latest `onchainkit`

---

.changeset/thin-jokes-build.md
CHANGELOG.md
site/docs/pages/identity/get-avatar.mdx
site/docs/pages/identity/get-name.mdx
site/docs/pages/identity/types.mdx
site/docs/pages/identity/use-avatar.mdx
site/docs/pages/identity/use-name.mdx
site/sidebar.ts
src/identity/core/getAvatar.test.tsx
src/identity/core/getAvatar.ts
src/identity/core/getName.test.tsx
src/identity/core/getName.ts
src/identity/hooks/useAvatar.test.tsx
src/identity/hooks/useAvatar.ts
src/identity/hooks/useName.test.tsx
src/identity/hooks/useName.ts
src/identity/index.ts
src/identity/types.ts
src/version.ts

Exposing the `getAvatar` and `getName` utility to help retrieve Name and Avatar identity information in cases where you use it with Next.js or any Node.js backend.

feat: expose getName and getAvatar identity logic. #265

---

site/docs/pages/index.mdx

feat: add video section to landing page

---

.changeset/sixty-snails-act.md
CHANGELOG.md
src/index.ts
src/version.ts

Deprecated root level imports for `getFrameMetadata`, `FrameMetadata`, `Avatar`, `Name`, `useAvatar`, `useName` utilities and components.

chore: deprecated a few utilities from root level imports

---

.changeset/lovely-peaches-relax.md
CHANGELOG.md
site/docs/pages/identity/avatar.mdx
site/docs/pages/identity/badge.mdx
site/package.json
site/vocs.config.tsx
site/yarn.lock
src/identity/components/Avatar.tsx

feat: added missing radius on Avatar component

---

.changeset/old-carrots-design.md
site/docs/pages/token/format-amount.mdx
site/docs/pages/token/types.mdx
site/sidebar.ts
src/token/core/formatAmount.test.ts
src/token/core/formatAmount.ts
src/token/index.ts
src/token/types.ts

- Adding a utility function to format numbers
- Should info like `locale` be stored in the OnchainKitProvider?
locally

feat: formatAmount utility function

---

.changeset/stale-masks-suffer.md
package.json
site/docs/pages/token/token-row.mdx
site/docs/pages/token/types.mdx
site/docs/styles.css
site/sidebar.ts
src/token/components/TokenRow.test.tsx
src/token/components/TokenRow.tsx
src/token/core/formatAmount.test.ts
src/token/core/formatAmount.ts
src/token/types.ts
yarn.lock

feat: TokenRow component

---

.changeset/fifty-adults-rest.md
src/frame/types.ts

This PR updates the `FrameTransactionResponse` type to accommodate an `eth_personalSign` method needed for XMTP consent proofs.

Update type for consent proofs

---

jest.config.cjs
site/docs/pages/token/token-chip.mdx
src/cssStub.ts
src/token/components/TokenChip.css
src/token/components/TokenChip.tsx

- add TokenChip.css to handle css modifiers (`:hover`)
| Normal | Hover | Active |
| --- | --- | --- |
| <img width="103" alt="Screenshot 2024-05-30 at 5 20 41 PM" src="https://github.com/coinbase/onchainkit/assets/132851666/96ff4bb2-24fd-41c7-a6bb-9b044851cb6b"> | <img width="101" alt="Screenshot 2024-05-30 at 5 20 45 PM" src="https://github.com/coinbase/onchainkit/assets/132851666/0cd15630-a88f-49e0-88ea-c5fa0add5502"> | <img width="100" alt="Screenshot 2024-05-31 at 4 28 34 PM" src="https://github.com/coinbase/onchainkit/assets/132851666/f8486879-d833-43e8-b0df-fc31dcb38c70"> |
locally

feat: TokenChip.css

---

.changeset/wild-dragons-sleep.md
site/docs/pages/token/introduction.mdx
site/docs/pages/token/token-image.mdx
site/docs/pages/token/token-selector.mdx
site/docs/pages/token/types.mdx
site/sidebar.ts
src/token/components/TokenImage.test.tsx
src/token/components/TokenImage.tsx
src/token/components/TokenSelector.test.tsx
src/token/components/TokenSelector.tsx
src/token/index.ts
src/token/types.ts

- add TokenImage to render token image
- add TokenSelector to render a button displaying token info or placeholder text
locally

feat: TokenImage and TokenSelector components

---

prettier.config.cjs

Added JSDOC typing to prettier config file for completion
Open editor then try completion

chore: add jsdoc to `prettier` config file

---

.changeset/hot-balloons-wave.md
site/docs/pages/App.tsx
site/docs/pages/token/token-search.mdx
src/index.css
src/token/components/TextInput.css
src/token/components/TextInput.tsx
src/token/components/TokenSearch.test.tsx
src/token/components/TokenSearch.tsx

- convert `TokenSearch` to css
- add modifier styles
- update placeholder text
- add clear button to `TextInput`
- add commented import to `site/docs/pages/App.tsx`
Default state
Hover
Focus
Clear button
locally

feat: convert TokenSearch to css and add modifier styles

---

site/docs/pages/onchainkit-provider.mdx

This PR makes the `/onchainkit-provider` documentation page clearer by:
- highlighting forgotten line
- fixing a typo: chain="base" -> chain={base}
This is actually a reopen of my previous PR https://github.com/coinbase/onchainkit/pull/450 as I messed up syncing my fork.
It doesn't include the changes that make `prettier` angry. For more context, see my comment https://github.com/coinbase/onchainkit/pull/450#issuecomment-2151484639

chore: make provider page clearer

---

README.md
site/docs/pages/frame/framegear.mdx
site/docs/pages/frame/introduction.mdx
site/docs/pages/getting-started.mdx
site/docs/pages/identity/introduction.mdx
site/docs/pages/index.mdx
site/docs/pages/token/introduction.mdx
site/docs/pages/wallet/introduction.mdx
site/docs/pages/xmtp/introduction.mdx

Add `bun` usage to code groups. Feels good to have it for bun users.
Looks like this
Launched docs locally with `yarn dev`

docs: add `bun` usage

---

site/docs/pages/contribution-guide.mdx
site/docs/pages/token/token-image.mdx
src/token/components/TokenImage.test.tsx
src/token/components/TokenImage.tsx
src/token/components/TokenSelector.tsx
src/token/components/getTokenImageColor.test.ts
src/token/components/getTokenImageColor.ts
src/token/types.ts

- TokenImage with no image renders partial token symbol and deterministic dark color
- fix typo in contribution-guide.mdx
Can't use the usual className approach to override `TokenImage` due to adjusting styles depending on prop values
locally

feat: TokenImage with no image renders partial token symbol and deterministic dark color

---

package.json

Added `packageManager` field to `package.json`
It helps for reproducibility.
And some people (like me) use [corepack](https://nodejs.org/api/corepack.html) to handle package managers between repositories.
I specified the latest version `1.22.22` of Yarn. Feel free to specify the one you prefer.

chore: specify package manager

---

.changeset/five-sloths-battle.md
site/docs/pages/token/token-row.mdx
src/index.css
src/token/components/TokenRow.css
src/token/components/TokenRow.test.tsx
src/token/components/TokenRow.tsx
src/token/types.ts

- convert TokenRow to css
- add modifier states
- add display controls
TokenRow display controls
Hover
Active
locally

feat: update TokenRow

---

.changeset/tasty-pants-eat.md
site/docs/components/TokenSelectorContainer.tsx
site/docs/pages/token/token-selector.mdx
site/docs/pages/token/types.mdx
src/index.css
src/token/components/TokenRow.tsx
src/token/components/TokenSelector.css
src/token/components/TokenSelector.test.tsx
src/token/components/TokenSelector.tsx
src/token/components/TokenSelectorDropdown.css
src/token/components/TokenSelectorDropdown.test.tsx
src/token/components/TokenSelectorDropdown.tsx
src/token/index.ts
src/token/types.ts

- add `TokenSelectorDropdown` to be used with `TokenSelectorDropdown`
With scrollbar
`TokenSelector` and `TokenSelectorDropdown` should be built with non-div elements like `select` and `option`. I will address this in future PRs.
locally

feat: TokenSelectorDropdown

---

.changeset/big-worms-lie.md
site/docs/pages/token/token-row.mdx
site/docs/pages/token/token-search.mdx
site/docs/pages/token/token-selector.mdx
site/docs/pages/token/types.mdx
src/token/components/TextInput.css
src/token/components/TokenRow.tsx
src/token/components/TokenSelectorDropdown.tsx

- `TokenSelectorDropdown` shows token image
| Old | New |
| ---- | ---- |
| <img width="276" alt="Screenshot 2024-06-07 at 1 36 16 PM" src="https://github.com/coinbase/onchainkit/assets/132851666/46c6826c-5a89-4c38-a5cd-5fe4ccd40cdc"> | <img width="276" alt="Screenshot 2024-06-07 at 1 34 30 PM" src="https://github.com/coinbase/onchainkit/assets/132851666/dc280902-6ff1-44b5-9ff3-7026244d3e69"> |
- Remove border from `TokenSearch`
| Old | New |
| --- | --- |
| <img width="896" alt="Screenshot 2024-06-07 at 1 38 18 PM" src="https://github.com/coinbase/onchainkit/assets/132851666/7a56fc7e-8655-4c7a-8378-a0f077824610"> | <img width="719" alt="Screenshot 2024-06-07 at 1 38 49 PM" src="https://github.com/coinbase/onchainkit/assets/132851666/469f6d9e-5388-45d5-a484-b0b5acd36 …

feat: TokenKit style update

---

.changeset/olive-keys-repair.md
site/docs/pages/token/token-selector.mdx

- add back `TokenSelectorDropdown` example
locally

docs: add back TokenSelectorDropdown example to docs

---

.changeset/dirty-rice-grow.md
site/docs/pages/token/token-selector.mdx
src/token/components/TokenSelectorDropdown.css

- Reduce the gap between `TokenSelector` and `TokenSelectorDropdown`
| Old | New |
| --- | --- |
| <img width="330" alt="Screenshot 2024-06-07 at 5 27 21 PM" src="https://github.com/coinbase/onchainkit/assets/132851666/2666b580-0006-4808-9fe0-8a32abc99d40"> | <img width="330" alt="Screenshot 2024-06-07 at 5 19 05 PM" src="https://github.com/coinbase/onchainkit/assets/132851666/31c14f3f-964a-4d3f-aa44-faffe25b1131"> |
locally

fix: adjust TokenSelectorDropdown margin-top

---

.github/actions/setup/action.yml
.github/workflows/build.yml
.github/workflows/canary.yml
.github/workflows/check.yml
.github/workflows/release.yml
.github/workflows/salus-scan.yml
.github/workflows/site.yml
.github/workflows/test.yml

It's nice to be up-to-date. AFAIK there is no breaking changes between v3 and v4 for both `actions/setup-node` and `actions/checkout` besides using Node.js v20 as the default runtime instead of v16 which Node.js dropped out from their long time support.
https://github.com/actions/setup-node/compare/v3...v4.0.0#diff-1243c5424efaaa19bd8e813c5e6f6da46316e63761421b3e5f5c8ced9a36e6b6R36
https://github.com/actions/checkout/compare/v4.0.0...v4.1.0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R15

chore: bump github actions

---

package.json
yarn.lock

Removed Yarn classic from dependencies since Yarn berry is used in this repository.
https://github.com/coinbase/onchainkit/blob/409503c3352f595591013fcca6bd4ec2bf36850e/.yarnrc.yml#L3

chore: remove Yarn classic from dependencies

---

.changeset/small-cooks-wave.md
package.json
src/styles/tailwind-base.css

- add tailwind utility classes to exported styles.css
locally

fix: add tailwind utility classes to exported styles.css

---

.changeset/honest-jeans-change.md
jest.config.cjs
src/definitions/swap.ts
src/swap/core/getParamsForToken.ts
src/swap/core/getQuote.ts
src/swap/core/getSwap.test.ts
src/swap/core/getSwap.ts
src/swap/core/getTransaction.test.ts
src/swap/core/getTransaction.ts
src/swap/index.ts
src/swap/types.ts

- add `getSwap`
- add `SwapParams` for both `getQuote` and `getSwap` (shared params for all `core/swap` utils)
- add types and `Transaction` interface with a helper method for injecting `nonce` and EIP-1559 gas values
- we do not support `gasPrice` (i.e. pre-EIP-1559 transactions)
- we may need to slightly tweak the data shape/parameters to support Wagmi's [useSendTransaction](https://wagmi.sh/react/api/hooks/useSendTransaction#usage) hook - this was built with usage in Viem's [sendTransaction](https://viem.sh/docs/actions/wallet/sendTransaction.html) in mind. (next PR)
Checking for a warning
```typescript
const swap = await getSwap({
fromAddress: account.address, // This address doesn't have ETH to pay gas, so the …
```

feat: `getSwap`

---

site/docs/pages/swap/get-swap-quote.mdx
site/sidebar.ts

docs: `getSwapQuote`

---

src/swap/components/Swap.tsx
src/swap/utils.test.ts
src/swap/utils.ts

- format amount returned from `getSwapQuote`

chore: Add token amount formatter

---

.github/labeler.yml
.github/workflows/labeler.yml

This PR adds a pull request labeler workflow using https://github.com/actions/labeler to make easier to see which packages are impacted. Labels are sorted alphabetically so it matches file tree.

feat: add pull request labeler

---

package.json
src/swap/components/SwapAmountInput.test.tsx
src/swap/components/SwapAmountInput.tsx
src/swap/utils.test.ts
src/swap/utils.ts

- integrate wagmi `useBalance` hook
- display balance and max button
- balance will also appear on `to` token 

feat: Add balance to SwapAmountInput

---

.changeset/tame-planets-search.md
src/token/components/SearchIcon.tsx
src/token/components/TextInput.tsx
src/token/components/TokenChip.test.tsx
src/token/components/TokenChip.tsx
src/token/components/TokenImage.tsx
src/token/components/TokenRow.tsx
src/token/components/TokenSearch.tsx
src/token/components/TokenSelectButton.tsx
src/token/components/TokenSelectDropdown.tsx

- fix token components lint errors
I will do `useDebounce` on a follow up PR.
locally

fix: token components lint errors

---

.changeset/fuzzy-eggs-cross.md
.changeset/proud-buttons-flash.md
.changeset/tame-planets-search.md
README.md
package.json
site/docs/pages/identity/introduction.mdx
site/docs/pages/token/introduction.mdx
site/docs/pages/wallet/introduction.mdx
yarn.lock

chore: release

---

src/wallet/constants.ts
src/wallet/isWalletASmartWallet.test.ts
src/wallet/isWalletASmartWallet.ts

- updated `isWalletASmartWallet` to check `initCode` for undeployed accounts
unit tests

fix: update smart wallet util

---

.changeset/ninety-windows-cheer.md
README.md
site/docs/pages/index.mdx
site/docs/pages/wallet/is-wallet-a-coinbase-smart-wallet.mdx
site/docs/pages/wallet/types.mdx
site/sidebar.ts
src/wallet/index.ts
src/wallet/isWalletACoinbaseSmartWallet.test.ts
src/wallet/isWalletACoinbaseSmartWallet.ts
src/wallet/types.ts

Update `isWalletASmartWallet` naming to be `isWalletACoinbaseSmartWallet` so we explicitly state what the function is doing. 

chore: Update isWalletASmartWallet to isWalletACoinbaseSmartWallet

---

.changeset/rich-dolls-sort.md
package.json
src/swap/components/Swap.tsx
src/swap/components/SwapAmountInput.tsx

- fix get quote logic in Swap component
locally

fix: get quote logic in Swap component

---

.changeset/bright-tigers-try.md
package.json
src/internal/text/TextLabel2.tsx
src/internal/text/TextTitle3.tsx
src/internal/text/index.ts
src/styles/index-with-tailwind.css
src/styles/index.css
src/swap/components/Swap.tsx
src/swap/components/SwapAmountInput.tsx

- add `DM Sans` font
- For tailwind users, it will default to `text-sans` unless they modify import `DM Sans` via
```css
@import url("https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz@0,9..40;1,9..40&display=swap");
@import url("https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,700;1,9..40,700&display=swap");
```
- Tailwind users can also override `text-display` class to use whatever font-family they want
- For non-tailwind users, it will use `DM Sans` correctly
locally

feat: add DM Sans font

---

.changeset/quick-moles-taste.md
src/internal/text/TextLabel1.tsx
src/internal/text/TextLabel2.tsx
src/swap/components/SwapAmountInput.tsx

Fix SwapAmountInput text styles
Turns out tailwind compiler does not work with dynamically generated class names
locally

fix: SwapAmountInput styling

---

.changeset/strong-walls-film.md
src/OnchainKitConfig.test.ts
src/network/getRPCUrl.test.ts
src/network/getRPCUrl.ts

- direct users to `products/onchainkit` in the CDP Portal instead

fix: error message from unset api key

---

.changeset/serious-flies-tie.md
site/docs/pages/swap/swap.mdx
site/docs/pages/swap/types.mdx
src/swap/components/SwapButton.tsx
src/swap/types.ts

- add optional `disabled` prop to `SwapButton` so users can control whether or not swap is swappable
locally

feat: Add disable swap button functionality

---

.changeset/few-buttons-share.md
site/docs/pages/restricted.mdx
site/docs/pages/temp-demo.mdx
site/middleware.ts
site/package.json
site/yarn.lock

Add Vercel Edge Middleware to enable Geo Blocking for the entire OnchainKit site. 
- Add restricted page. 
- Redirect users in a blocked region to the restricted page.
- Restrict the following countries `North Korea (KP), Iran (IR), Syria (SY), Cuba (CU), Crimea (UA-43), Luhansk (UA-09), Donetsk (UA-14)`
Edge Middleware is code that executes before a request is processed on a site. We can further update our middleware to execute custom logic, rewrite, redirect, add headers and more, before returning a response!
[API Reference.](https://vercel.com/docs/functions/edge-middleware/middleware-api#middleware-helper-methods)
Tested in dev with the US being blocked and unblocked.

feat: Enable Geo Blocking for restricted territories

---

site/docs/pages/temp-demo.mdx
site/middleware.ts

Temporarily block onchainkit.xyz/temp-demo in the US to ensure that our geo blocking is working. 

chore: Block onchainkit.xyz/temp-demo 

---

.changeset/three-bottles-kiss.md
src/swap/components/Swap.tsx
src/swap/components/SwapAmountInput.tsx
src/swap/components/SwapButton.tsx
src/swap/components/SwapMessage.tsx
src/swap/components/SwapToggleButton.tsx

This PR adds `use client` directives to components intended to be run only on the client such as:
- contexts
- buttons
- inputs
- those using `useState`
- ...
This way it would be easier to integrate to projects that use server components

feat: add `use client` directives to swap components

---

.changeset/happy-avocados-matter.md
site/docs/components/App.tsx

- force doc site to connect to base chain
locally

docs: force doc site to connect to base chain

---

.changeset/stupid-shoes-sip.md
site/docs/pages/getting-started.mdx

Add `OnchainProviders.tsx` file name:
Add code focus for the newly added  `OnchainProviders.tsx` code in the `ConfigureWagmiProvider` step:

chore: Update Getting Started guide

---

.changeset/friendly-ants-peel.md
site/docs/pages/swap/swap.mdx

Update wagmi import from `sendTransaction` to `useSendTransaction`. 
Add `EthToken` and `USDCToken` parameters to make it easier for the developer to copy and paste code to get started.

chore: Update Swap component docs

---

.changeset/nine-goats-battle.md
package.json

fix: move viem and wagmi to peer dependencies

---

.changeset/breezy-news-reflect.md
site/docs/components/App.tsx
site/docs/pages/wallet/introduction.mdx

Removing the following unsupported fields from the Coinbase Wallet Provider:
- `appChainIds`
- `options`

chore: Remove coinbase wallet provider fields

---

src/identity/components/Identity.tsx
src/identity/components/IdentityLayout.tsx
src/identity/types.ts
src/utils/getRoundedAmount.ts

- addressing previous PR comments

chore: wallet clean up

---

.changeset/real-guests-repeat.md
site/docs/components/WalletDemo.tsx

Avoid overlapping neighbor divs by adding bottom margin.  

docs: Increase Wallet Demo margin

---

.changeset/famous-readers-matter.md
site/docs/pages/identity/address.mdx
site/docs/pages/identity/name.mdx
site/docs/pages/identity/types.mdx
site/package.json
site/yarn.lock

Tracking issue: https://github.com/coinbase/onchainkit/issues/732
| Part | Description | Status |
|---|----|---|
| 1 | [[Part 1] feat: Add isSliced option to Address and remove slice logic from Name](https://github.com/coinbase/onchainkit/pull/747) | ✅  |
| 2 | [[Part 2] docs: Add isSliced option to Address and remove slice logic from Name](https://github.com/coinbase/onchainkit/pull/733) | _In Progress_|
Add the `isSliced` option to the `Address` component. This allows the component to render the full users address when set to false. 
Update the `Name` component to remove slice logic and return null if the ENS name is not found.
- Add documentation examples to show the `false` case for the Address component. 
- Update displayed examples on the Name and Address docs …

docs: Add isSliced option to Address and remove slice logic from Name

---

.changeset/ninety-rats-applaud.md
site/docs/pages/identity/address.mdx
site/docs/pages/identity/name.mdx

Update the Name and Address code snippets and component examples so that they match. The intention is to maximize the parity between the code snippets in the documentation and the displayed components.
- Remove some hidden component styling that was intended to improve readability - we want to maximize for authenticity. 
- 

docs: Update Name and Address code snippets and component examples

---

.changeset/strong-icons-pump.md
site/docs/pages/getting-started.mdx

Add `Wrap Your App with OnchainProviders` section in the getting started guide. 
This is a follow up from my dogfooding feedback [here](https://coinbase.slack.com/archives/C06NZU31P4N/p1719185284498779) - _"It wasn't clear that I had to wrap my root component in the OnchainProviders - I had to reference the Wagmi docs to remember this step."_

docs: Add Wrap Your App with OnchainProviders section

---

.changeset/sweet-drinks-impress.md
site/docs/pages/getting-started.mdx

Add links to ready-to-use onchain components: `Identity`, `Wallet`, `Tokens`, `Swap`, `Frame`.
This is a follow up from my dogfooding feedback here - _"Completing the guide doesn't result in anything working; it transitions into the docs starting with components then utilities. This feels disjointed and incomplete."_
Added a "Next Steps" section at the bottom of the `Getting Started` guide to provide direction to developers after completing the `Getting Started` guide.
I initially aimed for rendering something locally when the developer completed the Getting Started page, similar to create-react-app or Wagmi. This idea is better suited for a future "Quick Start" guide - which can work in addition to a `Getting Started` page.` Getting Started` is for when developers …

docs: Add Next Steps to the Getting Started page

---

.changeset/late-keys-deny.md
.changeset/two-pigs-itch.md
src/identity/components/Name.stories.tsx
src/identity/components/Name.test.tsx
src/identity/components/Name.tsx
src/identity/core/getName.test.tsx
src/identity/core/getName.ts
src/identity/hooks/getNewReactQueryTestProvider.tsx
src/identity/hooks/useName.test.tsx
src/identity/hooks/useName.ts
src/identity/types.ts

- **feat**: Added `chain` option to `useName` function for L2 chain name resolution support. 
- **feat**: Added `chain` option to `<Name>` component for L2 chain name resolution support.
- **fix**: Modified `getName` to return a rejected promise instead of an error. 
- **fix**: Disabled `retry` in `getNewReactQueryTestProvider` to run tests faster and avoid timeouts. 
- locally with 100% passing
- 100% test coverage
- In storybook

Feat: Add chain to useName

---

.changeset/many-readers-prove.md
.changeset/old-beds-yawn.md
src/identity/components/Address.test.tsx
src/identity/components/Address.tsx
src/identity/components/Avatar.test.tsx
src/identity/components/Avatar.tsx
src/identity/components/DisplayBadge.test.tsx
src/identity/components/DisplayBadge.tsx
src/identity/components/EthBalance.test.tsx
src/identity/components/EthBalance.tsx
src/identity/components/Identity.tsx
src/identity/components/IdentityProvider.test.tsx
src/identity/components/IdentityProvider.tsx
src/identity/components/Name.test.tsx
src/identity/components/Name.tsx
src/identity/types.ts

- **feat**: Added `chain` option to `<IdentityProvider>` for L2 chain name resolution support.
- **feat**: Added `chain` option to `<Identity>` component for L2 chain name resolution support.
- **fix**: Modify `<Name>` to prioritize its own address/chain props over the provider's. 
- **fix**: Modify `<Address>`, `<Avatar>`, `<EthBalance>` to prioritize its own address prop over the provider's. 
Locally 100% test passing / coverage

Feat: add chain to IdentityProvider and Identity

---

.changeset/tame-suns-rule.md
src/identity/core/getName.test.tsx
src/identity/core/getName.ts
src/identity/hooks/useName.test.tsx

- **fix**: Modified `getName` to default to ENS name when custom chain name is not available.
Add tests, 100% coverage

Feat: getName: Default to ENS name when custom chain name is not available

---

.changeset/flat-readers-reflect.md
site/docs/pages/identity/types.mdx
site/docs/pages/identity/use-name.mdx

- **fix**: Update type documentation for `useName`, `getName`, `<Name>` & `<Identity/>`

Fix: Update type documentation for custom chain name resolution

---

.changeset/forty-carpets-double.md
site/docs/pages/index.mdx

Add Terms of Service to the landing page footer.
- The link points towards the Base docs Terms of Service - https://docs.base.org/docs/terms-of-service/

docs: Add Terms of Service

---

.changeset/cool-nails-wash.md
site/docs/pages/index.mdx

Update Terms of Service to point towards Coinbase Developer Platform Terms of Service rather than the Base Docs ToS. 
https://www.coinbase.com/legal/cloud/terms-of-service

docs: Update TOS

---

.changeset/big-worms-sparkle.md
src/identity/components/Identity.test.tsx

Add `Identity.tsx` unit tests to improve test coverage from 73% to 100%. Adding coverage to the `handleCopy` function.
**Old:**
**New:**

chore: Add Identity.tsx unit tests

---

.changeset/moody-deers-occur.md
vitest.config.ts

Update test coverage report to ignore our static SVG files such as `disconnectSvg.tsx` and `walletSvg.tsx`. This cleans up our test coverage report and gives us a more accurate depiction of our test coverage. 
**Before:**
**After:**

chore: Ignore SVG files during testing

---

.changeset/wet-cougars-pay.md
src/wallet/components/WalletDropdownDisconnect.test.tsx
src/wallet/components/WalletDropdownLink.test.tsx

Add unit tests for `WalletDropdownDisconnect.tsx` and `WalletDropdownLink.tsx`.
**Before:**
**After:**

chore: Add WalletDropdown Disconnect and Link tests

---

site/docs/pages/transaction/transaction.mdx
src/internal/loading/Spinner.tsx
src/transaction/components/TransactionProvider.tsx
src/transaction/components/TransactionToast.tsx
src/transaction/components/TransactionToastAction.tsx
src/transaction/components/TransactionToastIcon.tsx
src/transaction/components/TransactionToastLabel.tsx
src/transaction/core/useGetTransactionToast.tsx
src/transaction/types.ts

- add transaction toast components

feat: Add transaction toast components

---

.changeset/six-poets-pull.md
site/docs/pages/index.mdx
site/docs/styles.css

**Update styling for our documentation code block snippets - most notably we are overriding the background color to match the rest of the docs.** 
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
**Update `MIT License` and `Terms of Service` in the landing page footer.** 
- Make text smaller. 
- Update language.
- Update format to be inline. 
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
**Update Landing Page "hero" to have less inline spacing.** 
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
**Update the footer OnchainKit text to match the …

docs: Update code block styling

---

.changeset/six-poets-pull.md
site/docs/pages/index.mdx
site/docs/styles.css

<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
Increase installation width to not cut off on mobile.

docs: Remove code group border

---

.changeset/lazy-shoes-work.md
src/identity/components/Name.test.tsx
src/identity/components/Name.tsx

Fix `Name` component to return the sliced address when no ENS name is found.

chore: Return the sliced address when no ENS name is found

---

site/docs/pages/transaction/transaction.mdx

Little typo fix on the message that Transaction component is not shipped yet.
Locally

chore: typo fix

---

.changeset/modern-cameras-reflect.md
site/docs/pages/wallet/wallet.mdx
src/identity/utils/getSlicedAddress.test.ts
src/identity/utils/getSlicedAddress.ts

Update the number of characters that a sliced address displays to show 4 characters before and after the ellipsis. 
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

chore: Update sliced address display

---

.changeset/young-pets-buy.md
src/transaction/components/TransactionProvider.test.tsx
src/transaction/components/TransactionProvider.tsx
src/transaction/hooks/useWriteContract.ts
src/transaction/hooks/useWriteContracts.ts

Add `EOA` account support to the `Transaction Component`. 
- Add `useWriteContract` wrapper.
- To support both `Smart Wallets` and `EOA` wallets we are defaulting to use `writeContracts` first, and then if that fails with an `EOA` specific error then we fallback to use `writeContract` and iterate through the list of contracts that were intended to be batched.
- Add basic functionality test for the Transaction Provider
Basic functionality unit test :
Tested locally on BaseSepolia. 
EOA Transaction landed onchain https://sepolia.basescan.org/tx/0x950f41d5bc0fe191b3a019d4c00f2ee295c1fb0a77f5a99d2db54334d5c3a300

feat: Add EOA account support to Transaction Component

---

.changeset/brown-moose-doubt.md
src/identity/components/Avatar.test.tsx
src/identity/components/Avatar.tsx
src/identity/hooks/useName.ts
src/identity/types.ts

**fix**: fix `useName` hook to use `chain.id` in the query key to avoid overlap between chains

Fix: Fix the usename hook to use chain.id  in the query key to avoid overlap between chains

---

.changeset/brave-lobsters-begin.md
src/transaction/hooks/useWriteContract.test.ts
src/transaction/hooks/useWriteContracts.test.ts

Add tests for `useWriteContract` and `useWriteContracts`. This is part of the initiative to increase `TransactionComponent` test coverage before the launch. 
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

chore: Add tests for useWriteContract and useWriteContracts wrapper

---

src/swap/components/Swap.tsx
src/swap/components/SwapProvider.tsx
src/swap/types.ts
src/swap/utils/buildSwapTransaction.test.ts
src/swap/utils/buildSwapTransaction.ts
src/swap/utils/getSwapQuote.test.ts
src/swap/utils/getSwapQuote.ts

- add `aggregators` prop to `<Swap/>` to control `V1` or `V2` API
- this will add the `v2Enabled` parameter in the request body, our API will route these to a beta implementation for serving quotes/trades directly from Uniswap V3
`V1` API does not index pools with under <= $10,000 of liquidity, `V2` API will make a direct call to the `UniswapRouter` contract
`slippage` for the `V2` API is hardcoded to 1000 bps (10%) - Tina is aligned for the initial launch and we'll fast-follow to add configurability to the UI
usage
```javascript
<Swap address={address} experimental={{ useAggregator: false }}>
...
</Swap>
```
See Slack for demo

feat: `v2` Swap API

---

.changeset/four-cups-shave.md
src/identity/components/Name.stories.tsx
src/identity/constants.ts
src/identity/types.ts
src/identity/utils/convertChainIdToCoinType.test.ts
src/identity/utils/convertChainIdToCoinType.ts
src/identity/utils/convertReverseNodeToBytes.test.ts
src/identity/utils/convertReverseNodeToBytes.ts
src/identity/utils/getName.ts

**feat**: Add `convertChainIdToCoinType` function to convert a chainId to a coinTypeHex for ENSIP-19 reverse resolution.
**fix**: Modify `convertReverseNodeToBytes` to use `convertChainIdToCoinType` instead of hardcoded resolver address.
**fix**: Modify `useName` to return a type `BaseName` for extra type safety. 
**feat**: Add more storybook scenarios for `<Name>`.

Feat: Add ENSIP-19 support to getName

---

.changeset/stale-spies-refuse.md
site/docs/components/App.tsx
site/docs/pages/identity/badge.mdx

Fix Identity Badge documentation page. The badge component example for custom styling was not behaving as expected. Updating to use the className override. 
Fix grammar. 
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

docs: Fix Identity Badge page

---

.changeset/unlucky-falcons-thank.md
site/docs/pages/identity/badge.mdx
site/docs/pages/index.mdx

<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

docs: Display badge component on landing page

---

.changeset/twelve-rings-return.md
site/docs/pages/transaction/transaction.mdx

- Fix using the Vercel ENV variable for the Paymaster URL
- Swap the Transaction with TransactionToast components and the Transaction with Paymaster Gas sponsorship capabilities sections.

docs: Fix Transaction Component Paymaster

---

.changeset/afraid-dogs-vanish.md
src/internal/svg/baseNameSvg.tsx
src/wallet/components/WalletDropdownBaseName.test.tsx
src/wallet/components/WalletDropdownBaseName.tsx
src/wallet/index.ts
src/wallet/types.ts

Add the Base Name tab to the Wallet Component. When a user has a Base Name, this tab will direct them to their Base Name profile page. If a user does not have a Base Name, this tab will direct them to a page where they can create one!
- Add `WalletDropdownBaseName` component
- Add BaseName SVG
- Add `WalletDropdownBaseName` tests
| Part | Description | Status |
|---|----|---|
| 1 | [feat: Implement WalletDropdownBaseName Sub-Component #913](https://github.com/coinbase/onchainkit/pull/913) | _In Progress_|
| 2 | [docs: Implement WalletDropdownBaseName Sub-Component #916](https://github.com/coinbase/onchainkit/pull/916) | _In Progress_|
Video recording:
[Wallet Components & Utilities · OnchainKit - 27 July 2024 - Watch …

feat: Implement WalletDropdownBaseName Sub-Component 

---

.changeset/seven-peas-brush.md
src/swap/components/SwapButton.tsx
src/swap/components/SwapProvider.tsx
src/swap/types.ts
src/swap/utils/processSwapTransaction.test.ts
src/swap/utils/processSwapTransaction.ts

add `onStart` hook to `SwapButton`, which will be called with the `txHash` (tx receipt has not been awaited yet). 
for swaps from ERC-20s, the `onStart` hook will be ran twice (one for the approval transaction, one for the actual transaction)
this is to expose more transaction state in order to enable use cases like custom toast messages
locally and in unit tests
```
<SwapButton
onStatus={{
onStart: async (txHash) => {
await new Promise((resolve) => setTimeout(resolve, 1000));
console.log('async onStart:', txHash);
},
}}
/>
```

feat: add `onStart` hook to `SwapButton`

---

site/docs/pages/transaction/types.mdx
src/swap/components/Swap.test.tsx
src/swap/components/SwapToggleButton.test.tsx
src/transaction/components/TransactionProvider.test.tsx
src/transaction/components/TransactionProvider.tsx
src/transaction/hooks/useCallsStatus.ts
src/transaction/hooks/useWriteContract.test.ts
src/transaction/hooks/useWriteContract.ts
src/transaction/types.ts

- implement `waitForTransactionReceipt` to handle case where user passes multiple contracts and is using EOA
- this function will be called for each transaction hash so that we can pass multiple receipts in onsuccess handler

Update txn success handler to pass multiple receipts for multiple contracts (EOA)

---

site/package.json
site/yarn.lock

docs: latest

---

site/docs/components/TransactionWrapper.tsx

justify-center is aligning items along the main axis (horizontally in this case).
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

docs: Fix Transaction Wrapper item alignment

---

.changeset/ten-swans-trade.md
src/swap/components/SwapAmountInput.test.tsx

<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

chore: Add tests for SwapAmountInput

---

.changeset/nervous-pugs-boil.md
src/swap/hooks/useSwapBalances.test.tsx

<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

chore: Add useSwapBalances tests

---

site/docs/pages/index.mdx
site/docs/styles.css
site/package.json
site/vocs.config.tsx
site/yarn.lock

Update doc site to support dark mode styling.
Blocked by: https://github.com/coinbase/onchainkit/pull/977
locally

docs: dark mode support

---

.changeset/honest-lies-walk.md
site/docs/pages/identity/types.mdx
site/docs/pages/identity/use-avatar.mdx
src/identity/components/Avatar.stories.tsx
src/identity/components/Avatar.tsx
src/identity/hooks/useAvatar.test.tsx
src/identity/hooks/useAvatar.ts
src/identity/index.ts
src/identity/types.ts
src/identity/utils/getAvatar.test.tsx
src/identity/utils/getAvatar.ts

- **feat**: Add chain props to `useAvatar` and `getAvatar` to resolve Base avatar.
- **feat**: Modify `getAvatar` to resolve Base avatar, and fallback to mainnet if none is found.

Feat: Add Base avatar support, Fallback to Mainnet

---

.changeset/cool-moons-bake.md
site/docs/pages/transaction/types.mdx
src/transaction/index.ts

chore: export `TransactionResponse` type

---

site/docs/pages/guides/tailwind.mdx
site/tailwind.config.js

Update docs site tailwind setup
Locally

docs: update docs site tailwind setup

---

site/docs/components/TransactionWrapper.tsx
src/transaction/components/TransactionToast.tsx

- remove txn background on docs
- fix dark mode txn toast styling

chore: Adjust dark mode styles

---

src/transaction/components/TransactionButton.tsx
src/transaction/types.ts
src/transaction/utils/isSpinnerDisplayed.test.ts
src/transaction/utils/isSpinnerDisplayed.ts

chore: more utils

---

src/swap/components/SwapProvider.test.tsx

chore: added test coverage to swap provider

---

src/transaction/components/TransactionProvider.test.tsx

chore: Add transaction provider tests

---

.changeset/many-ravens-cry.md
src/wallet/components/ConnectWallet.test.tsx

chore: Add Connect Wallet tests

---

.changeset/many-ravens-cry.md
src/wallet/components/WalletDropdownBaseName.tsx
src/wallet/components/WalletDropdownDisconnect.tsx
src/wallet/components/WalletDropdownLink.tsx

Increase our wallet logo sizes from 16x16 to 18x18. 
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

chore: Increase Wallet dropdown SVG sizes to 18x18

---

src/transaction/hooks/useWriteContract.test.ts
src/transaction/hooks/useWriteContracts.test.ts
src/transaction/hooks/useWriteContracts.ts

- add test coverage
- remove console log statement in useWriteContracts because it is confusing to see error printed in console when txn is actually successful 

chore: Add test coverage and remove console.log statement

---

src/transaction/components/TransactionProvider.test.tsx
src/transaction/components/TransactionProvider.tsx
src/transaction/types.ts
vitest.config.ts

chore: more error cleanup

---

src/transaction/components/TransactionButton.test.tsx
src/transaction/components/TransactionProvider.test.tsx
src/transaction/hooks/useCallsStatus.test.ts

chore: Add more test coverage

---

site/docs/pages/swap/swap.mdx

This example broke after we updated how we implement light mode / dark mode. 
This fixes that render and also updates our showcase styling to match our figma docs. 

docs: Fix Swap override styles example

---

.changeset/afraid-tips-whisper.md
src/identity/components/Avatar.stories.tsx
src/identity/components/Avatar.tsx

**fix**: Modify `Avatar` component to handle images with varying height/width ratio.

add min height/width and object fit cover to avatar

---

src/frame/types.ts
src/frame/utils/getFrameMetadata.test.ts
src/frame/utils/getFrameMetadata.ts
src/frame/utils/setFrameMetadataButtons.test.ts
src/frame/utils/setFrameMetadataButtons.ts

* updated `FrameButtonMetadata` to allow custom `postUrl` property
* updated `getFrameMetadata` to handle custom `postUrl`s on Frame Buttons

Feat: Better Handling of FrameButton post actions

---

.changeset/dry-ligers-end.md
playground/nextjs-app-router/app/layout.tsx
playground/nextjs-app-router/components/Demo.tsx

Update playground title from `OnchainKit Demo` to `OnchainKit Playground`.
Update Github link to point to https://github.com/coinbase/onchainkit/tree/main/playground

chore: Update Playground title and Github link 

---

.changeset/dry-ligers-end.md
src/styles/theme.ts
src/transaction/components/TransactionButton.tsx
src/wallet/components/WalletDropdown.tsx

Fix hover state styling for all components and update specific buttons
Issue:
- Our themed CSS class variables were not correctly applying the custom hover styles.
- As a result, none of the components were displaying our intended default hover styling.
Fix:
1. In theme.ts: Corrected how we access the hover state variable.
2. For TransactionButton and WalletDropdown:
- Implemented the 'pressable' class.
- This maintains their current styling while also enabling the use of our defined state classes (including hover).
Outcome:
- All components now correctly display the default hover styling.
- TransactionButton and WalletDropdown have consistent styling with added state-based effects.
[Watch the video walkthrough to see the tested …

chore: Fix hover state for all components

---

site/docs/pages/index.mdx

The TransactionButton on the landing page was not updating background colors on theme switch. This is because the background color was hard coded and taking priority. Removing the hardcoded bg. 

docs: Fix Landing Page Transaction Component

---

site/docs/pages/index.mdx

https://linear.app/coinbase/issue/BOE-300/light-mode-button-and-link-colors-should-be-indigo-600-not-indigo-400
https://linear.app/coinbase/issue/BOE-301/add-hover-state-to-all-the-buttons
1. **Fix button and link colors in light mode:** 
- Our button and link border and text colors were not updating when switching from dark to light mode. 
- Dark mode remains the same. 
2. **Update all start with and view docs buttons to highlight when hovered**
3. **Fix Get started** button light and dark mode styling. Also adding hover styling.
Light mode button and links are now indigo-600 rather than indigo-400.:
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

docs: Fix button and link colors in light mode

---

site/docs/pages/index.mdx

Hover on buttons were difficult to see, especially on light mode. 
Adding `hover:bg-gray-200` to light mode and `dark:hover:bg-gray-700` to dark mode. 
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

docs: Improve landing page button hover visibility

---

site/docs/components/landing/NavigationList.tsx
site/docs/pages/index.mdx
site/docs/styles.css
site/package.json
site/yarn.lock

https://linear.app/coinbase/issue/BOE-309/update-the-text-color-to-gray-950
Update the Landing Page light and dark mode text to match the Figma mockups. 
Bump /site `@coinbase/onchainkit` to  `0.29.2`
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

docs: Fix Landing Page text color in dark and light mode

---

site/vocs.config.tsx

https://linear.app/coinbase/issue/BOE-307/add-x-warpcast-to-the-topnav

docs: Add Twitter and Warpcast to Nav

---

site/vocs.config.tsx

docs: Rename Nav Templates

---

.changeset/brave-icons-fix.md
site/docs/pages/transaction/transaction.mdx
site/docs/pages/transaction/types.mdx
src/transaction/components/Transaction.tsx
src/transaction/components/TransactionButton.test.tsx
src/transaction/components/TransactionButton.tsx
src/transaction/components/TransactionProvider.test.tsx
src/transaction/components/TransactionProvider.tsx
src/transaction/components/TransactionSponsor.test.tsx
src/transaction/components/TransactionSponsor.tsx
src/transaction/types.ts

- remove address prop and use wagmi useAccount instead
- update life cycle status check for transaction sponsor

chore: remove address prop and update sponsor txn check

---

.changeset/many-ways-divide.md
src/internal/svg/disconnectSvg.stories.ts
src/internal/svg/disconnectSvg.tsx
src/wallet/components/WalletDropdownDisconnect.stories.tsx

https://linear.app/coinbase/issue/BOE-326/[wallet]-update-the-disconnect-icon-to-an-updated-icon
We are upgrading to a slightly larger SVG image. 
Storybook:
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

chore: Update Wallet disconnect SVG

---

playground/nextjs-app-router/.gitignore
src/internal/components/TextInput.tsx
src/swap/components/Swap.tsx
src/swap/components/SwapAmountInput.test.tsx
src/swap/components/SwapAmountInput.tsx
src/swap/components/SwapProvider.test.tsx
src/swap/components/SwapProvider.tsx
src/swap/index.ts
src/swap/types.ts
vitest.config.ts

feat: moved onSuccess and onError for Swap at top level

---

.changeset/brave-icons-fix.md
src/swap/components/SwapProvider.tsx
src/swap/utils/getAPIParamsForToken.ts

- resolves issue where it doesn't fetch quote if you start number with `.`

fix: Swap input amount bug fix

---

.changeset/dry-actors-bathe.md
src/transaction/hooks/useSendCall.test.ts
src/transaction/hooks/useSendCall.ts
src/transaction/hooks/useSendCalls.test.ts
src/transaction/hooks/useSendCalls.ts
src/transaction/types.ts

- scaffold `useSendCall` and `useSendCalls` in the same format as `useWriteContract` and `useWriteContracts` to support calldata in the `Transaction` component
N/A

feat: add `useSendCall` and `useSendCalls` hooks to support call-type transactions in `Transaction` component

---

.changeset/dry-actors-bathe.md
site/package.json
site/sidebar.ts
site/yarn.lock
src/api/index.ts
src/version.ts

chore: api module

---

playground/nextjs-app-router/components/OnchainProviders.tsx
playground/nextjs-app-router/components/demo/Swap.tsx
playground/nextjs-app-router/lib/constants.ts

- create `ENVIRONMENT_VARIABLES` map
- disable `SwapButton` only on `production` deployments (i.e. onchainkit.xyz/playground)
we can swap on preview deployments off PRs since they are behind authentication
can swap on preview deployment attached to this PR

playground: enable `Swap` in preview

---

.changeset/green-elephants-matter.md
src/swap/components/Swap.tsx
src/transaction/components/Transaction.tsx
src/useIsMounted.ts
src/wallet/components/Wallet.tsx

Following up on https://github.com/coinbase/onchainkit/issues/1077
User reported receiving a hydration warning from their next.js app when integrating the `Wallet` component which is likely because the `Wallet` component depends on client-specific data. The user is using pages routing and components in the pages/ directory are considered to be client-side by default, which, in this case, results in a hydration error. 
I am resolving this issue by returning `null` in `Wallet` component until the component mounts. 

chore: Fix wallet hydration issue on next.js

---

.changeset/modern-ladybugs-deliver.md
playground/nextjs-app-router/components/demo/Swap.tsx
site/docs/pages/index.mdx
site/docs/pages/swap/swap.mdx
site/docs/pages/swap/types.mdx
src/swap/components/Swap.tsx
src/swap/components/SwapProvider.test.tsx
src/swap/components/SwapProvider.tsx
src/swap/hooks/useFromTo.ts
src/swap/hooks/useSwapBalances.tsx
src/swap/types.ts
src/wallet/hooks/useGetETHBalance.ts
src/wallet/hooks/useGetTokenBalance.test.ts
src/wallet/hooks/useGetTokenBalance.ts

- use wagmi's `useAccount` to retrieve address instead

chore: remove address prop from Swap component

---

src/swap/components/SwapProvider.tsx

- readd the `error` field on context, and set by the component lifecycle emitters so `SwapMessage` renders
playground

fix: re-add `error` so `SwapMessage` renders

---

src/swap/components/SwapProvider.test.tsx
src/swap/components/SwapProvider.tsx

- if a user rejects a transaction then retries it, the error message stays after the swap succeeds (i.e. error state hasn't been reset)
- clear the errors on `success` state
playground

fix: clear error on success

---

site/docs/pages/transaction/transaction.mdx

Update remove redundant <TransactionStatusAction /> from docs

docs: update remove redundant <TransactionStatusAction /> from docs

---

site/docs/pages/guides/contribution.mdx

Added docs for storybook workflow
`cd site && yarn dev`

chore: add Storybook workflow doc

---

playground/nextjs-app-router/components/demo/Wallet.tsx

- fix the missing import in playground & casing

fix: `WalletDropdownBasename` in playground

---

playground/nextjs-app-router/components/Demo.tsx
playground/nextjs-app-router/tailwind.config.ts
tailwind.config.js

Add light and dark mode in Playground
- Add darkMode: ['class'] and safelist: ['dark'] in our tailwind.config.ts files. This prevents the users personal mac settings from overriding our components styling.

chore: Add light and dark mode in Playground

---

.changeset/olive-monkeys-unite.md
playground/nextjs-app-router/components/demo/Swap.tsx
src/swap/components/SwapAmountInput.test.tsx
src/swap/components/SwapAmountInput.tsx
src/swap/components/SwapButton.test.tsx
src/swap/components/SwapButton.tsx
src/swap/components/SwapMessage.test.tsx
src/swap/components/SwapMessage.tsx
src/swap/components/SwapProvider.test.tsx
src/swap/components/SwapProvider.tsx
src/swap/types.ts
src/swap/utils/getSwapMessage.test.ts
src/swap/utils/getSwapMessage.ts
src/wallet/components/Wallet.tsx
src/wallet/types.ts

- if no wallet connected, prompt user to connect wallet after filling out inputs
https://github.com/user-attachments/assets/fe23c13e-a5c0-4b34-930f-a2ae69b938e1

feat: add connect wallet functionality to Swap component

---

.changeset/tame-islands-unite.md
src/swap/components/SwapAmountInput.tsx
src/swap/components/SwapMessage.tsx

https://github.com/user-attachments/assets/066b4ac7-847e-4b94-a7c8-3ea9f1c4fa7b

chore: Adjust style so Swap component doesn't shift

---

site/docs/pages/farcaster/get-farcaster-user-address.mdx
site/docs/pages/frame/get-frame-html-response.mdx
site/docs/pages/frame/get-frame-message.mdx
site/docs/pages/frame/get-frame-metadata.mdx
site/docs/pages/identity/get-attestations.mdx
site/docs/pages/xmtp/get-xmtp-frame-message.mdx
site/docs/pages/xmtp/is-xmtp-frame-request.mdx

Added backticks to titles where it should be
Example:
Before:
After:

docs: consistent titles

---

.prettierrc
src/frame/utils/getFrameHtmlResponse.ts
src/frame/utils/setFrameHtmlButtons.test.ts
src/frame/utils/setFrameHtmlButtons.ts

* Created `setFrameHtmlButtons` utility and test suite for creating Button Metadata HTML
* Implemented utility in `getFrameHtmlResponse`
* Updated logic for buttons to allow `post` buttons to receive custom `postUrl`s
* 100% test coverage in `setFrameHtmlButtons.test.ts`

Feat: Update getFrameHtmlResponse with new button-utility

---

.changeset/sixty-clocks-shop.md
src/swap/components/SwapSettingsSlippageInput.tsx

chore: Swap Settings Slippage fast follow

---

.changeset/gorgeous-cameras-search.md
src/OnchainKitConfig.ts
src/OnchainKitProvider.test.tsx
src/OnchainKitProvider.tsx
src/identity/components/IdentityProvider.test.tsx
src/index.ts
src/types.ts
src/useCapabilitiesSafe.test.ts
src/useCapabilitiesSafe.ts

- add `useCapabilitiesSafe` hook
- add EIP-5792 capabilities to `OnchainKitProvider` for consumption in child components
unit tests and console logging the capabilities on Playground

feat: EIP-5792 in `OnchainKitProvider`

---

.changeset/great-dolls-kiss.md
playground/nextjs-app-router/components/demo/Swap.tsx
src/wallet/components/WalletDropdownDisconnect.tsx
src/wallet/components/WalletDropdownFundLink.tsx

- fixed hover styling for the `Fund` and `Disconnect` wallet components during the mobile view
- fix playground dark mode styling for the `Swap` component
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

fix: Fund and Disconnect hover styling in mobile

---

.changeset/spotty-ants-burn.md
src/transaction/components/TransactionProvider.test.tsx
src/transaction/components/TransactionProvider.tsx

- use EIP-5792 `walletCapabilities` to determine whether to atomic batch the calls

`Transaction` - use `walletCapabilities` for atomic batching

---

framegear/app/page.tsx
framegear/components/Frame/Frame.tsx
framegear/components/FrameInput/FrameInput.tsx
framegear/contexts/TextInputs.tsx

* Currently, when using Framegear, if there are multiple frames with text input fields, the `inputText` state will persist to the latter frames (ie. if a user inputs "blah" in the first input field, and the next frame has an `input` field, that field will be pre-filled with "blah"
* This PR fixes the issue by enabling Framegear to better handle multiple text inputs
* achieved by creating a `TextInputs` context
* leveraged `useTextInputs` in `FrameInput` and `Frame` to appropriately reset inputText state for various frame changes
* the following frame interactions reset the `inputText` state:
* `FrameInput`'s `fetch` button
* Any `post` or `post_redirect` button clicks in the `Frame` component
locally

Fix: Framegear with Multiple Text Inputs

---

.changeset/cool-walls-dream.md
CHANGELOG.md
site/docs/pages/config/is-ethereum.mdx
site/docs/public/sitemap.xml
site/sidebar.ts
src/isBase.test.ts
src/isBase.ts
src/isEthereum.test.ts
src/isEthereum.ts
src/types.ts

feat: added isMainnetOnly to isBase and isEthereum utilities #1167

---

.changeset/modern-walls-relax.md
src/swap/components/SwapAmountInput.tsx

Added space between swap input and select
| ----- | ---- |
| ![image](https://github.com/user-attachments/assets/8e16f13e-3e03-4ba5-b5af-a406d61334be) | ![image](https://github.com/user-attachments/assets/9469cb2d-df4b-485b-a3d0-a571c1acf2dd) |

fix: add space between swap input and select

---

site/docs/pages/transaction/transaction.mdx
site/vocs.config.tsx

Adding twoslash to the Transactions doc page.  Required swallowing a couple not found errors and adding dependencies, although the final display is unchanged.

docs: implement twoslash on transactions

---

.changeset/modern-walls-relax.md
.changeset/shy-foxes-jog.md
package.json
src/swap/components/Swap.tsx
src/swap/components/SwapProvider.test.tsx
src/swap/components/SwapProvider.tsx
src/swap/types.ts
yarn.lock

feat: introduced `config` for the `Swap` component

---

playground/nextjs-app-router/components/demo/Wallet.tsx
site/docs/pages/index.mdx
site/docs/pages/wallet/wallet-dropdown-link.mdx
site/docs/pages/wallet/wallet.mdx

- link to keys.coinbase.com instead of wallet.coinbase.com

chore: update wallet link to keys.coinbase.com

---

.changeset/shy-foxes-jog.md
src/api/getSwapQuote.test.ts
src/api/getSwapQuote.ts

Adjust slippage for V1 API (aggregator). V1 expects slippage in tenths of a percent (e.g., 30 = 3%). This was implemented when creating the transaction but not when fetching the quote 

chore: Update Swap Slippage v1 API for getting the Swap Quote

---

src/swap/constants.ts
src/swap/utils/getErrorMessage.test.ts
src/swap/utils/getErrorMessage.ts
src/swap/utils/getSwapMessage.test.ts
src/swap/utils/getSwapMessage.ts

extracting SwapMessage to constants to avoid circular dependency
getSwapMessage -> getErrorMessage -> getSwapMessage

fix: remove circular dependency

---

playground/nextjs-app-router/components/demo/Swap.tsx
src/swap/components/SwapButton.test.tsx
src/swap/components/SwapButton.tsx
src/swap/components/SwapMessage.test.tsx
src/swap/components/SwapMessage.tsx
src/swap/components/SwapProvider.test.tsx
src/swap/components/SwapProvider.tsx
src/swap/components/SwapSettingsSlippageInput.test.tsx
src/swap/components/SwapSettingsSlippageInput.tsx
src/swap/types.ts
src/swap/utils/getSwapMessage.test.ts
src/swap/utils/getSwapMessage.ts
src/swap/utils/processSwapTransaction.test.ts
src/swap/utils/processSwapTransaction.ts

* remove context states and use lifecyclestatus as the source of truth
* persist all lifecycle status data (except errors)

fix: update swap lifecyclestatus

---

.changeset/shy-foxes-jog.md
site/docs/pages/swap/types.mdx
src/swap/components/SwapSettingsSlippageInput.test.tsx
src/swap/components/SwapSettingsSlippageInput.tsx
src/swap/types.ts

fix: SwapSlippageInput was visually resetting to default value on error

---

.changeset/nervous-lamps-jog.md
src/swap/components/Swap.tsx

- turn off `v1` aggregator API (0x and 1inch)
- switch on `v2` API by default (Uniswap)

feat: set `v2` as default API for `Swap`

---

src/swap/types.ts
src/swap/utils/sendSingleTransactions.test.ts
src/swap/utils/sendSingleTransactions.ts
src/swap/utils/sendSwapTransactions.test.ts
src/swap/utils/sendSwapTransactions.ts

- add `executeSingleTransactions` (EOA)
- add `executeSwapTransactions` (atomic batch with `useSendCalls`, and single with `executeSingleTransactions`)
these utils will be used for batching all 3 Swap transactions (from ERC-20) for smart wallets
main PR playground - https://github.com/coinbase/onchainkit/pull/1264

feat: add utils for batch Swap transactions

---

.changeset/late-bottles-greet.md
src/swap/components/SwapProvider.tsx
src/swap/components/SwapSettingsSlippageInput.test.tsx
src/swap/components/SwapSettingsSlippageInput.tsx
src/swap/types.ts

Add the Swap Config to the Context.
Update `SwapSettingsSlippageInput` updates:
- Use the config `defaultMaxSlippage` rather than our hardcoded maxSlippage value.
- Remove local slippage state.
- Remove `getMaxSlippage` function. `useCallback` is not providing many performance benefits here. Likely it's even slower than accessing `lifecycleStatus.statusData.maxSlippage` directly.

chore: Update SwapSettingsSlippageInput to use Config

---

src/internal/svg/swapSettings.tsx
src/swap/components/SwapSettings.tsx

Moving SVG sizing to be handled by the parent component.
This fixes a bug where a custom icon would be unrestrained

chore: Update Swap Settings icon styling

---

site/docs/pages/swap/swap-settings.mdx
site/sidebar.ts

Add `SwapSettings` docs covering   `SwapSettings`, `SwapSettingsSlippageDescription`, `SwapSettingsSlippageInput`, and  `SwapSettingsSlippageTitle`.
Examples include general usage, overriding styles, overriding icons, adding text, and updating text!

docs: SwapSettings

---

playground/nextjs-app-router/components/demo/Swap.tsx
src/internal/utils/getToastPosition.test.ts
src/internal/utils/getToastPosition.ts
src/swap/components/Swap.tsx
src/swap/components/SwapProvider.tsx
src/swap/components/SwapToast.test.tsx
src/swap/components/SwapToast.tsx
src/swap/index.ts
src/swap/types.ts

- add `SwapToast` component and display on success

feat: Add SwapToast component

---

src/swap/hooks/useResetInputs.test.ts
src/swap/hooks/useResetInputs.ts

chore: Clear USD values post successful Swap

---

playground/nextjs-app-router/components/Demo.tsx

Add OnchainKit link to Playground

fix: Add OnchainKit link to Playground

---

src/swap/components/SwapProvider.tsx
src/swap/hooks/useLifecycleStatus.test.ts
src/swap/hooks/useLifecycleStatus.ts

Extract lifecycleStatus to a hook, this is a step towards using this hook for all components which will require it to use generic types for LifecycleStatus and LifecycleStatusUpdate.

fix: extract lifecycleStatus to hook

---

site/docs/pages/api/get-swap-quote.mdx
site/docs/pages/swap/types.mdx

docs: Update getSwapQuote API and type SwapQuote

---

site/docs/pages/index.mdx

Update to the Figma example to be interactive - it was previously a static image.

docs: Update the Landing Page Figma example to be interactive

---

src/swap/components/SwapAmountInput.tsx

Update the Swap USD value to NOT render when the qupte value is $0.00

chore: Update Swap USD 0 value render

---

site/docs/components/landing/Tweets.tsx
site/docs/pages/index.mdx

docs: Improve embedded tweet performance

---

site/docs/styles.css

docs: Fix tweet bottom border

---

site/docs/pages/transaction/transaction.mdx

Describe how to pass "calls" to the <Transaction /> component because it currently only demonstrates how to pass "contracts"
This change is documentation-only
Manually viewed it on my local instance of the docs.

Add calls to transaction component docs

---

.changeset/lucky-coats-drop.md
playground/nextjs-app-router/components/AppProvider.tsx
playground/nextjs-app-router/components/Demo.tsx
playground/nextjs-app-router/components/demo/Identity.tsx
playground/nextjs-app-router/components/demo/SwapDefault.tsx
playground/nextjs-app-router/components/form/active-component.tsx
src/swap/components/SwapButton.test.tsx
src/swap/components/SwapButton.tsx
src/swap/components/SwapDefault.test.tsx
src/swap/components/SwapDefault.tsx
src/swap/index.ts
src/swap/types.ts

feat: add SwapDefault component

---

playground/nextjs-app-router/components/AppProvider.tsx
playground/nextjs-app-router/components/Demo.tsx
playground/nextjs-app-router/components/demo/WalletDefault.tsx
playground/nextjs-app-router/components/form/active-component.tsx
src/wallet/components/WalletDefault.test.tsx
src/wallet/components/WalletDefault.tsx
src/wallet/index.ts

feat: add WalletDefault component

---

src/pay/components/PayProvider.tsx
src/swap/components/SwapProvider.test.tsx
src/transaction/utils/isUserRejectedRequestError.test.ts
src/transaction/utils/isUserRejectedRequestError.ts

- user rejected error is now part of `shortMessage` field in viem
tested, local PR deployment of `Transaction` now correctly shows `Request denied.` while https://onchainkit.xyz/playground does not

fix: error messages

---

src/pay/components/PayProvider.tsx

- reset error message and `init` state after funding flow is started

chore: reset state in `Pay` component after `Get USDC` is clicked

---

README.md

Updating the ReadMe team to be active team members so users reach out to the correct people. 
- Our old team members / contributors will still show up in the Contributors section below!
- Add OnchainKit Farcaster

chore: Update ReadMe active team

---

playground/nextjs-app-router/components/demo/Wallet.tsx
src/identity/components/Name.tsx
src/wallet/components/ConnectButton.tsx

Updated border and font weight. 
Updated playground to use text property.
Fix Identity text for all themes.

chore: Connect Wallet and Identity theming clean up 

---

src/pay/components/PayButton.tsx
src/pay/components/PayProvider.test.tsx
src/pay/components/PayProvider.tsx
src/pay/constants.ts
src/pay/hooks/useCommerceContracts.tsx
src/pay/types.ts

- add `fetchingData` and `ready` lifecycle status
- fetch data in `useEffect` for connected wallets
this change is due to a popup blocking issue in Safari iOS
also, adjust the funding link to pre-populate USDC on Base as an asset
playground in other PR

feat: pre-load transaction data in `Pay` for connected wallets

---

create-onchain/templates/next/app/providers.tsx

trivial: prefix api key envar in template with `NEXT_PUBLIC`

---

create-onchain/src/cli.ts

if client key is defined, add `Paymaster` as an integration

trivial: add `Paymaster` as an integration in `create-onchain`

---

src/network/neynar/getCustodyAddressForFidNeynar.test.ts
src/network/neynar/getCustodyAddressForFidNeynar.ts
src/network/neynar/getVerifiedAddressesForFidNeynar.test.ts
src/network/neynar/getVerifiedAddressesForFidNeynar.ts

This PR updates the `getCustodyAddressForFidNeynar` and `getVerifiedAddressesForFidNeynar` functions to use Neynar's V2 endpoints.
The V1 endpoints have been deprecated, and the verification endpoint (`https://api.neynar.com/v1/farcaster/verifications?fid=...`) has stopped returning verification data entirely.
Unit tests

fix: Upgrade to Neynar V2 Endpoints

---

.changeset/flat-forks-whisper.md
src/identity/components/Address.test.tsx
src/identity/components/Address.tsx
src/identity/components/Avatar.test.tsx
src/identity/components/Avatar.tsx
src/identity/components/EthBalance.test.tsx
src/identity/components/EthBalance.tsx
src/identity/components/Name.test.tsx
src/identity/components/Name.tsx

Updating our Identity components to error log and return null when the wallet address is missing when rendering as opposed to throwing the error. 
Throwing an error is disruptive, it's a better user experience to log the problem and just return null than stop the program and show the following screen:

chore: Update missing address error handling

---

.changeset/friendly-baboons-peel.md
src/wallet/components/ConnectWalletText.tsx

Update `ConnectWalletText` component styling to match the `ConnectWallet` text prop formatting.

fix: Update ConnectWalletText styling

---

site/docs/pages/guides/tailwind.mdx
site/sidebar.ts

This PR fixes a few instances of "Tailwind CSS" spelling to match [Tailwind's](https://tailwindcss.com/) own spelling. 

docs: fix Tailwind CSS spelling

---

.changeset/mighty-kings-knock.md
playground/nextjs-app-router/components/AppProvider.tsx
playground/nextjs-app-router/components/demo/Transaction.tsx
playground/nextjs-app-router/components/form/transaction-options.tsx
playground/nextjs-app-router/onchainkit/package.json
src/transaction/components/Transaction.tsx
src/transaction/components/TransactionButton.tsx
src/transaction/components/TransactionProvider.test.tsx
src/transaction/components/TransactionProvider.tsx
src/transaction/hooks/useGetTransactionStatusLabel.test.tsx
src/transaction/hooks/useGetTransactionStatusLabel.tsx
src/transaction/hooks/useGetTransactionToastLabel.test.tsx
src/transaction/hooks/useGetTransactionToastLabel.tsx
src/transaction/hooks/useSendWalletTransactions.test.tsx
src/transaction/hooks/useSendWalletTransactions.tsx
src/transaction/types.ts
src/transaction/utils/isSpinnerDisplayed.test.ts
src/transaction/utils/isSpinnerDisplayed.ts

* Add ability to pass a promise into the transaction component that resolves to calls or contracts
* Added new building transaction status
* Added new onError state when promise is rejected

feat: add promises to transactions and calls

---

site/docs/pages/pay/pay.mdx

docs: add handling successful checkout to `Pay` docs

---

.changeset/weak-coats-fetch.md
src/checkout/components/CheckoutProvider.test.tsx
src/checkout/components/CheckoutProvider.tsx

- was not passing in the proper paymaster field for `capabilities` previously
cherry picked to https://github.com/coinbase/onchainkit/pull/1428 and tested locally

fix: `isSponsored` in `Checkout` component

---

.changeset/few-files-attack.md
src/checkout/components/CheckoutProvider.test.tsx
src/checkout/components/CheckoutProvider.tsx

- add a USDC fill amount to Checkout funding flow
cherry picked to https://github.com/coinbase/onchainkit/pull/1428 and tested locally

feat: add `presetCryptoAmount` param to `Checkout`

---

site/docs/pages/getting-started.mdx

docs: add different package manager installations to `Getting Started`

---

src/internal/svg/baseSvg.tsx
src/internal/svg/defaultNFTSvg.tsx
src/nft/components/view/NFTAudio.test.tsx
src/nft/components/view/NFTAudio.tsx
src/nft/components/view/NFTImage.test.tsx
src/nft/components/view/NFTImage.tsx
src/nft/components/view/NFTLastSoldPrice.test.tsx
src/nft/components/view/NFTLastSoldPrice.tsx
src/nft/components/view/NFTMedia.test.tsx
src/nft/components/view/NFTMedia.tsx
src/nft/components/view/NFTMintDate.test.tsx
src/nft/components/view/NFTMintDate.tsx
src/nft/components/view/NFTNetwork.test.tsx
src/nft/components/view/NFTNetwork.tsx
src/nft/components/view/NFTOwner.test.tsx
src/nft/components/view/NFTOwner.tsx
src/nft/components/view/NFTTitle.test.tsx
src/nft/components/view/NFTTitle.tsx
src/nft/components/view/NFTVideo.test.tsx
src/nft/components/view/NFTVideo.tsx
src/nft/components/view/index.ts
src/nft/types.ts
src/styles/index.css
src/styles/theme.ts
vitest.config.ts

feat: add view components

---

site/docs/components/landing/ComponentPreview.tsx
site/docs/components/landing/SwapDemo.tsx
site/docs/components/landing/Tweets.tsx

- `ComponentPreview`: Implemented fixed width and adjust how the content overflow for responsiveness.
- `SwapDemo`: Assigned width for breakpoints for responsiveness
- `Tweets`: Adjusted the width of the cards for responsiveness
Acceptance criteria
- Used magic numbers as a fix because using w-full didn't work. In our next improvement, will find a more elegant way to address this. 
- Some code blocks are indented weirdly and should be addressed with syntax highlighting as a fast follow.
- @alissacrane-cb could we follow up on this and replacing the checkout button with a fake button that triggers a modal like what we have on the template? 
**How to test**
- git clone https://github.com/mindapivessa/onchainkit.git
- Switch to …

fix responsiveness on the new landing page

---

site/docs/components/landing/Tweets.tsx
site/docs/styles.css

New middle tweet. 
Tweak sizing. 

chore: Update Tweet on Landing Page

---

.changeset/real-dolphins-drive.md
src/transaction/components/Transaction.tsx
src/transaction/components/TransactionButton.test.tsx
src/transaction/components/TransactionButton.tsx
src/transaction/components/TransactionProvider.tsx
src/transaction/types.ts
src/transaction/utils/isSpinnerDisplayed.test.ts
src/transaction/utils/isSpinnerDisplayed.ts

feat: add custom error and success states to txn button

---

site/docs/components/landing/ComponentPreview.tsx

- Fixed the overflow + scroll behaviors for the code snippets
Before
After
- Check for all components
- Checked that it doesn't impact mobile responsiveness

fix transaction demo code overflow

---

.changeset/real-dolphins-drive.md
src/OnchainKitProvider.tsx
src/checkout/components/CheckoutProvider.test.tsx
src/checkout/components/CheckoutProvider.tsx

- reset `errorMessage` on subsequent button press
playground

fix: clear error message in `CheckoutStatus` if a request is denied

---

site/docs/pages/wallet/types.mdx
src/wallet/types.ts

Type for `ConnectWalletReact` in docs was missing the `withWalletAggregator` property.

docs: add missing `ConnectWalletReact` prop to types page

---

src/wallet/components/WalletDropdownBasename.test.tsx
src/wallet/components/WalletDropdownBasename.tsx

`WalletDropdownBasename` should only use `base` as chain, otherwise it will try to redirect L1 ENS name: https://linear.app/coinbase/issue/BAPP-670/%5Bbug%5D-broken-profile-link-that-appends-ethbaseeth

Fix: Enforce base as chain for name resolution

---

playground/nextjs-app-router/components/Demo.tsx

- Playground sidebar collapses on smaller screens (and sometimes on larger screens) because the class we're using, `min-w-120` does not actually exist. This PR updates that class to a a css class that _does_ exist.
- Remove unnecessary arbitrary Tailwind classes in favor of built in values
Before:
After:
- I've also switched to using the `cn` utility function that was already defined in the playground utils dir. This will improve readability and performance.

fix: fix minimum playground sidebar width

---

site/docs/pages/identity/identity-card.mdx
site/docs/pages/identity/socials.mdx
site/package.json
site/sidebar.ts
site/yarn.lock

`identity/identity-card`:
`identity/socials`:
[IdentityCard and Socials components](https://github.com/coinbase/onchainkit/pull/1489#top)

docs: IdentityCard and Socials components

---

playground/nextjs-app-router/components/DemoOptions.tsx

Moved the "Component" option above options for Component Mode and Component Theme to match natural flow
Before:
After:

chore: reorder sidebar elements in playground

---

src/nft/components/view/NFTNetwork.test.tsx
src/nft/components/view/NFTNetwork.tsx

Update NFT Network component to use wagmi's useChainId instead of getting chain off useAccount so Network still displays when no wallet is connected.
useChainId returns the last configured chainId when there is no active connection instead of undefined.

fix: nft network

---

src/nft/components/mint/NFTAssetCost.tsx
src/nft/components/view/NFTLastSoldPrice.test.tsx
src/nft/components/view/NFTLastSoldPrice.tsx

Updating default Mint Price label to Last sale price to reflect the actual data.  Mint price was only valid if the NFT has not been resold.
| ------ | ------- |
| ![image](https://github.com/user-attachments/assets/20ff91b7-01d1-45c0-bf86-560e0039e15c) | ![image](https://github.com/user-attachments/assets/0684dac7-d877-4de7-9c67-3c12b36595f2) |

fix: update last sold price

---

create-onchain/templates/next/package.json

This PR adds `viem` and `wagmi` to the CLI starter template's `package.json`. This will allow auto-importing to work correctly, plus most devs will likely need to use both packages in their onchain app directly at some point anyway.

chore: add `viem` and `wagmi` as dependencies to `create-onchain` starter

---

src/api/index.ts
src/api/types.ts

Expose the NFT api's
* getTokenDetails
* getMintDetails
* buildMintTransaction

fix: export nft apis

---

create-onchain/src/cli.ts
create-onchain/templates/next/.yarnrc.yml
create-onchain/templates/next/package.json

Our CLI starter currently builds fine with `bun` and `npm`, but has errors when building with `yarn` and `pnpm` (after installing deps) due to the way that `pnpm` and `yarn` handle peer dependencies. This PR adds necessary peer dependencies to `package.json` so that devs won't have errors on their first build with `pnpm` and `yarn`
Ran multiple installations from CLI with bun, yarn, pnpm, and npm

fix: fix CLI builds for yarn and pnpm

---

.changeset/quick-fans-tease.md
src/OnchainKitProvider.test.tsx
src/OnchainKitProvider.tsx
src/identity/constants.ts

Default to use the `COINBASE_VERIFIED_ACCOUNT_SCHEMA_ID` in the `OnchainKitProvider` when the `schemaID` is missing. This is to prevent the `DisplayBadge` component from throwing an error. 

chore: Update OnchainKitProvider to fallback to CB verified schemaId

---

.changeset/clever-days-compete.md
src/nft/components/view/NFTImage.test.tsx
src/nft/components/view/NFTImage.tsx
src/nft/components/view/NFTVideo.tsx
src/styles/theme.ts

* updated text1 style to 2xl (collection title)
* updated media to use grid vs. absolute positioning to render loading image
Test NFTs
Video (wide): 0x1f52841279fA4dE8B606a70373E9c84e84Ce9204
Video (square): 0xFE12c6d7555B4A94B352998f8e1E96aDFbE628e9
Image (tall): 0xc6A1F929B7cA5D76e0fA21EB44da1E48765990C5
Image (slightly wider than tall): 0x6d65115def07d25841891d0679189f2c42032f48
Mobile Video Card
| ------- | ------ |
| ![image](https://github.com/user-attachments/assets/bcc86500-f30a-4582-b949-c049527297c5) | ![image](https://github.com/user-attachments/assets/6176e940-5728-4d05-b7d9-f392d74bb822) |
Mobile Video Mint Card
| ------- | ------ |
| ![image](https://github.com/user-attachments/assets/6481db47-8d71-4b85-a78c-a09fb89 …

fix: nft responsiveness

---

site/docs/components/NFTComponents.tsx
site/docs/pages/mint/nft-card.mdx
site/docs/pages/mint/nft-mint-card.mdx

* Update docs for `NFTCard` and `NFTMintCard` with information about NFTCardDefault and NFTMintCardDefault implementations.
* Update mock data for Mint NFT with higher quantity so quantity selector shows in example
| NFT Card | Mint Card | Mint Demo NFT |
| --------- | -------- | --------| 
| ![image](https://github.com/user-attachments/assets/806d566d-e26c-4e7e-94c0-0ab28a2ebc11) | ![image](https://github.com/user-attachments/assets/5c4d8d88-0200-4800-b89b-befd40967589) | ![image](https://github.com/user-attachments/assets/0895fded-0ab8-4516-b7af-3856ecf52abb) |

docs: add NFTCardDefault and NFTMintCardDefault

---

site/docs/pages/installation/nextjs.mdx

Adding 'use client' directive to the providers file in order to prevent server component errors in Next 14+

docs: add 'use client' directive to Providers to prevent error

---

site/docs/components/StartBuilding.tsx
site/docs/components/landing/LandingFooter.tsx

**What changed and why?**
- Fixed a typo in `StartBuilding.tsx` (replaced "yoru" with "your").
- Removed an extra `className=` in `LandingFooter.tsx`.

fix: fix className and typo in components

---

site/vocs.config.tsx

In previews, docs site sidebar links are pointed at `https://onchainkit.xyz/...`. This PR makes use of Vercel environment variables to update the `baseUrl` correctly in preview environments.

fix: fix base URL in docs sidebar links

---

site/docs/pages/config/onchainkit-provider.mdx

* update docs for chain config 

fix: update chain type

---

.github/workflows/cli.yml
create-onchain/templates/next/package.json

Our CLI template has mismatching versions of `viem` and `wagmi` from `onchainkit`, causing type errors and the build to fail. This PR updates the template's `package.json` to have versions of `viem` and `wagmi` that match `onchainkit`'s.
- Also adds CI check that builds package, runs it, installs deps, and builds the project with npm

fix: fix CLI's `npm` build

---

.changeset/config.json

In the release process, our changelog is malformatted. This PR updates our `.changeset/config.json` to use the proper formatter. This will make it easier to read changelogs on our [Releases page](https://github.com/coinbase/onchainkit/releases) and anywhere else they appear, plus it will make the release process easier.
Before:
After this PR, each change will be formatted on separate lines.
- Created mock changeset`.md` file resembling one that happens during our releases
- Ran `bun: release version`, output is as expected.

fix: fix changelog formatting

---

playground/nextjs-app-router/components/Demo.tsx

Logic for determining active component and rendering said component is clunky. This PR moves the architecture to a mapping of components and removes the `renderActiveComponent` function for improved readability.

refactor: refactor active component logic in playground

---

site/docs/pages/mint/nft-mint-card.mdx

Added compatibility section to NFT Mint card, pointing users to reservoir platform support docs

docs: add compatibility to nft mint card

---

playground/nextjs-app-router/components/Demo.tsx
playground/nextjs-app-router/components/DemoOptions.tsx
playground/nextjs-app-router/components/form/checkout-options.tsx
playground/nextjs-app-router/components/form/transaction-options.tsx

This PR refactors the `DemoOptions` component away from a switch/case and to a mapping pattern. I think this is appropriate for 2 reasons:
1. Mapping is easier to read and maintain without stepping through nested logic.
2. (more importantly) it will enable the next playground feature, the ability to copy "share links". This requires us to know _which options_ are associated with _which components_, and this is much easier to do with an accessible mapping available.

refactor: refactor `DemoOptions` component

---

site/docs/components/landing/CheckoutDemo.tsx
site/docs/components/landing/ComponentPreview.tsx
site/docs/components/landing/FundDemo.tsx
site/docs/components/landing/IdentityDemo.tsx
site/docs/components/landing/NftMintCardDemo.tsx
site/docs/components/landing/SwapDemo.tsx
site/docs/components/landing/TransactionDemo.tsx
site/docs/components/landing/WalletDemo.tsx

* fixed spacing on homepage code snippets
fix:
current:
locally

fix code snippet spacing

---

site/docs/pages/swap/swap.mdx
site/docs/pages/transaction/transaction.mdx
site/docs/pages/wallet/wallet.mdx

- add appropriate imports and simplify code so it's actually copy pastable
<table>
<tr>
<th>After</th>
</tr>
<tr>
<td><img width="737" alt="image" src="https://github.com/user-attachments/assets/a3ed82d4-8be8-478e-8e5c-2d81a042def7"></td>
<td><img width="737" alt="image" src="https://github.com/user-attachments/assets/da4a376d-b28a-45a2-8886-dffd42ced5de"></td>
</tr>
<tr>
<td><img width="737" alt="image" src="https://github.com/user-attachments/assets/d1267ca2-a7fa-4b45-9d2a-4e8ec0df851e"></td>
<td><img width="737" alt="image" src="https://github.com/user-attachments/assets/1a951938-495f-443e-8199-e750330e8414"></td>
</tr>
<tr>
<td><img width="737" alt="image" src="https://github.com/user-attachments/assets/25e8f20a-6878-41ec-a25f-88d045c99f81"></td> …

docs: fix imports for default components

---

.github/workflows/cli.yml

title
no CLI workflow ran on this PR

chore: only run CLI github workflow on changes to `create-onchain` directory

---

playground/nextjs-app-router/components/Demo.tsx
playground/nextjs-app-router/lib/url-params.ts

Because our playground app is hosted at /playground, our logic for sharing links wasn't correct. This adds a `pathname` part to the URL so linking works as expected.

fix: fix playground share link in production

---

site/docs/pages/identity/identity-card.mdx

docs: Fix IdentityCard code sample

---

site/docs/pages/config/supplemental-providers.mdx
site/docs/pages/installation/astro.mdx
site/docs/pages/installation/nextjs.mdx
site/docs/pages/installation/remix.mdx
site/docs/pages/installation/vite.mdx

* updated installation guides based on new recommended provider configuration
* created `/config/supplemental-providers` to illustrate how to create custom Wagmi and QueryClient providers
Updated Installation Guides:
* Next.js
* Vite
* Remix
* Astro
locally

chore: update installation provider docs

---

create-onchain/templates/next/app/providers.tsx

Update to remove other providers to keep the providers clean.

chore: remove providers from cli template

---

playground/nextjs-app-router/onchainkit/package.json
playground/nextjs-app-router/package.json
tsup.config.ts

Dev server hot reloading has stopped working reliably; switching to bun linking and moving output to ./onchainkit in the playground dir to fix
This only affects internal dev experience.
Locally

dev: fix playground dev server

---

site/docs/pages/guides/themes.mdx
src/identity/components/IdentityCard.tsx
src/styles/index.css
src/styles/theme.ts
src/swap/components/SwapSettingsSlippageLayout.tsx
src/token/components/TokenSelectButton.tsx
src/wallet/components/WalletModal.tsx

* added classes for border styles
* preserved backwards compatibility: `ock-border-default` and `ock-border-default-active` unchanged
* adds `ock-border-line-default`, `ock-border-line-primary`, `ock-border-line-heavy`, and `ock-border-line-inverse`
locally

feat: added custom border classes

---

.changeset/config.json
package.json
yarn.lock

After some testing, uncovered the reason for our changelogs being all on one line. Reverted to our old change log format in `config.json` as that wasn't the root cause
When generating changesets, please format like this:
```
- **feat**: commit message here. By @dschlabach #XXXX
```
Note: the following formatting causes improper formatting of our changelog.md (note the no space between "-" and "*")
```
-**feat**: commit message here. By @dschlabach #XXXX
```

fix: fix changelog generation

---

src/identity/components/Socials.test.tsx
src/identity/utils/getSocialPlatformDetails.test.tsx
src/identity/utils/getSocialPlatformDetails.tsx

This bug comes from when setting your Social URL in [base.org](http://base.org/), there is no enforcement on how to enter your profile. One user could have their entire Farcaster url hardcoded where another user could only have his Farcaster name.
I've updated how we process the Farcaster URLs to be more flexible. 

chore: Improve <Socials /> Farcaster URL processing 

---

site/docs/pages/checkout/checkout.mdx

docs: `Checkout` polish

---

.changeset/cold-clocks-sip.md
src/checkout/components/CheckoutButton.test.tsx
src/checkout/components/CheckoutButton.tsx
src/checkout/components/CheckoutProvider.test.tsx
src/checkout/components/CheckoutProvider.tsx
src/checkout/constants.ts

- do not render `Get USDC` if insufficient funds
- instead, have original initial click bring user to keys.coinbase.com/fund
- open funding link in popup instead of new tab
unit tests and playground

feat: improved funding flow in Checkout

---

site/docs/pages/token/token-image.mdx

This pull request corrects a grammatical error in the `token-image.mdx` file, changing "with an url" to "with a url" to follow proper grammar rules. This update ensures the correct article "a" is used before a consonant sound.
- Fixed the usage of "an" to "a" in the context of "url."
**Notes to reviewers:**
- The change is grammatical and has no functional impact.
- Review of the file to confirm the fix.

fix: fix typo in token-image.mdx

---

site/docs/pages/fund/types.mdx

The word "avaialable" should be spelled as "available". 
Corrected.

fix: typos in documentation files

---

site/docs/pages/wallet/wallet.mdx

<table>
<tr>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

docs: Update WalletModal image size

---

site/docs/pages/fund/types.mdx

This change fixes a grammatical error in the text output, where "create" was incorrectly used instead of "created."
The adjustment ensures the text is grammatically correct and aligns with proper English usage.  
A small but important improvement to maintain clarity and professionalism in messaging.

docs: correct grammar issue in text output Update types.mdx

---

src/internal/components/Draggable.test.tsx
src/internal/components/Draggable.tsx
src/styles/constants.ts

* created internal Draggable component
* configurable grid size enables snapping behavior
* handles touch and mouse events
vitest, and locally

Feat: Draggable

---

site/docs/pages/fund/types.mdx

I made some small corrections to the documentation to improve clarity and accuracy:
1. The phrase "A optional prop" was changed to "An optional prop" to follow the correct usage of the article. Since "optional" starts with a vowel sound, it should be preceded by "an" instead of "a."
2. The phrase "The addresses that the customer's funds should be delivered to" was adjusted to "The address that the customer's funds should be delivered to" to reflect proper grammar. Although multiple addresses might be implied, it's more grammatically appropriate to use the singular "address" in this context.
These changes should help ensure that the documentation is more grammatically correct and easier to understand.

docs: fix minor grammar issues

---

CHANGELOG.md

This pull request addresses the following spelling errors:
experinece - experience
addeded - added 
I hope my corrections will be helpful and contribute to improving your work. Thank you for your dedication and effort.

fix: correct spelling and grammar mistakes in changelog

---

.changeset/slow-bats-obey.md
site/docs/components/AppDemo.tsx
site/docs/components/landing/SwapDemo.tsx
site/docs/components/landing/WalletDemo.tsx

Create new demo app provider which includes our auto logged in demo wallet. This is to achieve a "logged in" state for our components on the landing page, allowing users to see the intended components rather than a bunch of Connect Wallet buttons. 
For now, we are only auto logging in for the Wallet and Swap component. The Fund and Transaction component would have to be set to disabled. We've decided that it's better to leave these and allow the user to connect their own wallet to test out the functionality. 

docs: Enable auto logged in components on landing page

---

playground/README.md

While reviewing the documentation, I noticed a small typo in the "Getting Started" section. The word "Intall" was misspelled and has been corrected to "**Install**."

dev: fix typo in playground README.md

---

tailwind.config.js

We're getting an error breaking playground styling with the addition of `require('tailwindcss-animate')` in our Tailwind plugins. 
This switches import statement to ESModules to fix the config.

fix: fix Tailwind config

---

site/docs/pages/guides/build-onchain-apps.mdx

WalletConnect has been deprecated. 

docs: Remove WalletConnect reference

---

src/buy/components/BuyDropdown.test.tsx
src/buy/components/BuyDropdown.tsx
src/buy/components/BuyOnrampItem.test.tsx
src/buy/components/BuyOnrampItem.tsx
src/buy/utils/isApplePaySupported.test.ts
src/buy/utils/isApplePaySupported.ts

- show message when amount less than $5 (onramp has minimum)
- hide apple pay option on non mobile device

chore: add onramp message and disable apple pay on desktop

---

src/core/api/buildMintTransaction.ts
src/core/network/getRPCUrl.ts

This pull request addresses minor typographical errors in the following files:
- In `buildMintTransaction.ts`, changed "mint a nft" to "mint an nft" for proper article usage.
- In `getRPCUrl.ts`, corrected the article "a" to "an" before "RPC" to follow grammar rules for words starting with a vowel sound.
- The article "a" was replaced with "an" in both files to ensure correct grammar and improve readability.
- This is a straightforward typo fix with no functional impact.
- Changes have been reviewed manually for accuracy. No tests are required for this minor correction.

fix: fix typos

---

site/docs/pages/wallet/is-valid-aa-entrypoint.mdx

This change addresses a small typo in the type name `isValidAAEntrypointtOptions`. The extra `t` at the end has been removed, and the correct name is now `isValidAAEntrypointOptions`.  
- Updated all occurrences of `isValidAAEntrypointtOptions` to `isValidAAEntrypointOptions`.
- Adjusted references in related files to match the corrected name.
This fix ensures better readability and consistency in the codebase.

docs: fix broken link in `is-valid-aa-entrypoint.mdx`

---

src/internal/components/TextInput.test.tsx
src/internal/components/TextInput.tsx

Add inputMode passthrough to the TextInput component to allow triggering numeric keyboard on mobile devices

feat: add type

---

site/docs/pages/checkout/checkout.mdx
site/docs/pages/guides/use-basename-in-onchain-app.mdx

Fixed incorrect link path for getAvatar function documentation from `/identity/get-name` to `/identity/get-avatar` to ensure users are directed to the correct documentation page.

 fix: fix incorrect documentation link for `getAvatar` function

---

.changeset/eight-buttons-walk.md
src/wallet/components/WalletModal.tsx

Pass through appLogo and appName to cb smart wallet from wallet modal
fixes: https://github.com/coinbase/onchainkit/issues/1789
| ------ | ------ |
| ![image](https://github.com/user-attachments/assets/13484a2a-da7e-4258-8cc4-062400a286f1) | ![image](https://github.com/user-attachments/assets/32bae768-5739-4aa9-a992-6f7f648d5ba4) |

fix: pass though logo and name to cb wallet

---

packemon.config.ts
src/buy/components/Buy.tsx
src/checkout/components/Checkout.tsx
src/checkout/components/CheckoutButton.tsx
src/checkout/components/CheckoutStatus.tsx
src/core-react/OnchainKitProvider.tsx
src/fund/components/FundButton.tsx
src/fund/index.ts

Continuing #1771 with support for `Buy` and `OnchainkitProvider`
- Consumers will still need to set a client boundary manually with `OnchainkitProvider` because of the way that the `chain` prop from `viem` is handled.
- Only setting directive on `Buy` since it's the only exported Buy component (no subcomponents)
- Locally with Next 15 and Vite

fix: set client boundary in `Buy`, `Checkout`, `Fund`, and `OnchainkitProvider`

---

site/docs/components/landing/ComponentPreview.tsx

Identity Card copy on the left back to Identity to remain consistent with the other previews. 

docs: Update Identity landing page preview

---

playground/nextjs-app-router/onchainkit/package.json
src/wallet/components/ConnectWallet.tsx

* duplicated connect modal state in ConnectWallet
* fixes issue where ConnectWallet not always wrapped in WalletProvider. in these cases, modal is unable to be displayed because the handlers come from context
* by adding state local to this component, we can use it in a disconnected state without wrapping in a a WalletProvider
locally

fix: modal state local to connect wallet

---

src/wallet/components/WalletAdvanced.tsx
src/wallet/components/WalletAdvancedAddressDetails.tsx
src/wallet/components/WalletAdvancedDefault.tsx
src/wallet/components/WalletAdvancedQrReceive.tsx
src/wallet/components/WalletAdvancedSwap.tsx
src/wallet/components/WalletAdvancedTokenHoldings.tsx

fix: add client boundaries for `WalletAdvanced*` components

---

.changeset/dull-shirts-confess.md
src/internal/primitives/Dialog.test.tsx
src/internal/primitives/Dialog.tsx
src/internal/primitives/DismissableLayer.test.tsx
src/internal/primitives/DismissableLayer.tsx
src/internal/primitives/FocusTrap.test.tsx
src/internal/primitives/FocusTrap.tsx
src/wallet/components/ConnectWallet.test.tsx
src/wallet/components/ConnectWallet.tsx
src/wallet/components/WalletModal.test.tsx
src/wallet/components/WalletModal.tsx

Introduces new UI primitive components - `FocusTrap`, `DismissableLayer`, and `Dialog`.
`FocusTrap`:
- Ensures keyboard focus remains within a contained area for accessibility
`DismissableLayer`:
- Handles dismissal using outside clicks and escape key events
`Dialog`:
* Portaling to document.body
* Focus management (trapping focus within dialog)
* Click outside and escape key dismissal
* Proper ARIA attributes for accessibility
Design Principles: 
- Limited styling 
- ARIA Accessibility built in
- Optional props by default 
- Stand-alone primitive components
Updated `WalletModal` to use the primitives for:
- Proper modal dialog behavior with ARIA attributes
- Focus trapping for keyboard navigation
- Click outside and escape key dismissal
- Portal-based rendering …

feat: Add UI Primitives - FocusTrap, DismissableLayer, and Dialog. 

---

site/sidebar.ts

Initially under `Guides` we found that the Troubleshooting section was difficult to find. The `Introduction` section seems more appropriate. 

docs: Move Troubleshooting section to the Introduction

---

.changeset/perfect-knives-draw.md
src/core-react/nft/hooks/useMintDetails.ts
src/core-react/nft/hooks/useTokenDetails.ts
src/core-react/nft/types.ts
src/ui/react/nft/index.ts

Export nft hooks for useTokenDetails and useMintDetails, passthrough react-query options.

feat: export nft hooks

---

src/identity/hooks/useAddress.ts
src/identity/hooks/useAvatar.ts
src/identity/hooks/useName.ts
src/identity/hooks/useSocials.tsx

We are defining unnecessary strings as `actionKey` and using that for our `queryKey`. We don't need to do this, Tanstack takes care of this under the hood by default.

fix: remove unnecessary `actionKey`s in `useQuery`

---

src/earn/utils/buildDepositToMorphoTx.test.ts
src/earn/utils/buildDepositToMorphoTx.ts
src/earn/utils/buildWithdrawFromMorphoTx.test.ts
src/earn/utils/buildWithdrawFromMorphoTx.ts

fix: add typesafety to morpho build functions

---

src/api/buildSwapTransaction.test.ts
src/api/buildSwapTransaction.ts
src/api/getSwapQuote.test.ts
src/api/getSwapQuote.ts
src/api/types.ts
src/buy/components/BuyAmountInput.tsx
src/buy/components/BuyProvider.test.tsx
src/buy/components/BuyProvider.tsx
src/buy/utils/getBuyQuote.test.ts
src/buy/utils/getBuyQuote.ts
src/swap/constants.ts

* Added error if amountReference: 'to' is used with the useAggregator: true param
* Updated Buy component to use amountReference: 'from' (default value) for quotes
* Update Buy component input to show numeric keyboard on mobile devices
* Fixed AmountReference type

fix: deprecate v1 swap amountReference to

---

.changeset/many-glasses-visit.md
src/internal/primitives/DismissableLayer.test.tsx
src/internal/primitives/DismissableLayer.tsx
src/internal/primitives/FocusTrap.tsx
src/internal/primitives/Popover.test.tsx
src/internal/primitives/Popover.tsx
src/swap/components/SwapSettings.test.tsx
src/swap/components/SwapSettings.tsx

Implement `Popover`, `DismissableLayer`, and `FocusTrap` primitives in the `SwapSettings` component. 
Tested SwapSettings (mobile and desktop view) and WalletModal in the playground.

feat: Implement Popover, DismissableLayer, and FocusTrap primitives in SwapSettings

---

src/earn/components/DepositAmountInput.test.tsx
src/earn/components/DepositAmountInput.tsx
src/earn/components/EarnAmountInput.test.tsx
src/earn/components/EarnAmountInput.tsx
src/earn/components/EarnProvider.tsx
src/earn/components/WithdrawAmountInput.test.tsx
src/earn/components/WithdrawAmountInput.tsx
src/earn/types.ts

- add `EarnAmountInput` and wrappers for `Earn` component
```
<WithdrawAmountInput />
<DepositAmountInput />
```

feat: add Earn amount inputs

---

.changeset/friendly-cougars-fly.md
src/OnchainKitProvider.test.tsx
src/OnchainKitProvider.tsx
src/core-react/internal/hooks/useAnalytics.test.ts
src/core-react/internal/hooks/useAnalytics.ts
src/core/OnchainKitConfig.ts
src/core/network/constants.ts
src/core/network/sendAnalytics.test.ts
src/core/network/sendAnalytics.ts
src/core/types.ts
src/internal/types.ts
src/types.ts

- add `interactionId` on every `OnchainKitProvider` render (user session)
- add `analyticsURL` as a `config` parameter on `OnchainKitProvider` (users can override where analytics are sent)
- add `useAnalytics` hook
- add `sendAnalytics` API
locally

feat: Client Analytics

---

src/earn/components/DepositBalance.test.tsx
src/earn/components/DepositBalance.tsx
src/earn/components/EarnBalance.test.tsx
src/earn/components/EarnBalance.tsx
src/earn/components/EarnProvider.test.tsx
src/earn/components/EarnProvider.tsx
src/earn/components/WithdrawBalance.test.tsx
src/earn/components/WithdrawBalance.tsx
src/earn/types.ts

feat: add earn balance cards

---

src/api/getPortfolios.test.ts
src/api/getPortfolios.ts
src/api/index.ts
src/api/types.ts
src/wallet/components/WalletAdvancedProvider.test.tsx
src/wallet/components/WalletAdvancedProvider.tsx
src/wallet/hooks/usePortfolio.test.tsx
src/wallet/hooks/usePortfolio.ts
src/wallet/types.ts

* updated endpoint name to `getPortfolios` for clarity and accuracy
* exported `getPortfolios` in `src/api`
* updated hook name to `usePortfolio` for clarity and accuracy
* updated response type to conform to convention

chore: export `getPortfolios`

---

create-onchain/templates/next/README.md

Hi! In this PR, I fixed a broken link in the `README.md`. The link to the OnchainKit documentation now points to the correct URL (`https://onchainkit.xyz/getting-started`).
The old link was no longer working, which could confuse users. This fix ensures access to the correct and up-to-date documentation.

fix: update broken link docs README.md

---

src/earn/components/DepositBalance.test.tsx
src/earn/components/DepositButton.test.tsx
src/earn/components/DepositButton.tsx
src/earn/components/DepositDetails.test.tsx
src/earn/components/DepositDetails.tsx
src/earn/components/Earn.test.tsx
src/earn/components/Earn.tsx
src/earn/components/EarnAmountInput.tsx
src/earn/components/EarnCard.test.tsx
src/earn/components/EarnCard.tsx
src/earn/components/EarnDeposit.test.tsx
src/earn/components/EarnDeposit.tsx
src/earn/components/EarnDetails.test.tsx
src/earn/components/EarnDetails.tsx
src/earn/components/EarnProvider.tsx
src/earn/components/EarnWithdraw.test.tsx
src/earn/components/EarnWithdraw.tsx
src/earn/components/WithdrawBalance.test.tsx
src/earn/components/WithdrawButton.test.tsx
src/earn/components/WithdrawButton.tsx
src/earn/components/WithdrawDetails.test.tsx
src/earn/components/WithdrawDetails.tsx
src/earn/types.ts
src/internal/components/tabs/Tabs.tsx
src/internal/index.ts

- `WithdrawCard` / `DepositCard` -> wrappers for `EarnCard`
- `WithdrawDetails` / `DepositDetails` -> wrappers for `EarnDetails`
- `Earn`
- `WithdrawButton` / `DepositButton` -> wrappers of `Transaction`

feat: add additional Earn components

---

src/api/buildSendTransaction.test.ts
src/api/buildSendTransaction.ts
src/api/types.ts
src/internal/hooks/useSendTransaction.test.tsx
src/internal/hooks/useSendTransaction.tsx
src/wallet/utils/validateAddressInput.test.ts
src/wallet/utils/validateAddressInput.ts

* added `buildSendTransaction` API endpoint
* added `useSendTransaction` hook
* added `validateAddressInput` wallet util

feat: more send utilities

---

.changeset/tough-points-love.md
package.json
tsup.config.ts
yarn.lock

Alias resolution in type files is not handled by tsc, adding tscpaths and an extra build step to handle these.

chore: fix aliases type resolution

---

site/docs/pages/hooks/use-mint-details.mdx
site/docs/pages/hooks/use-token-details.mdx
site/sidebar.ts

Added Mint hooks under utilities section
| sidebar | token details | mint details |
| ------- | ------- | ------ |
| ![image](https://github.com/user-attachments/assets/e773b93b-5268-4a83-82c0-0953404f83aa) | ![image](https://github.com/user-attachments/assets/e3f2a70b-3184-4f91-bb4c-8a58a1b90397) | ![image](https://github.com/user-attachments/assets/67bf9497-d04e-4ce6-9b87-02599e2a69e6) |

docs: nft hooks docs

---

site/docs/pages/wallet/types.mdx

The `withWalletAggregator` prop has been deprecated. Updating old documentation. 

docs: Remove deprecated withWalletAggregator prop

---

src/fund/components/FundButton.tsx
src/fund/hooks/useFundCardFundingUrl.ts
src/fund/hooks/useGetFundingUrl.test.ts
src/fund/hooks/useGetFundingUrl.ts
src/fund/types.ts
src/fund/utils/getOnrampBuyUrl.ts
src/wallet/components/WalletDropdownFundLink.tsx

Currently when calling onramp url from the OCK we don't know what component is making the request. 
Adding component name to the sdkVersion
**BEFORE**
`sdkVersion: "onchainkit@0.36.9"`
**AFTER**
`sdkVersion: "onchainkit@0.36.9:FundCard"`

feat: Add onramp component level tracking param

---

src/transaction/hooks/useSendWalletTransactions.test.tsx
src/transaction/hooks/useSendWalletTransactions.tsx
src/transaction/types.ts
src/transaction/utils/sendSingleTransactions.test.ts
src/transaction/utils/sendSingleTransactions.ts

When passing multiple `Calls` to the `<Transaction />` component, if latter calls rely on the prior calls being confirmed, they will fail when using an EOA.
This PR ensures that we `await` prior transactions before calling the next `call`

fix: await sequential transaction calls in `<Transaction />`

---

src/fund/components/FundCardAmountInput.test.tsx
src/internal/components/amount-input/AmountInput.tsx
src/internal/hooks/useInputResize.test.ts
src/internal/hooks/useInputResize.ts

- Updated FundCard amount input to scale based on the input.
https://github.com/user-attachments/assets/b61260dd-5820-4f3b-8668-4315480abda2

feat:  Fund Card - Dynamic amount input size

---

site/docs/pages/api/types.mdx
site/sidebar.ts

* added `getPortfolios` documentation to sidebar
* fixed typo in type and type link

docs: fix type typo, add sidebar

---

.changeset/tiny-geckos-visit.md
src/token/components/TokenSelectDropdown.test.tsx
src/token/components/TokenSelectDropdown.tsx

This PR replaces the custom dropdown implementation in TokenSelectDropdown with the DropdownMenu primitive component, improving accessibility and maintainability.
Key Changes:
- Replace manual click/blur handling with DropdownMenu's built-in event management
- Remove custom positioning logic in favor of DropdownMenu's positioning system
- Simplify state management to single isOpen toggle
- Add proper ARIA attributes through DropdownMenu primitive
- Maintain existing visual styling and TokenRow/TokenSelectButton components
Benefits:
- Improved accessibility with proper ARIA attributes and keyboard navigation
- Consistent positioning behavior across different screen sizes
- Reduced code complexity by leveraging built-in primitive features
- Better focus management and …

feat: Implement DropdownMenu Primitive in TokenSelectDropdown

---

src/token/constants.ts

Several token addresses are not checksummed causing issues in future PRs when comparing addresses.
[Read more](https://docs.alchemy.com/docs/how-to-handle-checksum-addresses)

fix: ensure token addresses are checksummed

---

package.json
yarn.lock

Update `Vitest` to `v3.0.5`. 
`v3.0.5` includes a fix for a critical security vulnerability that was found - `Remote Code Execution when accessing a malicious website while Vitest API server is listening`
This vulnerability can result in remote code execution for users that are using Vitest serve API.
https://github.com/coinbase/onchainkit/security/dependabot/82

chore: Update Vitest to latest

---

src/transaction/components/Transaction.tsx

Returning `null` causes layout shift in the `<Transaction />` component. This PR updates the component to return a div with similar styling in order to prevent layout shift on mount.

fix: prevent layout shift in Transaction component

---

.changeset/selfish-cougars-travel.md
src/OnchainKitProvider.test.tsx
src/OnchainKitProvider.tsx
src/core/OnchainKitConfig.ts
src/core/network/sendAnalytics.test.ts
src/core/network/sendAnalytics.ts
src/core/types.ts
src/types.ts

We are adding telemetry to applicable OnchainKit components. We want to make it as easy to opt out as possible if that is what users prefer. Adding an opt out parameter. 

feat: Add telemetry opt-out

---

playground/nextjs-app-router/onchainkit/package.json
src/identity/utils/getName.ts

This PR fixes logic for fetching Basenames and ENS names in `getName`.
In the case where the chain is Base and the user does _not_ have a Basename, we hit an arm in the if/else where nothing is returned, allowing us to hit the case where we fallback to the ENS name. In that case, we want to be sure that we read from mainnet. Instead, we were attempting to read from Base, which caused retries and ultimately a timeout that returned null.
This reverts the prior change [here](https://github.com/coinbase/onchainkit/pull/1875/files#diff-35ac9703d5627d9d638ebb29587e99301f5710dd0e4313417e063619c56d7767).

fix: revert change resulting in slow identity resolution

---

src/appchain/bridge/abi.ts
src/appchain/bridge/constants.ts
src/appchain/bridge/hooks/useAppchainConfig.test.ts
src/appchain/bridge/hooks/useAppchainConfig.ts
src/appchain/bridge/hooks/useDeposit.test.ts
src/appchain/bridge/hooks/useDeposit.ts
src/appchain/bridge/hooks/useDepositButton.test.tsx
src/appchain/bridge/hooks/useDepositButton.tsx
src/appchain/bridge/hooks/useWithdraw.test.ts
src/appchain/bridge/hooks/useWithdraw.ts
src/appchain/bridge/hooks/useWithdrawButton.test.tsx
src/appchain/bridge/hooks/useWithdrawButton.tsx
src/appchain/bridge/types.ts
src/appchain/bridge/utils/getETHPrice.test.ts
src/appchain/bridge/utils/getETHPrice.ts
src/appchain/bridge/utils/getOutput.test.ts
src/appchain/bridge/utils/getOutput.ts
src/appchain/bridge/utils/isUserRejectedRequestError.test.ts
src/appchain/bridge/utils/isUserRejectedRequestError.ts
src/appchain/bridge/utils/maybeAddProofNode.ts
src/token/constants.ts

add hooks for appchain bridge component
`useAppchainConfig`
- queries the DeployChain for an appchain's configuration
`useDeposit`
- wraps Wagmi hooks to make a deposit to the L2's `StandardBridge` contract
`useWithdraw`
- wraps Wagmi hooks to make a withdrawal from the appchain's `StandardBridge` and `OptimismPortal` contracts
`useDepositButton` and `useWithdrawButton`
- manages states for components (later PR)
and misc. util functions
unit tests and locally in playground (entire PR)

feat: appchain bridge hooks

---

.changeset/tall-moose-type.md
biome.json
src/appchain/bridge/components/AppchainBridge.test.tsx
src/appchain/bridge/components/AppchainBridge.tsx
src/appchain/bridge/components/AppchainBridgeAddressInput.test.tsx
src/appchain/bridge/components/AppchainBridgeAddressInput.tsx
src/appchain/bridge/components/AppchainBridgeInput.test.tsx
src/appchain/bridge/components/AppchainBridgeInput.tsx
src/appchain/bridge/components/AppchainBridgeNetwork.tsx
src/appchain/bridge/components/AppchainBridgeProvider.test.tsx
src/appchain/bridge/components/AppchainBridgeProvider.tsx
src/appchain/bridge/components/AppchainBridgeTransactionButton.test.tsx
src/appchain/bridge/components/AppchainBridgeTransactionButton.tsx
src/appchain/bridge/components/AppchainBridgeWithdraw.test.tsx
src/appchain/bridge/components/AppchainBridgeWithdraw.tsx
src/appchain/bridge/components/AppchainNetworkToggleButton.tsx
src/appchain/bridge/constants.ts
src/appchain/bridge/types.ts
src/appchain/bridge/utils/defaultPriceFetcher.test.ts
src/appchain/bridge/utils/defaultPriceFetcher.ts
src/internal/svg/fullWidthSuccessSvg.tsx

add FE components for bridge UI
will rebase and change reference to `master` once https://github.com/coinbase/onchainkit/pull/1971 is merged
unit tests, QA, playground

feat: appchain bridge UI

---

package.json
src/appchain/bridge/hooks/useDeposit.ts
src/appchain/bridge/hooks/useDepositButton.tsx
src/appchain/bridge/hooks/useWithdraw.ts
src/appchain/bridge/hooks/useWithdrawButton.tsx
src/appchain/bridge/types.ts
src/appchain/index.ts

- expose `/appchain` in `package.json`
- export components, hooks, and types

feat: export appchain bridge components, hooks, and types

---

src/identity/utils/getName.test.ts

We recently had a regression where our fallback for `getName` on mainnet was changed to read from `base` instead, causing slow resolution the `Wallet` component. This PR improves test coverage to prevent a regression in the future.

fix: add test coverage for `getName` fallback function

---

src/identity/utils/getName.ts

As discussed, we want to improve the readability of `getName` by removing the variable reassignment to prevent future regressions and improve readability.

fix: improve readability of `getName`

---

src/core/analytics/hooks/useAnalytics.ts

Currently `sendAnalytics` does not properly narrow down its arguments based on the analytics event type. This PR updates the types to work properly.

fix: fix types for `sendAnalytics`

---

src/earn/components/DepositButton.tsx
src/earn/components/Earn.tsx
src/earn/components/EarnProvider.tsx
src/earn/components/WithdrawButton.tsx
src/earn/mocks/index.ts
src/earn/types.ts

This PR updates `<Earn />` to accept an `isSponsored` prop which is then used to sponsor deposit and withdraw transactions
Locally in playground

feat: add `isSponsored` to `<Earn />`

---

site/docs/layout.tsx

During deploys, our docs site occasionally goes down with the error `TypeError: Failed to fetch dynamically imported module`. This happens because previously built and deployed assets have become available as Vercel has removed the files but the client has not yet been updated. 
If that happens, we want to force the client to reload and fetch the lastest bundles.

fix: add fallback for docs site during deployment

---

src/buy/utils/getBuyQuote.ts
src/internal/components/amount-input/AmountInput.tsx

- **Improved sentence structure in `getBuyQuote.ts`**  
- "how much of X we will recieve if we sell the input token amount" →  
"how much of X we will receive if we sell the input token amount"  
- **Refined comment in `AmountInput.tsx`**  
- "currency symbol is far away from the inputed value" →  
"currency symbol is far away from the inputted value"  
- `src/buy/utils/getBuyQuote.ts`  
- `src/internal/components/amount-input/AmountInput.tsx`

fix spelling error in `getBuyQuote.ts` and `AmountInput.tsx` for improved clarity

---

src/nft/utils/buildMintTransactionData.test.ts

I fixed a typo in the variable name when importing and mocking `buildMintTransaction`. The incorrect `buildMintTransationApi` was replaced with the correct `buildMintTransactionApi`.

fix: fix typo in `buildMintTransactionData.test.ts`

---

site/docs/pages/earn/earn.mdx
site/docs/pages/earn/types.mdx

We added `isSponsored` functionality to the `Earn` component, updating docs to reflect.

docs: add `isSponsored` prop to `Earn` docs

---

src/core/analytics/hooks/useAnalytics.test.ts
src/core/analytics/hooks/useAnalytics.ts
src/core/analytics/utils/sendAnalytics.test.ts
src/core/analytics/utils/sendAnalytics.ts

Allowing the client application to explicitly set the origin.
With our current setup, grabbing the origin from the request header in the backend, the presence of Origin is unreliable - resulting in many events having an empty origin field. 

chore: Add origin to analytics

---

src/OnchainKitProvider.tsx
src/OnchainKitProviderBoundary.test.tsx
src/OnchainKitProviderBoundary.tsx
src/core/analytics/hooks/useAnalytics.test.ts
src/core/analytics/hooks/useAnalytics.ts

Adding a boundary around all of onchainkit to catch any unhandled errors, ideally components will implement their own more granular boundaries, but this will at least prevent ock from crashing a developers application.

fix: add onchainkit boundary

---

.changeset/witty-snakes-serve.md
src/appchain/bridge/components/AppchainBridge.test.tsx
src/appchain/bridge/components/AppchainBridge.tsx
src/appchain/bridge/components/AppchainBridgeProvider.test.tsx
src/appchain/bridge/components/AppchainBridgeProvider.tsx
src/appchain/bridge/components/AppchainBridgeResumeTransaction.test.tsx
src/appchain/bridge/components/AppchainBridgeResumeTransaction.tsx
src/appchain/bridge/components/AppchainBridgeSuccess.test.tsx
src/appchain/bridge/components/AppchainBridgeSuccess.tsx
src/appchain/bridge/components/AppchainBridgeWithdraw.test.tsx
src/appchain/bridge/components/AppchainBridgeWithdraw.tsx
src/appchain/bridge/hooks/useWithdraw.ts
src/appchain/bridge/hooks/useWithdrawButton.test.tsx
src/appchain/bridge/hooks/useWithdrawButton.tsx
src/appchain/bridge/types.ts
src/internal/svg/fullWidthErrorSvg.tsx

- add `AppchainBridgeResumeTransaction`
this lets users resume a claim (e.g. if they accidentally exited out of the previous one)
unit tests, see Slack for video

feat: add `AppchainBridgeResumeTransaction`

---

playground/nextjs-app-router/components/AppProvider.tsx
playground/nextjs-app-router/components/OnchainProviders.tsx

The old image broken during the OnchainKit move to Base.org. Updating with the new logo.

chore: Add OCK logo to ConnectWallet in the playground

---

.changeset/yellow-toys-sin.md
playground/nextjs-app-router/onchainkit/package.json
src/internal/components/BottomSheet.tsx
src/internal/components/Dialog.tsx
src/internal/components/DropdownMenu.tsx
src/internal/components/Popover.tsx
src/internal/hooks/useOutsideClick.test.ts
src/internal/hooks/useOutsideClick.ts

* added `data-portal-origin="true"` property to all portal-using components
* added logic to `useOutsideClick` to exclude clicks from elements with data-porta-origin
why is excluding portal-clicks on `useOutsideClick` okay?
* if there is a portal open then...
* either it opened from an outside click
* or it opened from an "inside click"
* in the former case, `useOutsideClick` will call the callback
* in the latter case, given that the portal opened _because of an "inside click"_, clicks on the portal should not constitute outside clicks and should not call the callback
in playground

fix: improve useOutsideClick portal handling

---

src/core/analytics/types.ts

Updating Analytics type definitions from optional properties to using | undefined. 
Union with undefined is better here because when sending events it helps seeing the distinction between a property that was expected but not provided. 

chore: Update analytics type definitions to union with undefined

---

src/earn/components/Earn.tsx
src/internal/components/tabs/Tab.tsx

| Before | After |
|--------|--------|
| ![DS 2025-02-26 at 14 31 53@2x](https://github.com/user-attachments/assets/eedcb51c-cd38-482a-9f88-adc17255893c) | ![DS 2025-02-26 at 14 32 30@2x](https://github.com/user-attachments/assets/8ca6e951-f070-4bc8-8bf0-d112620b710c) |

fix: improve focus states in `Earn` for keyboard users

---

src/earn/components/Earn.tsx
src/earn/components/EarnAmountInput.tsx
src/styles/theme.ts

Updating the `EarnAmountInput` component to handle font family based on theme.

fix: show proper theme in `EarnAmountInput`

---

src/appchain/bridge/components/AppchainBridgeProvider.tsx

explorer should always open using `chain.id` (Base or Base Sepolia) instead of `from.id`, `getExplorer` will return Basescan since for withdrawals `from` is the appchain ID

fix: use `chain.id` instead

---

src/core/analytics/constants.ts
src/core/analytics/types.ts

Add a new analytics event to track when users manually cancel actions in OnchainKit components. `SwapCanceled`, `checkoutCanceled`, etc. 

chore: Add canceled event type

---

src/buy/components/BuyDropdown.test.tsx
src/buy/components/BuyDropdown.tsx
src/buy/components/BuyProvider.test.tsx
src/buy/components/BuyProvider.tsx
src/core/analytics/types.ts

feat: Add Buy Telemetry

---

src/internal/components/amount-input/AmountInput.tsx

* TextInput supports a `delayMs` prop for debouncing
* AmountInput implements TextInput. Previously it had not supported `delayMs`
* This PR adds `delayMs` as a supported prop that's passed to TextInput
* locally, in playground

feat: allow AmountInput to use TextInput's delayMs prop

---

src/wallet/components/WalletAdvancedContent.test.tsx
src/wallet/components/WalletAdvancedContent.tsx
src/wallet/components/WalletAdvancedProvider.test.tsx
src/wallet/components/WalletAdvancedProvider.tsx
src/wallet/components/WalletAdvancedQrReceive.test.tsx
src/wallet/components/WalletAdvancedQrReceive.tsx
src/wallet/components/WalletAdvancedSwap.test.tsx
src/wallet/components/WalletAdvancedSwap.tsx
src/wallet/components/WalletAdvancedTokenHoldings.test.tsx
src/wallet/components/WalletAdvancedTokenHoldings.tsx
src/wallet/components/WalletAdvancedTransactionActions.test.tsx
src/wallet/components/WalletAdvancedTransactionActions.tsx
src/wallet/components/WalletAdvancedWalletActions.test.tsx
src/wallet/components/WalletAdvancedWalletActions.tsx
src/wallet/types.ts

* previously, we had state for the two sub-components: QR and Swap. 
* in preparation for the addition of Send, I refactored how WalletAdvanced handles sub-components
* instead of separate state for each sub-component, there is one state: `activeFeature`. this simplifies the devex for controlling which feature is displayed
test coverage and in playground

refactor: improve WalletAdvanced sub-component handling

---

src/core/analytics/types.ts
src/wallet/components/ConnectWallet.test.tsx
src/wallet/components/ConnectWallet.tsx

Refactor our wallet connector events to use the connector from `useAccount()` to determine and pass the WalletProvider in our analytics events. 

chore: Refactor WalletProvider event to use connector from useAccount

---

package.json
src/DefaultOnchainKitProviders.test.tsx
src/DefaultOnchainKitProviders.tsx
src/OnchainKitProvider.tsx
src/core/createWagmiConfig.ts
src/core/types.ts
src/minikit/MiniKitProvider.test.tsx
src/minikit/MiniKitProvider.tsx
src/minikit/index.ts
src/minikit/types.ts
yarn.lock

* Add MiniKitProvider
* Provides global access to context 
* Hooks up event listeners
* Updates internal context state with notification details
* Adds SafeAreaInsets
* Extract Default wagmi/query provider logic to DefaultOnchainKitProviders to reuse allowing consumers to wrap MiniKitProvider with their own wagmi/react-query

feat: add minikit provider

---

playground/nextjs-app-router/components/demo/Swap.tsx
playground/nextjs-app-router/onchainkit/package.json
src/swap/components/Swap.test.tsx
src/swap/components/Swap.tsx
src/swap/components/SwapAmountInput.tsx
src/swap/components/SwapButton.tsx
src/swap/components/SwapDefault.tsx
src/swap/components/SwapSettings.tsx
src/swap/components/SwapToggleButton.tsx
src/swap/types.ts

Update Swap and SwapSettings components to have default children.  Added toToken, fromToken, swappableTokens as top level props when children is undefined.  Interface is unchanged when children are passed in.
* Remove findChildren
* Add default children
* SwappableTokens, toToken, fromToken to Swap component, required when children is undefined
| swap default | swap with children | swap with extra |
| ------------- | -------------------| ---------------- |
| ![image](https://github.com/user-attachments/assets/a7edbfbb-d634-4686-b609-d788f3a3f7e3) | ![image](https://github.com/user-attachments/assets/b3234125-0fd7-4cbc-be31-e4e94fef44d5) | ![image](https://github.com/user-attachments/assets/800d7cc9-e8ce-4dce-af14-8efefe3a4308) |
**How has it …

refactor: remove swap findChildren

---

src/wallet/components/WalletDropdownLink.test.tsx
src/wallet/types.ts

Fixed `WalletDropdownLinkReact` type to allow `ReactNode` in `icon` property
When sending a `ReactNode` in the `icon` property is already working well.
**Code screenshots**
```tsx
<WalletDropdownLink icon={<Bot />} href="/deployed-agents">
My agents
</WalletDropdownLink>
```

fix(WalletDropdownLinkReact): icon type allow ReactNode

---

.changeset/tame-rice-dress.md
site/docs/pages/config/is-base.mdx
site/docs/pages/config/is-ethereum.mdx
site/docs/pages/config/types.mdx
src/core/types.ts
src/core/utils/isBase.ts
src/core/utils/isEthereum.ts
src/index.ts

Interfaces and Types should use `PascalCase`, we currently are using `camelCase` for type `isBaseOptions` and `isEthereumOptions`. 
Updating types to use `PascalCase` to remain consistent across our library. 
Note that this is a breaking change. 
This naming convention issue was brought up in this PR [fix: types naming convention](https://github.com/coinbase/onchainkit/pull/1915#top) 

chore: Update IsBaseOptions and IsEthereumOptions naming convention 

---

src/wallet/index.ts

Added an export of the `WalletModal` component to allow opening it from custom connect buttons instead of the generic UI.
Spotted during ETH Denver, it was useful for our case as we have multiple login providers, including OnchainKit, and don't want to use the big "Connect" button, but instead our own button that will open the modal.
Using the wagmi connector directly wasn't possible as it only exposes Coinbase Wallet, not the Metamask / Phantom options also provided in this modal
/
Straightforward change that shouldn't require testing, but we tested and integrated in our project

fix(wallet): Export WalletModal to allow custom opening

---

package.json
playground/nextjs-app-router/components/Demo.tsx
playground/nextjs-app-router/components/DemoOptions.tsx
playground/nextjs-app-router/components/demo/Signature.tsx
playground/nextjs-app-router/components/form/active-component.tsx
playground/nextjs-app-router/onchainkit/package.json
playground/nextjs-app-router/types/onchainkit.ts
src/internal/components/Toast.tsx
src/signature/components/Signature.test.tsx
src/signature/components/Signature.tsx
src/signature/components/SignatureButton.test.tsx
src/signature/components/SignatureButton.tsx
src/signature/components/SignatureIcon.test.tsx
src/signature/components/SignatureIcon.tsx
src/signature/components/SignatureLabel.test.tsx
src/signature/components/SignatureLabel.tsx
src/signature/components/SignatureProvider.test.tsx
src/signature/components/SignatureProvider.tsx
src/signature/components/SignatureStatus.test.tsx
src/signature/components/SignatureStatus.tsx
src/signature/components/SignatureToast.test.tsx
src/signature/components/SignatureToast.tsx
src/signature/index.ts
src/signature/types.ts
src/signature/utils/validateMessage.test.ts
src/signature/utils/validateMessage.ts

Adding Signature component which utilizes wagmi signTypedData (EIP 712) and signMessage (personal_sign falling back to eth_sign) to sign data

feat: signature

---

.changeset/soft-melons-lie.md
src/token/components/TokenBalance.test.tsx
src/token/components/TokenBalance.tsx
src/token/types.ts
src/wallet/components/wallet-advanced-send/components/SendTokenSelector.test.tsx

* Refactored the "Action Button" (typically "max")
* Refactored types to be discriminated unions that disallow erroneous prop combinations
* locally, playground, test coverage

chore: better TokenBalance 

---

site/docs/pages/api/get-portfolios.mdx
src/api/getPortfolios.ts

* Added supported network info to `getPortolios`

chore: add supported networks documentation for getPortfolios

---

src/fund/utils/fetchOnrampConfig.test.ts
src/fund/utils/fetchOnrampConfig.ts
src/fund/utils/fetchOnrampOptions.test.ts
src/fund/utils/fetchOnrampOptions.ts
src/fund/utils/fetchOnrampQuote.test.ts
src/fund/utils/fetchOnrampQuote.ts
src/fund/utils/fetchOnrampTransactionStatus.test.ts
src/fund/utils/fetchOnrampTransactionStatus.ts

Updated Onramp utils to allow to be used in non-react JS environments and/or without having to set up Onchainkit Provider

chore(ONRAMP-5024):Make OnchainKit onramp utils usable without the OCK Provider (in non-React environments)

---

.changeset/fluffy-icons-rhyme.md
src/core/types.ts
src/internal/hooks/useTheme.test.ts
src/internal/hooks/useTheme.ts
src/styles/tailwind-base.css

Add `base-light` and `base-dark` theme support. 

feat: Add Base light and dark theme

---

.changeset/eight-crabs-tan.md
src/identity/components/Badge.test.tsx
src/identity/components/Badge.tsx
src/identity/components/IdentityCard.test.tsx
src/identity/components/IdentityCard.tsx
src/identity/types.ts

The attestation badge can be confusing, it's simply a checkmark that displays next to the users wallet name or address. This tooltip will make it clear what the Badge represents. It will also allow the developer to customize the message.
`<IdentityCard /> // No tooltip.` 
`<IdentityCard badgeTooltip={true} /> // Tooltip with attestation name` 
`<IdentityCard badgeTooltipText="Custom text" /> // Tooltip with "Custom text"`
```
<Identity>
<Badge /> // No tooltip
</Identity>
```
```
<Identity>
<Badge tooltip={true} /> // Tooltip with attestation name
</Identity>
```
```
<Identity>
<Badge tooltipText="Custom text" /> // Tooltip with "Custom text
</Identity>
```
With themes:

feat: Add Badge tooltip display

---

playground/nextjs-app-router/components/form/nft-options.tsx

Replace `htmlFor="chain"` with `htmlFor="nftToken"` to ensure the label properly references the corresponding input. This improves accessibility and helps screen readers identify the correct field.

Replace `htmlFor="chain"` nft-options.tsx

---

playground/nextjs-app-router/components/demo/Buy.tsx
src/buy/components/BuyDropdown.tsx
src/buy/components/BuyOnrampItem.test.tsx
src/buy/components/BuyOnrampItem.tsx

The USD estimate for $5 of USDC is slightly off (4.9999). There is a minimum amount of $5 required for onramp options so this PR updates that check to use amount instead of amountUSD for USDC buys. We need to keep amountUSD for non-USDC tokens.

chore: fix onramp bug

---

src/minikit/hooks/useNotification.test.tsx
src/minikit/hooks/useNotification.ts

Pass in notification details from frontend context when available to allow in-app notifications to be sent without a database.

fix: pass in notification details when available

---

.changeset/petite-guests-itch.md
packages/onchainkit/src/identity/hooks/useAttestations.test.ts
packages/onchainkit/src/identity/hooks/useAttestations.ts
packages/onchainkit/src/identity/utils/getAttestations.test.ts
packages/onchainkit/src/identity/utils/getAttestations.ts

Add caching to the `useAttestation` hook.
This saves us one network call on every render of the identity component - reducing network overhead and latency.
Removes:
Tested in playground using logs and network tab.

chore: Add Attestation caching

---

packages/onchainkit/scripts/get-next-version.js
packages/onchainkit/scripts/get-next-version.test.ts

- Removed `--since=origin/main` flag in the changeset script which was causing it to not report a version
- Fall back to package.json if changeset doesn't produce a version change
- More robust error handling
- Manually

fix: Changeset version script

---

eslint.config.mjs
packages/onchainkit/src/appchain/bridge/components/AppchainBridgeWithdraw.test.tsx
packages/onchainkit/src/appchain/bridge/components/AppchainBridgeWithdraw.tsx
packages/onchainkit/src/fund/components/FundCardPaymentMethodSelectRow.tsx
packages/onchainkit/src/fund/components/FundCardPaymentMethodSelectorToggle.tsx
packages/onchainkit/src/internal/components/TextInput.tsx
packages/onchainkit/src/internal/components/amount-input/CurrencyLabel.tsx
packages/onchainkit/src/wallet/hooks/usePortfolio.test.tsx

Enabling the eslint rule `display-name` and fixing or ignoring the flagged errors.
Why? This ensures the component appears properly labeled in all tooling, making development, debugging, and testing much more efficient. Adding the display name is considered a best practice in React development, especially for components created with forwardRef, memo, or other higher-order components.
Unit tests.

chore: Enable eslint display-name rule

---

eslint.config.mjs
packages/onchainkit/src/internal/components/TextInput.test.tsx
packages/onchainkit/src/internal/svg/addSvg.tsx
packages/onchainkit/src/internal/svg/errorSvg.tsx
packages/onchainkit/src/internal/svg/fullWidthErrorSvg.tsx
packages/onchainkit/src/internal/svg/fullWidthSuccessSvg.tsx
packages/onchainkit/src/internal/svg/successSvg.tsx

Enabling the eslint rule `prop-types` and fixing or ignoring the flagged errors.
This enforces the use of PropTypes for React component props validation. It checks that any component that receives props has proper prop validation defined.
Unit tests.

chore: Enable eslint prop-types rule

---

packages/onchainkit/src/appchain/bridge/components/AppchainBridgeProvider.test.tsx

Attempting to fix the flaky unit test - _should handle address modal state changes_.
This fix moves the assertion inside the waitFor callback, ensuring the test waits for the state update to complete before making the assertion.

fix: Flaky Appchain unit test

---

packages/playground/app/layout.tsx
packages/playground/app/page.tsx

Move Ock providers to page so they aren't inherited by the minikit app

fix: playground layout providers

---

packages/onchainkit/src/buy/components/Buy.test.tsx
packages/onchainkit/src/signature/components/SignatureButton.test.tsx
packages/onchainkit/src/signature/components/SignatureButton.tsx
packages/onchainkit/src/wallet/components/ConnectWallet.test.tsx
packages/onchainkit/src/wallet/components/ConnectWallet.tsx
packages/onchainkit/src/wallet/components/ConnectWalletText.tsx
packages/onchainkit/src/wallet/components/Wallet.tsx
packages/onchainkit/src/wallet/components/WalletAdvancedDefault.tsx
packages/onchainkit/src/wallet/components/WalletIsland.tsx
packages/onchainkit/src/wallet/types.ts
packages/playground/components/demo/Wallet.tsx

- implement default children for `<ConnectWallet />`
- refactor ConnectWallet logic
- introduce new prop `disconnectedLabel` on ConnectWallet that enables devs to customize disconnected state (children will represent connected state)
- deprecate `ConnectWalletText` component

chore: update ConnectWallet and add default children

---

.changeset/nice-spoons-kiss.md
packages/onchainkit/package.json
packages/onchainkit/scripts/publish-alpha.js
packages/onchainkit/scripts/publish-alpha.test.ts

- Removes \@coinbase/onchainkit/core export from package.json that's not included in the build
- Removes --dry-run from alpha release script
Figured this change would be a good minor but testable change to test alpha releases with.
Manually

fix: Remove unused @coinbase/onchainkit/core export + enable alpha releases

---

packages/onchainkit/src/fund/index.ts
packages/onchainkit/src/fund/types.ts

Exporting missing type - `SuccessEventData` for the Fund component. 
This type should be exported. It is currently[ erroring in the Fund setup-onramp-event-listeners docs page.](https://docs.base.org/builderkits/onchainkit/fund/setup-onramp-event-listeners) 

chore: Export Fund SuccessEventData type

---

eslint.config.mjs
packages/onchainkit/src/core/network/attestations.ts
packages/onchainkit/src/fund/utils/subscribeToWindowMessage.test.ts
packages/onchainkit/src/identity/hooks/useAttestations.test.ts
packages/onchainkit/src/internal/hooks/useDebounce.ts
packages/onchainkit/src/internal/types.ts
packages/onchainkit/src/internal/utils/formatFiatAmount.test.ts
packages/onchainkit/src/swap/types.ts
packages/onchainkit/src/transaction/hooks/useWriteContracts.test.ts
packages/onchainkit/src/transaction/types.ts
packages/onchainkit/src/wallet/components/ConnectWallet.test.tsx

Enable eslint `no-explicit-any` and explicitly ignore the flagged errors.

chore: Enable eslint rule no-explicit-any 

---

.github/workflows/build.yml
packages/onchainkit/package.json
packages/onchainkit/scripts/validate-build.js
packages/onchainkit/scripts/validate-build.test.ts

Recently we published a build that didn't include a file that was referenced in our package.json exports.
This script will mock publishing the package and ensure that all exported files make it to the packed package.
I added this check to the current build workflow. Let me know if you think it belongs somewhere else.
- Manually
- Unit tests

chore: Add script to validate that the package includes all exports

---

packages/onchainkit/src/styles/index-with-tailwind.css

fixes issue where inline styles are being overwritten by theme classes
```
<Name className="text-[red]" />
```
before:
after:

chore: reorder css imports to allow overrides

---

.changeset/mighty-rockets-teach.md
packages/onchainkit/src/identity/hooks/useName.test.tsx
packages/onchainkit/src/identity/utils/getName.test.ts
packages/onchainkit/src/identity/utils/getName.ts

This PR fixes a vulnerability in the identity resolution system that allowed users to spoof their displayed names.
The current implementation of reverse resolution (address → name) didn't verify name ownership:
- It's possible to spoof the address by setting a name on the reverse registry without actually owning the name
- We would display that name without verification
The Solution: Bidirectional Validation
- Reverse Resolution: Get name from address (getName)
- Forward Resolution: Resolve name back to address (getAddress)
- Validation: Only display the name if addresses match
This prevents malicious actors from falsely displaying names they don't control, ensuring all displayed names are properly verified and legitimate.
Following with …

chore: Add bidirectional resolution validation to Basenames and ENS names

---

.changeset/tame-pugs-create.md
packages/onchainkit/src/wallet/components/WalletAdvancedAddressDetails.test.tsx
packages/onchainkit/src/wallet/components/WalletAdvancedAddressDetails.tsx
packages/onchainkit/src/wallet/components/WalletAdvancedTokenHoldings.test.tsx
packages/onchainkit/src/wallet/components/WalletAdvancedTokenHoldings.tsx
packages/onchainkit/src/wallet/components/WalletAdvancedTransactionActions.test.tsx
packages/onchainkit/src/wallet/components/WalletAdvancedTransactionActions.tsx
packages/onchainkit/src/wallet/components/WalletAdvancedWalletActions.test.tsx
packages/onchainkit/src/wallet/components/WalletAdvancedWalletActions.tsx
packages/onchainkit/src/wallet/components/WalletDropdownContent.test.tsx
packages/onchainkit/src/wallet/components/WalletDropdownContent.tsx
packages/onchainkit/src/wallet/components/WalletProvider.tsx
packages/onchainkit/src/wallet/components/wallet-advanced-send/components/SendProvider.test.tsx
packages/onchainkit/src/wallet/components/wallet-advanced-send/components/SendProvider.tsx
packages/onchainkit/src/wallet/components/wallet-advanced-send/components/SendTokenSelector.test.tsx
packages/onchainkit/src/wallet/components/wallet-advanced-send/components/SendTokenSelector.tsx
packages/onchainkit/src/wallet/hooks/usePortfolio.test.tsx
packages/onchainkit/src/wallet/hooks/usePortfolio.ts
packages/onchainkit/src/wallet/types.ts

Move usePortfolio out of wallet context so its only called when its actually used

fix: only call useportfolio when subcomponents need it

---

.changeset/early-schools-lie.md
packages/onchainkit/src/identity/hooks/useAddresses.test.tsx
packages/onchainkit/src/identity/hooks/useAddresses.ts
packages/onchainkit/src/identity/index.ts
packages/onchainkit/src/identity/types.ts
packages/onchainkit/src/identity/utils/getAddresses.test.ts
packages/onchainkit/src/identity/utils/getAddresses.ts

Added new multicall ENS resolution utilities with `useAddresses` hook and `getAddresses` utility function to efficiently resolve multiple ENS or Basenames to Ethereum addresses, reducing network requests and improving performance for batch resolution scenarios.
Follow up from [chore: Add bidirectional resolution validation when batching Basenames and ENS names](https://github.com/coinbase/onchainkit/pull/2264#top). As an additional fast follow, I will be implementing this function into `getNames`.
Unit tests.

feat: Add batch ENS / Basename resolution with useAddresses hook and getAddresses utility

---

packages/playground/components/AppProvider.tsx
packages/playground/components/demo/Identity.tsx
packages/playground/components/demo/IdentityCard.tsx

currently, if disconnected in the identity demo, the page is blank. we can either show the `<ConnectWallet />` or a message indicating user needs to connect

chore: show connect button when disconnected in Identity demo

---

.changeset/fancy-pets-add.md
packages/onchainkit/src/identity/utils/getNames.test.ts
packages/onchainkit/src/identity/utils/getNames.ts

Refactors the `getNames` function to use the `getAddresses` utility for batch name verification, replacing individual address verifications with more efficient batch processing. 
The change improves performance by reducing network calls when resolving multiple names.

chore: Refactor getNames utility to leverage batch processing with getAddresses

---

packages/create-onchain/templates/minikit-basic/package.json
packages/create-onchain/templates/minikit-snake/package.json

I just spun up a new minikit app locally, and one of the first things I noticed when I opened the codebase was the use of the @farcaster/frame-sdk package, but it was not actually installed (i.e not included in package.json). This PR adds that package to the package.json for both minikit app templates so people won't have to install it separately. 
I just copy and pasted the line from my own package.json into the templates.
My linter is happy.

chore: Add @farcaster/frame-sdk dependency to minikit templates

---

packages/create-onchain/src/onchainkit.test.ts
packages/create-onchain/src/onchainkit.ts

default to create-onchain wallet config to `all` and remove cli prompt 

chore: remove smart wallet check from cli prompt

---

packages/onchainkit/package.json

- Fixes syntax for publishConfig.access
- Manually

fix: OnchainKit package.json publishConfig.access = public

---

packages/onchainkit/src/signature/components/SignatureProvider.test.tsx
packages/onchainkit/src/signature/components/SignatureProvider.tsx

Added proper cleanup of SignatureProvider on unmount. Currently, if the component unmounts within 1000ms after a successful action, state mutation happens on an unmounted component.

fix: signature provider unmount reset

---

packages/playground/app/mint/hooks/useEarningsData.ts
packages/playground/components/demo/FundCard.tsx
packages/playground/components/demo/Transaction.tsx
packages/playground/lib/nft/buildMintTransaction.ts
packages/playground/lib/nft/useReservoirMintData.ts
packages/playground/lib/nft/useReservoirNFTData.ts

We had some type imports that were still using imports from before the monorepo migration. This removes those imports.
I went with quick and dirty since we're starting to land on what v1 looks like. IMO, this is a good example of more types that should be exported. Personally, I'd err on the side of exporting all internal types.
Manually

fix: Updates playground to remove outdated imports

---

packages/onchainkit/src/OnchainKitProvider.tsx
packages/onchainkit/src/utils/crypto.test.ts
packages/onchainkit/src/utils/crypto.ts

- Added a fallback for non-critical uuid usages to allow for testing in http environments
See issue https://github.com/coinbase/onchainkit/issues/2309
Did not introduce `uuid` dependency to avoid bloating package/security concerns (though extremely unlikely), but it's a consideration we can make

fix: support an insecure fallback for session id to allow for testing on http contexts

---

packages/create-onchain/package.json

Marks `create-onchain` library as public

chore: Make create-onchain library public

---

.changeset/twenty-news-hide.md
packages/onchainkit/src/identity/hooks/useAddress.test.tsx
packages/onchainkit/src/identity/hooks/useAddresses.test.tsx
packages/onchainkit/src/identity/hooks/useAddresses.ts
packages/onchainkit/src/identity/types.ts
packages/onchainkit/src/identity/utils/getAddress.test.ts
packages/onchainkit/src/identity/utils/getAddress.ts
packages/onchainkit/src/identity/utils/getAddresses.test.ts
packages/onchainkit/src/identity/utils/getAddresses.ts
packages/onchainkit/src/identity/utils/getName.test.ts
packages/onchainkit/src/identity/utils/getName.ts
packages/onchainkit/src/identity/utils/getNames.ts

Updates calls to `viem.client.getEnsAddress` to use the mainnet client exclusively.
This is the intended way to do ENS resolution. This was only working until recently because the function signature expected by Viem matched our Basenames resolver, but this changed in a recent update to Viem.

fix: Basenames bidirectional validation

---

packages/onchainkit/src/identity/utils/getSocials.test.ts
packages/onchainkit/src/identity/utils/getSocials.ts

Fixes getSocials util by using mainnet resolver to call `client.getEnsName`
- Manually
- Unit tests

fix: getSocials

---

packages/onchainkit/src/fund/components/FundButton.test.tsx
packages/onchainkit/src/fund/components/FundButton.tsx
packages/onchainkit/src/fund/components/FundCard.tsx
packages/onchainkit/src/fund/components/FundCardAmountInput.test.tsx
packages/onchainkit/src/fund/components/FundCardAmountInput.tsx
packages/onchainkit/src/fund/components/FundCardAmountInputTypeSwitch.test.tsx
packages/onchainkit/src/fund/components/FundCardAmountInputTypeSwitch.tsx
packages/onchainkit/src/fund/components/FundCardHeader.tsx
packages/onchainkit/src/fund/components/FundCardPaymentMethodDropdown.tsx
packages/onchainkit/src/fund/components/FundCardPaymentMethodImage.tsx
packages/onchainkit/src/fund/components/FundCardPaymentMethodSelectRow.tsx
packages/onchainkit/src/fund/components/FundCardPaymentMethodSelectorToggle.tsx
packages/onchainkit/src/fund/components/FundCardPresetAmountInputItem.tsx
packages/onchainkit/src/fund/components/FundCardProvider.tsx
packages/onchainkit/src/fund/components/FundCardSubmitButton.test.tsx
packages/onchainkit/src/fund/components/FundCardSubmitButton.tsx
packages/onchainkit/src/fund/index.ts
packages/onchainkit/src/fund/types.ts
packages/playground/components/Demo.tsx
packages/playground/components/demo/FundButtonWithRenderProp.tsx
packages/playground/components/form/active-component.tsx
packages/playground/types/onchainkit.ts

- add render prop to FundButton and remove display props 
- add children prop to FundButton (mutually exclusive with render prop)
- remove `text`, `successText`, `errorText`, `hideIcon`, `hideText` props
```js
<FundCardSubmitButton render={customRender} />
<FundButton render={customRender} />
```

chore: refactor fund components

---

packages/onchainkit/CHANGELOG.md

changed link, previous one was 404

docs: fix broken link

---

.github/workflows/build.yml
packages/onchainkit/src/fund/components/FundCardSubmitButton.tsx
packages/onchainkit/src/internal/svg/errorSvg.tsx
packages/onchainkit/src/internal/svg/successSvg.tsx
packages/onchainkit/src/wallet/components/Wallet.tsx

v1: Fix lint issues

---

packages/onchainkit/src/wallet/components/Wallet.tsx
packages/onchainkit/src/wallet/components/WalletIsland.tsx
packages/onchainkit/src/wallet/components/WalletProvider.tsx
packages/onchainkit/src/wallet/components/wallet-advanced-send/components/SendButton.test.tsx
packages/onchainkit/src/wallet/components/wallet-advanced-send/components/SendButton.tsx
packages/onchainkit/src/wallet/types.ts
packages/playground/components/DemoOptions.tsx
packages/playground/components/demo/WalletIsland.tsx

Send component is an internal component only used within Wallet when configured with Advanced components. we were exposing multiple props through `SendButton` that would never be used, given that it is an internal component. This PR removes those props to simplify logic. 
This PR also adds an optional `isSponsored` prop to Wallet so devs can enable sponsored transaction with send

chore: enable paymaster for wallet advanced Send

---

packages/miniapp-manifest-generator/package.json
packages/onchainkit/.vscode/extensions.json
packages/onchainkit/.vscode/settings.json
packages/onchainkit/CHANGELOG.md
packages/onchainkit/package.json
packages/onchainkit/src/DefaultOnchainKitProviders.test.tsx
packages/onchainkit/src/DefaultOnchainKitProviders.tsx
packages/onchainkit/src/connected/__tests__/Connected.test.tsx
packages/onchainkit/src/minikit/MiniKitProvider.tsx
packages/onchainkit/src/wallet/components/Wallet.tsx
packages/onchainkit/src/wallet/components/WalletIsland.tsx
packages/onchainkit/src/wallet/components/WalletProvider.tsx
packages/onchainkit/src/wallet/components/wallet-advanced-send/components/SendButton.test.tsx
packages/onchainkit/src/wallet/components/wallet-advanced-send/components/SendButton.tsx
packages/onchainkit/src/wallet/types.ts
packages/playground/components/DemoOptions.tsx
packages/playground/components/demo/WalletIsland.tsx
pnpm-lock.yaml

chore: merge main

---

packages/onchainkit/src/minikit/MiniKitProvider.test.tsx
packages/onchainkit/src/minikit/MiniKitProvider.tsx

Updates MiniKitProvider so that it respects the wallet.preference option if it's running outside the context of a mini app
- Manually
- Unit tests

fix: MiniKitProvider respects wallet.preference option

---

packages/onchainkit/README.md

Description:  
This pull request corrects a typo in the Quickstart section of packages/onchainkit/README.md, changing "boostrap" to the correct spelling "bootstrap". This improves the clarity and professionalism of the documentation. No other changes were made.

Fix typo in README.md

---

packages/onchainkit/package.json

Removes the Tailwind CLI commands now that we're using Vite for building styles

chore: Remove unused tailwind commands

---

packages/onchainkit/src/buy/components/BuyOnrampItem.tsx
packages/onchainkit/src/identity/components/IdentityCard.tsx
packages/onchainkit/src/identity/components/IdentityLayout.tsx
packages/onchainkit/src/wallet/hooks/useGetETHBalance.ts
packages/onchainkit/src/wallet/hooks/useGetTokenBalance.ts
packages/onchainkit/src/wallet/index.ts

chore: cleanup types and export utils

---

packages/onchainkit/src/minikit/MiniKitProvider.test.tsx
packages/onchainkit/src/minikit/MiniKitProvider.tsx
packages/onchainkit/src/minikit/components/AutoConnect.test.tsx
packages/onchainkit/src/minikit/hooks/useIsInMiniApp.test.tsx
packages/onchainkit/src/minikit/hooks/useIsInMiniApp.tsx

Updates isInMiniApp to use the existance of `sdk.context` because TBA doesn't currently support isInMiniApp

refactor: useIsInMiniApp now uses context to determine if in mini app

---

.changeset/huge-animals-push.md
packages/onchainkit/src/minikit/components/AutoConnect.test.tsx
packages/onchainkit/src/minikit/components/AutoConnect.tsx

MiniKit will now autoconnect if the current connector is a "farcasterMiniApp" connector.
Manually, unit tests.

feat: Accept farcasterMiniApp connector for autoconnect functionality

---

packages/onchainkit/src/internal/components/Sheet.tsx
packages/onchainkit/src/wallet/components/Wallet.tsx
packages/onchainkit/src/wallet/components/WalletDropdown.test.tsx
packages/onchainkit/src/wallet/components/WalletDropdown.tsx

- Moves click outside logic that closes the wallet dropdown to the WalletDropdown component

fix: Move wallet click outside logic to WalletDropdown

---

packages/onchainkit/src/OnchainKitProvider.test.tsx
packages/onchainkit/src/OnchainKitProvider.tsx
packages/onchainkit/src/core/OnchainKitConfig.test.ts
packages/onchainkit/src/core/OnchainKitConfig.ts
packages/onchainkit/src/core/types.ts
packages/onchainkit/src/identity/components/Badge.test.tsx
packages/onchainkit/src/identity/components/Badge.tsx
packages/onchainkit/src/identity/components/DisplayBadge.test.tsx
packages/onchainkit/src/identity/components/DisplayBadge.tsx
packages/onchainkit/src/nft/components/mint/NFTCreator.tsx
packages/onchainkit/src/nft/components/mint/NFTMinters.tsx
packages/onchainkit/src/nft/components/view/NFTOwner.tsx
packages/onchainkit/src/useOnchainKit.test.tsx
packages/onchainkit/src/wallet/components/wallet-advanced-send/components/RenderSendButton.test.tsx

- Removes deprecated `schemaId` OnchainKitProvider prop

chore: Remove deprecated schemaId prop

---

.changeset/sour-carrots-lie.md
packages/onchainkit/src/minikit/hooks/useOpenUrl.ts
packages/onchainkit/src/minikit/index.ts

- Lets user specify how useOpenUrl will handle behavior outside of mini apps

feat: Allow useOpenUrl to specify fallback behavior

---

.changeset/tangy-geese-retire.md
packages/onchainkit/src/minikit/utils/manifestUtils.test.ts
packages/onchainkit/src/minikit/utils/manifestUtils.ts

- Allows users to specify additional properties in `withValidManifest`

fix: Allow additional properties in `withValidManifest`
